[ClassVersion("1.0.0.0"), FriendlyName("SPFarmSolution")]
class MSFT_SPFarmSolution : OMI_BaseResource
{
    [Key, Description("The filename of the WSP package")] string Name;
    [Required, Description("The full path to the WSP file")] string LiteralPath;
    [Write, Description("A list of the web applications to deploy this to")] string WebAppUrls[];
    [Write, Description("Present if the WSP should be deployed, or Absent if it should be removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("The version of the package that is being modified")] string Version;
    [Write, Description("Should the solution be deployed to the farm, or just installed to the farm")] Boolean Deployed;
    [Write, Description("What compatability level should the WSP be deployed as?"), ValueMap{"14","15","All"}, Values{"14","15","All"}] string SolutionLevel;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
