---
- hosts: all
  tasks:
  - name: Enable virt_nfs and virt_sandbox_nfs
    command: setsebool -P {{ item }} 1
    with_items:
      - virt_use_nfs
      - virt_sandbox_use_nfs
      
- hosts: nfs
  vars:
    mountpoint: /dev/sdc
  become: yes
  tasks:
  - name: Install necessary packages
    yum: name={{ item }} state=present
    with_items:
      - nfs-utils
      - rpcbind
  - name: Disable iptables and unmask firewalld
    shell: |
      systemctl disable iptables
      systemctl unmask firewalld
  - name: Make sure firewalld is started now and on start up.
    service: name=firewalld state=started enabled=yes
  - name: Make sure nfs-server is started now and on start up.
    service: name=nfs-server state=started enabled=yes
  - name: Create folder to be mounted for NFS server
    file:
      path: /exports/home
      state: directory

  - name: Add mount path to /etc/exports
    lineinfile:
      path: /etc/exports
      line: "/exports/home *(rw,no_root_squash,no_wdelay)"

  - name: Export /exports/home for volume mounting
    shell: |
      mkfs.xfs {{ mountpoint }}
      mount {{ mountpoint }} /exports/home
      chown -R nfsnobody:nfsnobody /exports/home
      chmod -R 777 /exports/home
      exportfs -a
      firewall-cmd --permanent --add-service=mountd
      firewall-cmd --permanent --add-service=nfs
      firewall-cmd --permanent --add-service=rpc-bind
      firewall-cmd --reload
  - name: Make mount permanent
    shell: echo "$(blkid | grep /dev/sdc | awk '{print $2}') /exports/home        xfs     defaults    0 0" >> /etc/fstab