[ClassVersion("1.0.0"), FriendlyName("xUser")]
class MSFT_xUserResource : OMI_BaseResource
{
  [Key,Description("The name of the User to Create/Modify/Delete")] String UserName;
  [Write,Description("An enumerated value that describes if the user is expected to exist on the machine"),ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
  [Write,Description("The display name of the user")] String FullName;
  [Write,Description("A description for the user")] String Description;
  [Write,Description("The password for the user"),EmbeddedInstance("MSFT_Credential")] String Password;
  [Write,Description("Value used to disable/enable a user account")] Boolean Disabled;
  [Write,Description("Value used to set whether a user's password expires or not")] Boolean PasswordNeverExpires;
  [Write,Description("Value used to require a user to change their password")] Boolean PasswordChangeRequired;
  [Write,Description("Value used to set whether a user can/cannot change their password")] Boolean PasswordChangeNotAllowed;
};
