[ClassVersion("1.0.0")]
Class MSFT_SPWebAppPPSearchDomain
{
    [Required, Description("FQDN of the domain or forest")] String FQDN;
    [Required, Description("Is the FQDN a forest?")] Boolean IsForest;
    [Write, Description("Specifies the credentials to use to connect to the specified domain or forest"), EmbeddedInstance("MSFT_Credential")] String AccessAccount;
};
[ClassVersion("1.0.0.0"), FriendlyName("SPWebAppPeoplePickerSettings")]
class MSFT_SPWebAppPeoplePickerSettings : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Write, Description("Sets a customized query filter to send to Active Directory")] String ActiveDirectoryCustomFilter;
    [Write, Description("Sets the custom query that is sent to Active Directory")] String ActiveDirectoryCustomQuery;
    [Write, Description("Sets the time-out in seconds when a query is issued to Active Directory")] Uint16 ActiveDirectorySearchTimeout;
    [Write, Description("Specifies whether to search only the current site collection")] Boolean OnlySearchWithinSiteCollection;
    [Write, Description("List of all domains/forests that must be searched"), EmbeddedInstance("MSFT_SPWebAppPPSearchDomain")] String SearchActiveDirectoryDomains[];
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
