#! /bin/bash
# Provided by azure extension which comes from template parameters
MIN_HEAP_SIZE=$1
MAX_HEAP_SIZE=$2
CLUSTER_NAME=$3
HAZELCAST_VERSION=$4
SUBSCRIPTION_ID=$5
AAD_CLIENT_ID=$6
AAD_CLIENT_SECRET=$7
AAD_TENANT_ID=$8
GROUP_NAME=$9
CLUSTER_TAG=${10}
CLUSTER_PORT=${11}
chmod +x install_hazelcast
chmod +x modify_configuration
chmod +x modify_version
python3 ./modify_configuration --cluster-name=$CLUSTER_NAME --subscription-id=$SUBSCRIPTION_ID --aad-client-id=$AAD_CLIENT_ID --aad-client-secret=$AAD_CLIENT_SECRET --tenant-id=$AAD_TENANT_ID --group-name=$GROUP_NAME --cluster-tag=$CLUSTER_TAG --cluster-port=$CLUSTER_PORT --filename=hazelcast.xml
python3 ./modify_version --hazelcast-version=$HAZELCAST_VERSION --filename=pom.xml
./install_hazelcast $MIN_HEAP_SIZE $MAX_HEAP_SIZE
sudo cp ./hazelcast.conf /etc/rsyslog.d/
sudo systemctl restart rsyslog.service
sudo cp ./hazelcast.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl start hazelcast
