#! /bin/bash
# Provided by azure extension which comes from template parameters
CLUSTER_NAME=$1
HAZELCAST_VERSION=$2
SUBSCRIPTION_ID=$3
AAD_CLIENT_ID=$4
AAD_CLIENT_SECRET=$5
AAD_TENANT_ID=$6
GROUP_NAME=$7
CLUSTER_TAG=$8
CLUSTER_PORT=$9
chmod +x install_hazelcast
chmod +x modify_configuration
chmod +x modify_version
python3 ./modify_configuration --cluster-name=$CLUSTER_NAME --subscription-id=$SUBSCRIPTION_ID --aad-client-id=$AAD_CLIENT_ID --aad-client-secret=$AAD_CLIENT_SECRET --tenant-id=$AAD_TENANT_ID --group-name=$GROUP_NAME --cluster-tag=$CLUSTER_TAG --cluster-port=$CLUSTER_PORT --filename=hazelcast.xml
python3 ./modify_version --hazelcast-version=$HAZELCAST_VERSION --filename=pom.xml
./install_hazelcast
sudo cp ./hazelcast.conf /etc/rsyslog.d/
sudo systemctl restart rsyslog.service
sudo cp ./hazelcast.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl start hazelcast
