#! /bin/bash
sudo apt-get update -y
sudo apt-get install default-jdk -y
sudo apt-get install maven -y
sudo mvn install

# persist this variable to the VM environment
echo "JAVA_OPTIONS=$JAVA_OPTS" >> /etc/environment
echo "MAVEN_OPTS=$JAVA_OPTS" >> /etc/environment

# set MAVEN_OPTS for hazelcast service
sudo systemctl import-environment MAVEN_OPTS

# create the hazelcast home directory
sudo mkdir /var/hazelcast
sudo cp pom.xml /var/hazelcast
sudo cp ./hazelcast.xml /var/hazelcast/
