#! /bin/bash
MIN_HEAP_SIZE=$1
MAX_HEAP_SIZE=$2
sudo apt-get update -y
sudo apt-get install default-jdk -y
sudo apt-get install maven -y
sudo mvn install

#### minimum heap size
if [ "x$MIN_HEAP_SIZE" = "x" ]
 then
   MIN_HEAP_SIZE=4G
fi
if [ "x$MAX_HEAP_SIZE" = "x" ]
 then
  MAX_HEAP_SIZE=4G
fi

if [ "x$MIN_HEAP_SIZE" != "x" ]; then
  JAVA_OPTS="$JAVA_OPTS -Xms${MIN_HEAP_SIZE}"
fi
if [ "x$MAX_HEAP_SIZE" != "x" ]; then
  JAVA_OPTS="$JAVA_OPTS -Xms${MAX_HEAP_SIZE}"
fi
# persist this variable to the VM environment
echo "JAVA_OPTIONS=$JAVA_OPTS" >> /etc/environment
echo "MAVEN_OPTS=$JAVA_OPTS" >> /etc/environment

# set MAVEN_OPTS for hazelcast service
sudo systemctl import-environment MAVEN_OPTS

# create the hazelcast home directory
sudo mkdir /var/hazelcast
sudo cp pom.xml /var/hazelcast
sudo cp ./hazelcast.xml /var/hazelcast/
