[ClassVersion("1.0.0"), FriendlyName("xNetAdapterBinding")]
class MSFT_xNetAdapterBinding : OMI_BaseResource
{
  [Key,Description("Specifies the alias of a network interface.")] string InterfaceAlias;
  [Key,Description("Specifies the underlying name of the transport or filter in the following form - ms_xxxx, such as ms_tcpip.")] string ComponentId;
  [Write,Description("Specifies if the component ID for the Interface should be Enabled or Disabled."),ValueMap{"Enabled", "Disabled"},Values{"Enabled", "Disabled"}] string State;
  [Read,Description("Returns the current state of the component ID for the Interfaces."),ValueMap{"Enabled", "Disabled","Mixed"},Values{"Enabled", "Disabled","Mixed"}] string CurrentState;
};
