
[ClassVersion("0.1.0.0"), FriendlyName("xWaitForDisk")] 
class MSFT_xWaitForDisk : OMI_BaseResource
{
    [key] uint32 DiskNumber;
    [Write] uint64 RetryIntervalSec;
    [Write] uint32 RetryCount;
};