[ClassVersion("0.1.0.0"), FriendlyName("xPendingReboot")] 
class MSFT_xPendingReboot : OMI_BaseResource
{
  [key, Description("Name of this pending reboot check")] string Name;
  [write, Description("Specifies whether to skip reboots triggered by the Component-Based Servicing component")] boolean SkipComponentBasedServicing;
  [read, Description("A value indicating whether the Component-Based Servicing component requested a reboot")] boolean ComponentBasedServicing;

  [write, Description("Specifies whether to skip reboots triggered by Windows Update")] boolean SkipWindowsUpdate;
  [read, Description("A value indicating whether Windows Update requested a reboot")] boolean WindowsUpdate;

  [write, Description("Specifies whether to skip pending file rename reboots")] boolean SkipPendingFileRename;
  [read, Description("A value indicating whether a pending file rename triggered a reboot")] boolean PendingFileRename;

  [write, Description("Specifies whether to skip reboots triggered by a pending computer rename")] boolean SkipPendingComputerRename;
  [read, Description("A value indicating whether a pending computer rename triggered a reboot")] boolean PendingComputerRename;

  [write, Description("Specifies whether to skip reboots triggered by the ConfigMgr client")] boolean SkipCcmClientSDK;
  [read, Description("A value indicating whether the ConfigMgr client triggered a reboot")] boolean CcmClientSDK;
};

