[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerNetwork")]
class MSFT_xSQLServerNetwork : OMI_BaseResource
{
    [Key, Description("SQL Server instance name of which network protocol should be configured")] String InstanceName;
    [Required, Description("Network protocol name that should be configured"), ValueMap{"tcp"}, Values{"tcp"}] String ProtocolName;
    [Write, Description("Is network protocol should be enabled or disabled")] Boolean IsEnabled;
    [Write, Description("If dynamic ports are used should be set to 0, otherwise leave empty"), ValueMap{"0"}, Values{"0"}] String TCPDynamicPorts;
    [Write, Description("Sets static port for TCP/IP")] String TCPPort;
    [Write, Description("Controls if affected SQL Service should be restarted automatically")] Boolean RestartService;
};
