[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerDatabasePermissions")]
class MSFT_xSQLServerDatabasePermissions : OMI_BaseResource
{
    [Key, Description("The SQL database.")] String Database;
    [Required, Description("The name of the SQL login for the permission set.")] String Name;
    [Required, Description("The set of permissions for the SQL database.")] String Permissions[];
    [Write, Description("The SQL Server for the database.")] String SQLServer;
    [Write, Description("The SQL instance for the database.")] String SQLInstanceName;
};
