[ClassVersion("1.0.0"), FriendlyName("xADDomainDefaultPasswordPolicy")]
class MSFT_xADDomainDefaultPasswordPolicy : OMI_BaseResource
{
    [Key, Description("Name of the domain to which the password policy will be applied")] String DomainName;
    [Write, Description("Whether password complexity is enabled for the default password policy")] Boolean ComplexityEnabled;
    [Write, Description("Length of time that an account is locked after the number of failed login attempts (minutes)")] UInt32 LockoutDuration;
    [Write, Description("Maximum time between two unsuccessful login attempts before the counter is reset to 0 (minutes)")] UInt32 LockoutObservationWindow;
    [Write, Description("Number of unsuccessful login attempts that are permitted before an account is locked out")] UInt32 LockoutThreshold;
    [Write, Description("Minimum length of time that you can have the same password (minutes)")] UInt32 MinPasswordAge;
    [Write, Description("Maximum length of time that you can have the same password (minutes)")] UInt32 MaxPasswordAge;
    [Write, Description("Minimum number of characters that a password must contain")] UInt32 MinPasswordLength;
    [Write, Description("Number of previous passwords to remember")] UInt32 PasswordHistoryCount;
    [Write, Description("Whether the directory must store passwords using reversible encryption")] Boolean ReversibleEncryptionEnabled;
    [Write, Description("Active Directory domain controller to enact the change upon")] String DomainController;    
    [Write, Description("Credentials used to access the domain"), EmbeddedInstance("MSFT_Credential")] String Credential;
};

