[ClassVersion("1.0.0.0"), FriendlyName("SPSearchServiceSettings")]
class MSFT_SPSearchServiceSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Specifies the performance level of the crawler"), ValueMap{"Reduced","PartlyReduced","Maximum"}, Values{"Reduced","PartlyReduced","Maximum"}] string PerformanceLevel;
    [Write, Description("Specifies the contact email used by the crawler")] string ContactEmail;
    [Write, Description("Sets the windows services for search to run as this account"), EmbeddedInstance("MSFT_Credential")] string WindowsServiceAccount;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
