[ClassVersion("1.0.0"),FriendlyName("xPackage")] 
class MSFT_xPackageResource : OMI_BaseResource
{
  [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
  [Key] string Name;
  [required] string Path;
  [Key] string ProductId;
  [write] string Arguments;
  [write,EmbeddedInstance("MSFT_Credential")] string Credential;
  [write] uint32 ReturnCode[];
  [write] string LogPath;
  [read] string PackageDescription;
  [read] string Publisher;
  [read] string InstalledOn;
  [read] uint32 Size;
  [read] string Version;
  [read] boolean Installed;
  [write] string FileHash;
  [write,ValueMap{"SHA1","SHA256","SHA384","SHA512","MD5","RIPEMD160"},Values{"SHA1","SHA256","SHA384","SHA512","MD5","RIPEMD160"}] string HashAlgorithm;
  [write] string SignerSubject;
  [write] string SignerThumbprint;
  [write] string ServerCertificateValidationCallback;
  [write,ValueMap{"LocalMachine","CurrentUser"},Values{"LocalMachine","CurrentUser"}] string InstalledCheckRegHive;
  [write] string InstalledCheckRegKey;
  [write] string InstalledCheckRegValueName;
  [write] string InstalledCheckRegValueData;
  [write] boolean CreateCheckRegValue;
  [write,EmbeddedInstance("MSFT_Credential")] string RunAsCredential;
};
