#!/bin/sh

printf "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
printf "Microsoft Azure Loves CloudFoundry!\n"
printf "CPI:      bosh_azure_cpi\n"
printf "Version:  Beta\n"
printf "Github:   https://github.com/AbelHu/bosh_azure_cpi\n"
printf "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
