
[ClassVersion("1.0.1.0"), FriendlyName("xADDomainTrust")]
class MSFT_xADDomainTrust : OMI_BaseResource
{
    [Write, Description("Should this resource be present or absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Credentials to authenticate to the target domain")] String TargetDomainAdministratorCredential;
    [Key, Description("Name of the AD domain that is being trusted")] String TargetDomainName;
    [Required, Description("Type of trust"), ValueMap{"External","Forest"}, Values{"External","Forest"}] String TrustType;
    [Required, Description("Direction of trust"), ValueMap{"Bidirectional","Inbound","Outbound"}, Values{"Bidirectional","Inbound","Outbound"}] String TrustDirection;
    [Key, Description("Name of the AD domain that is requesting the trust")] String SourceDomainName;
};


