
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerEndpoint")]
class MSFT_xSQLServerEndpoint : OMI_BaseResource
{
    [Key] String EndPointName;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] Uint32 Port;
    [Write] String AuthorizedUser;
    [Write] String SQLServer;
    [Write] String SQLInstanceName;
};

