[ClassVersion("1.0.0.0"), FriendlyName("SPServiceIdentity")]
class MSFT_SPServiceIdentity : OMI_BaseResource
{
    [Key, Description("The name of the service instance to manage")] string Name;
    [Required, Description("The user name of a managed account, LocalService, LocalSystem or NetworkService that will be used to run the service") ] string ManagedAccount;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
