
[ClassVersion("1.0.0.0"), FriendlyName("xMountImage")]
class MSFT_xMountImage : OMI_BaseResource
{
    [Key, Description("Specifies the path of the VHD or ISO file.")] String ImagePath;
    [Write, Description("Specifies the drive letter to mount this VHD or ISO to.")] String DriveLetter;
    [Write, Description("Specifies the storage type of a file. If the StorageType parameter is not specified, then the storage type is determined by file extension."), ValueMap{"ISO","VHD","VHDx","VHDSet"}, Values{"ISO","VHD","VHDx","VHDSet"}] String StorageType;
    [Write, Description("Allows a VHD file to be mounted in read-only or read-write mode. ISO files are mounted in read-only mode regardless of what parameter value you provide."), ValueMap{"ReadOnly","ReadWrite"}, Values{"ReadOnly","ReadWrite"}] String Access;
    [Write, Description("Determines whether the VHD or ISO should be mounted or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

