[ClassVersion("1.0.0.0"), FriendlyName("SPFarmPropertyBag")]
class MSFT_SPFarmPropertyBag : OMI_BaseResource
{
    [Key, Description("The key of the SPFarm property bag")] string Key;
    [Write, Description("Value of the SPfarm property bag")] String Value;
    [Write, Description("Set to present to ensure the SPfarm property exists, or absent to ensure it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
