[ClassVersion("1.0.0.0"), FriendlyName("xADServicePrincipalName")]
class MSFT_xADServicePrincipalName : OMI_BaseResource
{
    [Write, Description("Specifies if the service principal name should be added or remove. Default value is 'Present'. { *Present* | Absent }."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] string Ensure;
    [Key, Description("The full SPN to add or remove, e.g. HOST/LON-DC1.")] string ServicePrincipalName;
    [Write, Description("The user or computer account to add or remove the SPN, e.b. User1 or LON-DC1$. Default value is ''. If Ensure is set to Present, a value must be specified.")] string Account;
};
