---
groups:
  - name: deploy-bosh
    jobs:
      - deploy-bosh

jobs:
- name: deploy-bosh
  serial: true
  plan:
  - aggregate:
    - {trigger: false, get: bosh-setup-template, resource: bosh-setup-template}

  - task: deploy-bosh
    file: bosh-setup-template/bosh-setup/ci/tasks/deploy-bosh.yml
    config:
      params:
        AZURE_CLIENT_ID:                {{azure_client_id}}
        AZURE_CLIENT_SECRET:            {{azure_client_secret}}
        AZURE_TENANT_ID:                {{azure_tenant_id}}
        AZURE_REGION_NAME:              {{azure_region_name}}
        SSH_KEY_DATA:                   {{ssh_key_data}}

resources:
- name: bosh-setup-template
  type: git
  source:
    uri: git@github.com:Azure/azure-quickstart-templates.git
    branch: master
    private_key: {{github_deployment_key__bosh-setup-template}}
