[ClassVersion("1.0.0.0"), FriendlyName("xRoute")]
class MSFT_xRoute : OMI_BaseResource
{
    [Key, Description("Specifies the alias of a network interface.")] string InterfaceAlias;
    [Key, Description("Specifies the IP address family."), ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
    [Key, Description("Specifies a destination prefix of an IP route. A destination prefix consists of an IP address prefix and a prefix length, separated by a slash (/).")] String DestinationPrefix;
    [Key, Description("Specifies the next hop for the IP route.")] String NextHop;
    [Write, Description("Specifies whether the route should exist."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Specifies an integer route metric for an IP route.")] Uint16 RouteMetric;
    [Write, Description("Specifies the publish setting of an IP route."), ValueMap{"No","Yes","Age"}, Values{"No","Yes","Age"}] String Publish;
    [Write, Description("Specifies a preferred lifetime in seconds of an IP route.")] Real64 PreferredLifetime;
};
