[ClassVersion("1.0.0.0")]
Class MSFT_SPWebApplicationHappyHour
{
    [write] uint32 Hour;
    [write] uint32 Minute;
    [write] uint32 Duration;

};
[ClassVersion("1.0.0.0"), FriendlyName("SPWebAppThrottlingSettings")]
class MSFT_SPWebAppThrottlingSettings : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Write, Description("What should the list view threshold for this site be set to")] uint32 ListViewThreshold;
    [Write, Description("Should object model code be able to be override the list view threshold")] boolean AllowObjectModelOverride;
    [Write, Description("What is the list view threshold for site administrators")] uint32 AdminThreshold;
    [Write, Description("What is the maximum number of lookup fields in a single list view")] uint32 ListViewLookupThreshold;
    [Write, Description("Should the happy hour window be enabled for this web app")] boolean HappyHourEnabled;
    [Write, Description("The time window for happy hour"), EmbeddedInstance("MSFT_SPWebApplicationHappyHour")] string HappyHour;
    [Write, Description("What is the limit for unique permissions on a single object in this web app")] uint32 UniquePermissionThreshold;
    [Write, Description("Is request throttling enabled on this web app")] boolean RequestThrottling;
    [Write, Description("Is the change log enabled for this web app")] boolean ChangeLogEnabled;
    [Write, Description("How many days does the change log store data for")] uint32 ChangeLogExpiryDays;
    [Write, Description("Are event handlers enabled in the web application")] boolean EventHandlersEnabled;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};
