[ClassVersion("1.0.0.0"), FriendlyName("SPWebAppPermissions")]
class MSFT_SPWebAppPermissions : OMI_BaseResource
{
    [Key, Description("The url of the web application")] string WebAppUrl;
    [Write, Description("List permissions that need to be configured"), ValueMap{"Manage Lists","Override List Behaviors","Add Items","Edit Items","Delete Items","View Items","Approve Items","Open Items","View Versions","Delete Versions","Create Alerts","View Application Pages"}, Values{"Manage Lists","Override List Behaviors","Add Items","Edit Items","Delete Items","View Items","Approve Items","Open Items","View Versions","Delete Versions","Create Alerts","View Application Pages"}] string ListPermissions[];
    [Write, Description("Site permissions that need to be configured"), ValueMap{"Manage Permissions","View Web Analytics Data","Create Subsites","Manage Web Site","Add and Customize Pages","Apply Themes and Borders","Apply Style Sheets","Create Groups","Browse Directories","Use Self-Service Site Creation","View Pages","Enumerate Permissions","Browse User Information","Manage Alerts","Use Remote Interfaces","Use Client Integration Features","Open","Edit Personal User Information"}, Values{"Manage Permissions","View Web Analytics Data","Create Subsites","Manage Web Site","Add and Customize Pages","Apply Themes and Borders","Apply Style Sheets","Create Groups","Browse Directories","Use Self-Service Site Creation","View Pages","Enumerate Permissions","Browse User Information","Manage Alerts","Use Remote Interfaces","Use Client Integration Features","Open","Edit Personal User Information"}] string SitePermissions[];
    [Write, Description("Personal permissions that need to be configured"), ValueMap{"Manage Personal Views","Add/Remove Personal Web Parts","Update Personal Web Parts"}, Values{"Manage Personal Views","Add/Remove Personal Web Parts","Update Personal Web Parts"}] string PersonalPermissions[];
    [Write, Description("Set all permissions")] boolean AllPermissions;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

