---
- hosts: localhost
  tasks:

  # Host definitions
    - set_fact:
        LICENSE_FILE: "{{ TEMPORARY_SOE_FILE }}"
    - import_role:
        name: common/read_sas_license_information
  
    - name: deleting old cas_size file
      file:
        state: absent
        path: "{{ CAS_URI_FILE }}"

    - name: build json prototype variable
      set_fact:
        JSON_RETURN:
          SAS_DRIVE: "{{ SAS_HOME_PATH }}"
          SAS_STUDIO: "{{ SAS_STUDIO_PATH }}"


    - name: writing json to file
      blockinfile:
        marker: "#DATA#"
        path: "{{ CAS_URI_FILE }}"
        block: >-
          {{ ('' ~ (JSON_RETURN) ).replace("{u'", "{'").replace(" u'", " '") }}
        create: yes

