---


- name: Download sas-orchestration cli
  hosts: [AnsibleController]
  gather_facts: true
  roles:
    - role: prepare_deployment/download_orchestration_cli
  tags:
    - download_orchestration_cli

- name: Download SOE file
  hosts: [AnsibleController]
  roles:
    - role: prepare_deployment/download_soe_file
  tags:
    - download_soe_file

- name: Provide mirror access
  hosts: [MirrorServer]
  become: yes
  become_user: root
  tasks:
    - set_fact:
        USE_MIRROR: True
      when: DEPLOYMENT_MIRROR | default()
    - include_role:
        name: prepare_deployment/deployment_mirror
      when: USE_MIRROR | default()
  tags:
    - deployment_mirror

- name: Create Viya playbook
  hosts: [AnsibleController]
  tasks:
    - set_fact:
        USE_MIRROR: True
      when: DEPLOYMENT_MIRROR | default()
    - include_role:
        name: prepare_deployment/create_viya_playbook
  tags:
    - create_viya_playbook

- name: Update vars.yml
  hosts: [AnsibleController]
  roles:
    - role: prepare_deployment/update_vars
  tags:
    - update_vars

- name: Update sitedefault.yml
  hosts: [AnsibleController]
  roles:
    - role: prepare_deployment/update_sitedefault
  tags:
    - update_sitedefault

- name: Update inventory.yml
  hosts: [AnsibleController]
  roles:
    - role: prepare_deployment/update_inventory
  tags:
    - update_inventory

- name: Get VIRK pre-install playbook
  hosts: [AnsibleController]
  gather_facts: true
  tasks:
    - include_role:
        name: common/read_sas_license_information
      vars:
        LICENSE_FILE: "{{ TEMPORARY_SOE_FILE }}"
    - set_fact:
        VIYA_VERSION: "{{ SAS_LICENSE.viya_version }}"
      when: DEPLOYMENT_MIRROR | default()
    - include_role:
        name: prepare_deployment/get_virk
  tags:
    - get_virk


