#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0"), FriendlyName("xSqlCreateVirtualDisk")] 
class MicrosoftAzure_xSqlCreateVirtualDisk : OMI_BaseResource
{
    [key, Description("The size of virtual disk.")]
    UInt64 DriveSize;
    
    [write, Description("The number of disks.")]
    Uint32 NumberOfColumns;

    [required, Description("The size of disk in bytes.")]
    UInt64 BytesPerDisk;

	[required, Description("Storage Optimization Type")]
	string OptimizationType;

	[write, Description("The flag to indicate if a virtual machine reboot is needed or not")]
    boolean RebootVirtualMachine;
};
