[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerFirewall")]
class MSFT_xSQLServerFirewall : OMI_BaseResource
{
    [Write, Description("An enumerated value that describes if the SQL firewall rules are is expected to be enabled on the machine.\nPresent {default}  \nAbsent   \n"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("UNC path to the root of the source files for installation.")] String SourcePath;
    [Write, Description("Folder within the source path containing the source files for installation.")] String SourceFolder;
    [Key, Description("SQL features to enable firewall rules for.")] String Features;
    [Key, Description("SQL instance to enable firewall rules for.")] String InstanceName;
    [Read, Description("Is the firewall rule for the Database Engine enabled?")] boolean DatabaseEngineFirewall;
    [Read, Description("Is the firewall rule for the Browser enabled?")] boolean BrowserFirewall;
    [Read, Description("Is the firewall rule for Reporting Services enabled?")] boolean ReportingServicesFirewall;
    [Read, Description("Is the firewall rule for Analysis Services enabled?")] boolean AnalysisServicesFirewall;
    [Read, Description("Is the firewall rule for the Integration Services enabled?")] boolean IntegrationServicesFirewall;
 };
