
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerScript")]
class MSFT_xSQLServerScript : OMI_BaseResource
{
    [Required, Description("The name of an instance of the Database Engine. For default instances, only specify the computer name. For named instances, use the format ComputerName\\InstanceName")] String ServerInstance;
    [Key, Description("Path to SQL file that will perform Set action.")] String SetFilePath;
    [Key, Description("Path to SQL file that will perform Get action.")] String GetFilePath;
    [Key, Description("Path to SQL file that will perform Test action.")] String TestFilePath;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to run SQL scripts.")] String Credential;
    [Write, Description("Creates a sqlcmd scripting variable for use in the sqlcmd script, and sets a value for the variable.")] String Variable[];
    [Read, Description("Result of Get action.")] String GetResult[];
};

