[ClassVersion("1.0.0"), FriendlyName("cChocoSource")] 
class cChocoSource : OMI_BaseResource
{
  [Key] string Name;
  [Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
  [write] string source;
  [write,EmbeddedInstance("MSFT_Credential")] String Credentials;
  [write] UInt32 Priority;
};
