[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerFailoverClusterSetup")]
class MSFT_xSQLServerFailoverClusterSetup : OMI_BaseResource
{
    [Key, Description("Prepare or Complete."), ValueMap{"Prepare","Complete"}, Values{"Prepare","Complete"}] String Action;
    [Write, Description("UNC path to the root of the source files for installation.")] String SourcePath;
    [Write, Description("Folder within the source path containing the source files for installation.")] String SourceFolder;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to perform the installation.")] String SetupCredential;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to access SourcePath.")] String SourceCredential;
    [Write, Description("Suppress reboot.")] Boolean SuppressReboot;
    [Write, Description("Force reboot.")] Boolean ForceReboot;
    [Required, Description("SQL features to be installed.")] String Features;
    [Key, Description("SQL instance to be installed.")] String InstanceName;
    [Write, Description("SQL instance ID, if different from InstanceName.")] String InstanceID;
    [Write, Description("Product key for licensed installations.")] String PID;
    [Write, Description("Enabled updates during installation.")] String UpdateEnabled;
    [Write, Description("Source of updates to be applied during installation.")] String UpdateSource;
    [Write, Description("Enable customer experience reporting.")] String SQMReporting;
    [Write, Description("Enable error reporting.")] String ErrorReporting;
    [Write, Description("Name of the resource group to be used for the SQL Server failover cluster.")] String FailoverClusterGroup;
    [Required, Description("Network name for the SQL Server failover cluster.")] String FailoverClusterNetworkName;
    [Write, Description("IPv4 address for the SQL Server failover cluster.")] String FailoverClusterIPAddress;
    [Write, Description("Installation path for shared SQL files.")] String InstallSharedDir;
    [Write, Description("Installation path for x86 shared SQL files.")] String InstallSharedWOWDir;
    [Write, Description("Installation path for SQL instance files.")] String InstanceDir;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Service account for the SQL service.")] String SQLSvcAccount;
    [Read, Description("Output username for the SQL service.")] String SQLSvcAccountUsername;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Service account for the SQL Agent service.")] String AgtSvcAccount;
    [Read, Description("Output username for the SQL Agent service.")] String AgtSvcAccountUsername;
    [Write, Description("Collation for SQL.")] String SQLCollation;
    [Write, Description("Array of accounts to be made SQL administrators.")] String SQLSysAdminAccounts[];
    [Write, Description("Security mode.")] String SecurityMode;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("SA password, if SecurityMode=SQL")] String SAPwd;
    [Write, Description("Root path for SQL database files.")] String InstallSQLDataDir;
    [Write, Description("Path for SQL database files.")] String SQLUserDBDir;
    [Write, Description("Path for SQL log files.")] String SQLUserDBLogDir;
    [Write, Description("Path for SQL TempDB files.")] String SQLTempDBDir;
    [Write, Description("Path for SQL TempDB log files.")] String SQLTempDBLogDir;
    [Write, Description("Path for SQL backup files.")] String SQLBackupDir;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Service account for Analysus Services service.")] String ASSvcAccount;
    [Read, Description("Output username for the Analysis Services service.")] String ASSvcAccountUsername;
    [Write, Description("Collation for Analysis Services.")] String ASCollation;
    [Write, Description("Array of accounts to be made Analysis Services admins.")] String ASSysAdminAccounts[];
    [Write, Description("Path for Analysis Services data files.")] String ASDataDir;
    [Write, Description("Path for Analysis Services log files.")] String ASLogDir;
    [Write, Description("Path for Analysis Services backup files.")] String ASBackupDir;
    [Write, Description("Path for Analysis Services temp files.")] String ASTempDir;
    [Write, Description("Path for Analysis Services config.")] String ASConfigDir;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Service account for Integration Services service.")] String ISSvcAccount;
    [Read, Description("Output username for the Integration Services service.")] String ISSvcAccountUsername;
    [Write, Description("File system folder for Integration Services.")] String ISFileSystemFolder;
};
