/*

**Example**

    SPHealthAnalyzerRuleState DisableDiskSpaceRule
    {
        Name = "Drives are at risk of running out of free space."
        Enabled = $true
        RuleScope   = "All Servers"
        Schedule = "Daily"
        FixAutomatically = $false
        InstallAccount = $InstallAccount
    }
*/

[ClassVersion("1.0.0.0"), FriendlyName("SPHealthAnalyzerRuleState")]
class MSFT_SPHealthAnalyzerRuleState : OMI_BaseResource
{
    [Key, Description("The name of the rule exactly as it appears in central admin")] String Name;
    [Required, Description("Should the rule be enabled?")] Boolean Enabled;
    [Write, Description("What is the scope of this rule"), ValueMap{"All Servers","Any Server"}, Values{"All Servers","Any Server"}] String RuleScope;
    [Write, Description("How often should the rule check"), ValueMap{"Hourly","Daily","Weekly","Monthly","OnDemandOnly"}, Values{"Hourly","Daily","Weekly","Monthly","OnDemandOnly"}] String Schedule;
    [Write, Description("Should the rule fix itself automatically")] Boolean FixAutomatically;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

