---
- type: replace
  path: /instance_groups/name=bosh/properties/azure/azure_stack?
  value: &azure-stack-properties
    domain: ((azure_stack_domain))
    resource: ((azure_stack_resource))
    authentication: ((azure_stack_authentication))
    endpoint_prefix: management
    ca_cert: ((ca_cert))

- type: replace
  path: /cloud_provider/properties/azure/azure_stack?
  value: *azure-stack-properties
