---
- path: /instance_groups/name=bosh/properties/ntp
  type: replace
  value:
  - 1.cn.pool.ntp.org
  - 1.asia.pool.ntp.org
  - 0.asia.pool.ntp.org
- path: /cloud_provider/properties/ntp
  type: replace
  value:
  - 1.cn.pool.ntp.org
  - 1.asia.pool.ntp.org
  - 0.asia.pool.ntp.org
