---
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/buildpacks/fog_connection/azure_storage_dns_suffix?
  error: "Please apply 'use-external-blobstore.yml' and 'use-azure-storage-blobstore.yml' before applying 'use-azure-stack-storage-blobstore.yml'."
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/droplets/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/packages/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/resource_pool/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/buildpacks/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/droplets/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/packages/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/resource_pool/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/buildpacks/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/droplets/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/packages/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))

- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/resource_pool/fog_connection/azure_storage_dns_suffix?
  value: ((blobstore_storage_dns_suffix))
