---
- type: remove
  path: /instance_groups/name=bosh/properties/azure/client_secret

- type: replace
  path: /instance_groups/name=bosh/properties/azure/certificate?
  value: ((certificate))

- type: remove
  path: /cloud_provider/properties/azure/client_secret

- type: replace
  path: /cloud_provider/properties/azure/certificate?
  value: ((certificate))
