[ClassVersion("1.0.0"), FriendlyName("xDNSServerAddress")] 
class MSFT_xDNSServerAddress : OMI_BaseResource
{
  [Required] string Address[];
  [Key] string InterfaceAlias;
  [Key,Write,ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
  [Write] boolean Validate;
};
