[ClassVersion("1.0.0.0"), FriendlyName("SPSearchAuthoritativePage")]
class MSFT_SPSearchAuthoritativePage : OMI_BaseResource
{
    [Key, Description("Search Service Application Name")] String ServiceAppName;
    [Key, Description("Source URI for the authoritative page")] String Path;
    [Write, Description("Level of Authoratitive Page, values between 0.0 and 2.0")] Real32 Level;
    [Write, Description("The resource will either make the page authoritative or demoted based on this value"), ValueMap{"Authoratative","Demoted"}, Values{"Authoratative","Demoted"}] String Action;
    [Write, Description("Ensure the Authoritative is Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5")] String InstallAccount;
};
