[ClassVersion("1.0.0.0"), FriendlyName("SPWebAppPropertyBag")]
class MSFT_SPWebAppPropertyBag : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Key, Description("The key of the SPWebApplication property")] string Key;
    [Write, Description("Value of the SPWebApplication property")] String Value;
    [Write, Description("Set to present to ensure the SPWebApplication property exists, or absent to ensure it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
