--- 
.gi_redhat_8_template: 
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-gi-redhat-8
  stage: golden_image_redhat_8
  only: 
    variables: 
      - $JOB_NAME == "golden_image_redhat_8"
  
.gi_runner_template: 
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-gi_runner
  stage: golden_image_runner
  only: 
    variables: 
      - $JOB_NAME == "golden_image_runner"
  
.gi_windows_10_template: 
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-gi-windows-10 
  stage: golden_image_windows_10
  only: 
    variables: 
      - $JOB_NAME == "golden_image_windows_10"

.gi_windows_7_template: 
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-gi-windows-7
  stage: golden-image-windows-7
  only: 
    variables: 
      - $JOB_NAME == "golden_image_windows_7"
