--- 
.image_template:
  variables: 
    AZURE_LOCATION: ""
    BASELINE: ""
    CREATION_DATE: ""
    IMAGE_ID: ""
    IMAGE_NAME: ""
    IMAGE_VERSION: ""
    OFFER: ""
    OS_TYPE: ""
    PROJECT_CODE: ""
    BU_PROJECT_CODE: ""
    PUBLISHER: ""
    RUN_COST_MODEL: ""
    SITE: ""
    SKU: ""
    SOURCE_VIRTUAL_MACHINE_ID: ""
    SOURCE_VIRTUAL_MACHINE_NAME: "" 
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-image
  stage: image
  only: 
    variables: 
      - $JOB_NAME == "image"
