--- 
.image_delete_template: 
  variables: 
    IMAGE_NAME: ""
    PROJECT_CODE: ""
    BU_PROJECT_CODE: ""
    IMAGE_ID: ""
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - image-delete  
  stage: image_delete
  only: 
    variables: 
      - $JOB_NAME == "image_delete"
