--- 
.launchpad_template: 
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-launchpad
  stage: launchpad
  when: manual
  only: 
    variables: 
      - $JOB_NAME == "launchpad"
