--- 
.notify_snow_error_template: 
  timeout: 3h
  before_script: 
    - "echo '>>> send failure status to snow'"
  script: 
    - run-notify-snow-error
  stage: notify_snow_error
  when: on_failure
  only: 
    variables: 
      - $JOB_NAME == "project"
      - $JOB_NAME == "project_delete"
      - $JOB_NAME == "vde"
      - $JOB_NAME == "vde_delete"
      - $JOB_NAME == "image"
      - $JOB_NAME == "image_delete"
  except: 
    variables: 
      - $SNOW_NUMBER == ""


.notify_snow_success_template: 
  variables: 
    AZURE_VDE_ID: ""     
    IMAGE_ID: ""
    SOURCE_VIRTUAL_MACHINE_NAME: ""
    SOURCE_VIRTUAL_MACHINE_ID: ""
    OS_TYPE: ""
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-notify-snow-success
  stage: notify_snow_success
  when: on_success
  only: 
    variables: 
      - $JOB_NAME == "project"
      - $JOB_NAME == "project_delete"
      - $JOB_NAME == "vde"
      - $JOB_NAME == "vde_delete"
      - $JOB_NAME == "image"
      - $JOB_NAME == "image_delete"
  except: 
    variables: 
      - $SNOW_NUMBER == ""
