--- 
.project_template: 
  variables: 
    ACTION: ""
    CODE: ""
    BU_PROJECT_CODE: ""
    CONFIGURATION_MANAGER: ""
    CREATION_DATE: ""
    DESCRIPTION: ""
    NAME: ""
    PROJECT_APPROVERS: ""
    PROJECT_MANAGER: ""
    SITE: ""
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-project
  only: 
    variables: 
      - $JOB_NAME == "project"
