--- 
.project_delete_template: 
  variables: 
    CODE: ""
    BU_PROJECT_CODE: ""
  timeout: 3h
  before_script: 
    - run-before-script
  script:
    - run-project-delete
  stage: project_delete
  only: 
    variables: 
      - $JOB_NAME == "project_delete"
