--- 
.validate_snow_request_template:
  timeout: 3h
  stage: validate_snow_request
  before_script:
    - echo ">>> validation step is running...."
    - SUBPREFIX=$(echo \"${AZURE_SUBSCRIPTION_ID}\" | cut -c1-5)
  script:
    - run-validate-snow-request 2>&1 | tee errors_validate.log
  artifacts:
    when: on_failure
    paths:
      -  errors_validate.log
