--- 
.vde_delete_template: 
  variables: 
    HOST_NAME: ""
    VDE_TYPE: ""
    PROJECT_CODE: ""
    BU_PROJECT_CODE: ""
    TYPE: ""
    AZURE_VDE_ID: ""
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-vde-delete
  stage: vde_delete
  only: 
    variables: 
      - $JOB_NAME == "vde_delete"
