--- 
.vde_template: 
  variables: 
    AZURE_LOCATION: ""
    AZURE_VDE_ID: ""
    CREATION_DATE: ""
    DATA_DISK_SIZE: ""
    DESCRIPTION: ""
    HOST_NAME: ""
    IMAGE_REFRENCE: ""
    OS_DISK_SIZE: ""
    OS_TYPE: ""
    PROJECT_CODE: ""
    BU_PROJECT_CODE: ""
    REQUESTOR: ""
    RUN_COST_MODEL: ""
    SHARED_ACCESS: ""
    SHUTDOWN_TIME: ""
    SITE: ""
    SOURCE_IMAGE_ID: ""
    START_TIME: ""
    TIME_ZONE: ""
    TYPE: ""
    USER_ACCOUNT: ""
    USER_ADMINS_RIGHTS: ""
    USER_LIST: ""
    USER_RIGHTS_ACCESS: ""
    VDE_TYPE: ""
    VM_INSTANCE: ""
  timeout: 3h
  before_script: 
    - run-before-script
  script: 
    - run-vde
  stage: vde_create
  only: 
    variables: 
      - $JOB_NAME == "vde"
