
[ClassVersion("1.0.0.0"), FriendlyName("xWindowsFeature")] 
class MSFT_xWindowsFeature : OMI_BaseResource
{
    [Key, Description("The name of the role or feature to install or uninstall.")] String Name;
    [Write, Description("Specifies whether the role or feature should be installed or uninstalled. To install the feature, set this property to Present. To uninstall the feature, set the property to Absent."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
    [Write, Description("Specifies whether the subfeatures of the main feature should also be installed.")] Boolean IncludeAllSubFeature;
    [Write, Description("The path to the log file to log this operation.")] String LogPath;
    [Write, Description("A credential, if needed, to install or uninstall the role or feature."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Read, Description("The display name of the retrieved role or feature.")] String DisplayName;
};
