[ClassVersion("1.0.0.0"), FriendlyName("SPIrmSettings")]
class MSFT_SPIrmSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Enable or Disable IRM on this farm"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Use the RMS server published in this farm's Active Directory")] Boolean UseADRMS;
    [Write, Description("Use the specified RMS server, must provide in URL format")] String RMSserver;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
