---

- name: ensure folder exists
  file:
    path: "{{LDIFLOC}}"
    state: directory
    mode: 0700

- name: create base.ldif
  template:
    src: base.ldif.j2
    dest: "{{LDIFLOC}}/base.ldif"
    mode: 0600   

- name: execute base.ldif
  no_log: true
  shell: "ldapadd -x -D {{OLCROOTDN}} -w '{{OLCROOTPW | b64decode }}' -f {{LDIFLOC}}/base.ldif"

- name: create sasldap.ldif
  template:
    src: sasldap.ldif.j2
    dest: "{{LDIFLOC}}/sasldap.ldif"
    mode: 0600   

- name: execute sasldap.ldif
  no_log: true
  shell: "ldapadd -x -D {{OLCROOTDN}} -w '{{OLCROOTPW | b64decode }}' -f {{LDIFLOC}}/sasldap.ldif"


- name: create sasadmin.ldif
  template:
    src: sasadmin.ldif.j2
    dest: "{{LDIFLOC}}/sasadmin.ldif"
    mode: 0600

- name: execute sasadmin.ldif
  no_log: true
  shell: "ldapadd -x -D {{OLCROOTDN}} -w '{{OLCROOTPW | b64decode }}' -f {{LDIFLOC}}/sasadmin.ldif"


- name: create install_users.ldif
  template:
    src: install_users.ldif.j2
    dest: "{{LDIFLOC}}/install_users.ldif"
    mode: 0600   

- name: execute install_users.ldif
  no_log: true
  #shell: "cat {{LDIFLOC}}/install_users.ldif"
  shell: "ldapadd -x -D {{OLCROOTDN}} -w '{{OLCROOTPW | b64decode }}' -f {{LDIFLOC}}/install_users.ldif"


