---
- name: Install openldap server packages
  yum: 
    pkg: "{{ item }}"
    state: present
  with_items:
     - openldap-servers
     - openldap-clients

     
# - debug: msg="'{{ OLCROOTPW | b64decode }}'"
# - debug: var="OLCROOTPW"
# I added a bunch of equals padding to the end to 
- name: encrypt the admin password
  no_log: true
  shell: "slappasswd -s '{{ OLCROOTPW | b64decode }}'"
  register: OLCROOTPW_ENC

- name: encrypt the user password
  no_log: true
  shell: "slappasswd -s '{{ OLCUSERPW | b64decode }}'"
  register: OLCUSERPW_ENC


- name: copy db_config
  shell: cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
  args:
    creates: /var/lib/ldap/DB_CONFIG

- name: apply permissions
  shell: chown -R ldap:ldap /var/lib/ldap


- name: edit hdb.ldif
  lineinfile: 
    dest: /etc/openldap/slapd.d/cn=config/olcDatabase={2}hdb.ldif
    regexp: "^olcSuffix.*"
    line: "olcSuffix: {{OLCSUFFIX}}"
    state: present
    backup: yes

- name: edit hdb.ldif
  lineinfile: 
    dest: /etc/openldap/slapd.d/cn=config/olcDatabase={2}hdb.ldif
    regexp: "^olcRootDN.*"
    line: "olcRootDN: {{OLCROOTDN}}"
    state: present
    backup: yes

- name: edit hdb.ldif
  lineinfile: 
    dest: /etc/openldap/slapd.d/cn=config/olcDatabase={2}hdb.ldif
    regexp: "^olcRootPW.*"
    line: "olcRootPW: {{OLCROOTPW_ENC.stdout}}"
    state: present
    backup: yes

- name: show me the result
  shell: cat /etc/openldap/slapd.d/cn=config/olcDatabase={2}hdb.ldif
  register: result1
- debug: var=result1.stdout_lines

- name: edit monitor.ldif
  replace: 
    dest: /etc/openldap/slapd.d/cn=config/olcDatabase={1}monitor.ldif
    regexp: 'read\ by\ dn\.base\=\".*\"\ read'
    replace: "read by dn.base=\"{{OLCSUFFIX}}\" read"
    backup: yes

- name: run slaptest
  shell: slaptest -u
  register: slaptest
- debug: var=slaptest

- name: Start and enable slapd
  service: 
    name: slapd
    state: started
    enabled: yes
  ignore_errors: yes

- name: check that port is listening
  shell: netstat -lt | grep ldap
  register: ldapport
- debug: var=ldapport
- fail: msg="ldap does not seem to be running"
  when: ldapport.rc != 0


- name: add the following schemas (cosine)
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif 
  register: cosine
- debug: var=cosine

- name: add the following schemas (nis)
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif 
  register: nis
- debug: var=nis

- name: add the following schemas (ldif)
  shell: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif 
  register: inetorgperson
- debug: var=inetorgperson


