[ClassVersion("1.0.0"), FriendlyName("xIisMimeTypeMapping")] 
class MSFT_xIisMimeTypeMapping : OMI_BaseResource
{
  [Key] string Extension;
  [Key] string MimeType;
  [Required,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
