[ClassVersion("1.0.0.0"), FriendlyName("SPManagedPath")]
class MSFT_SPManagedPath : OMI_BaseResource
{
    [Key, Description("The URL of the web application to apply the managed path to - this is ignored for host header web applications")] string WebAppUrl;
    [Key, Description("The relative URL of the managed path")] string RelativeUrl;
    [Required, Description("Should the host header be explicit? If false then it is a wildcard")] boolean Explicit;
    [Required, Description("Is this a host header web application?")] boolean HostHeader;
    [Write, Description("Present ensures managed path exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
