---
# This playbook configures a RAID device with all the available Azure disks

- name: Create a RAID and Configure Storage
  hosts: '{{ target }}'
  vars:
     raid_device: /dev/md0
     system_devices: /dev/sda|/dev/sdb
     raid_mountpoint: /datadrive
  tasks:
    - fail: msg="Variable file_system was not defined. Specify ext4 or xfs"
      when: file_system is not defined

    # CentOS Specific tasks
    - name: Install CentOS packages
      yum: name={{ item }} state=latest
      with_items:
      - mdadm
      - xfsprogs
      when: ansible_distribution =="CentOS"

    # Ubuntu Specific tasks
    - name: Install Ubuntu packages
      apt: name={{ item }} state=latest
      with_items:
      - mdadm
      - xfsprogs
      when: ansible_distribution  == "Ubuntu"

    - name: check for RAID device
      command: mdadm -D {{ raid_device }}
      register: mdadm_check
      failed_when: mdadm_check.rc == 0

    - name: List data disks and exclude system reserved devices
      shell: ls  /dev/sd* | egrep -v "/dev/sda|/dev/sdb" |egrep -v "[0-9]$"
      register: data_devices

    - name: Abort if RAID is not needed
      fail: " {{ data_devices.stdout_lines | length }} devices detected.NO RAID is needed"
      when: "{{ data_devices.stdout_lines | length }} <= 1"

    - debug: msg="{{ data_devices.stdout_lines | length }} Data disks detected {{ data_devices.stdout_lines | join(" ") }}"

    - name: Create RAID device
      shell: echo yes | mdadm --create --verbose {{ raid_device }} --name=data --level=0 --raid-devices={{ data_devices.stdout_lines | length }} {{ data_devices.stdout_lines | join(" ") }}

    - name: Create filesystem
      filesystem: >
        fstype={{ file_system }}
        dev={{ raid_device }}
        force=no

    - name: Create mountpoint for  RAID
      file: >
        path={{ raid_mountpoint }}
        state=directory

    - name: Mount RAID
      mount: >
        name={{ raid_mountpoint }}
        src={{ raid_device }}
        fstype={{ file_system }}
        state=mounted
        opts=defaults,noatime
