[ClassVersion("1.0.0.0"), FriendlyName("SPAlternateUrl")]
class MSFT_SPAlternateUrl : OMI_BaseResource
{
    [Key, Description("The name of the web application to apply the alternate URL to")] String WebAppName;
    [Key, Description("The Zone to use for the alternate URL"), ValueMap{"Default","Intranet","Extranet","Custom","Internet"}, Values{"Default","Intranet","Extranet","Custom","Internet"}] String Zone;
    [Key, Description("The new alternate URL")] String Url;
    [Write, Description("Specifies if the URL has to be configured as internal")] Boolean Internal;
    [Write, Description("Present ensures the URL is set for this zone on this web app, Absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

