[ClassVersion("1.0.0"), FriendlyName("xDnsConnectionSuffix")] 
class MSFT_xDnsConnectionSuffix : OMI_BaseResource
{
  [Key] String InterfaceAlias;
  [Required] String ConnectionSpecificSuffix;
  [Write] Boolean RegisterThisConnectionsAddress;
  [Write] Boolean UseSuffixWhenRegistering;
  [Write, Description("Ensure the presence/absence of the resource"), ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
};

