[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerRSSecureConnectionLevel")]
class MSFT_xSQLServerRSSecureConnectionLevel : OMI_BaseResource
{
    [Key, Description("SQL instance to set secure connection level for.")] String InstanceName;
    [Key, Description("SQL Server Reporting Service secure connection level.")] Uint16 SecureConnectionLevel;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Credential with administrative permissions to the SQL instance.")] String SQLAdminCredential;
};
