[ClassVersion("1.0.0.0"), FriendlyName("SPServiceAppPool")]
class MSFT_SPServiceAppPool : OMI_BaseResource
{
    [Key, Description("The name of application pool")] string Name;
    [Required, Description("The name of the managed account to run this service account as")] string ServiceAccount;
    [Write, Description("Present if the service app pool should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

