[ClassVersion("1.0.0.0"), FriendlyName("SPWebAppSuiteBar")]
class MSFT_SPWebAppSuiteBar : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Write, Description("SP2016+: Url to take the users to when the suite bar logo is clicked")] String SuiteNavBrandingLogoNavigationUrl;
    [Write, Description("SP2016+: Alternative text for the Suite Bar Logo")] String SuiteNavBrandingLogoTitle;
    [Write, Description("SP2016+: URL of the logo for the Suite Bar")] String SuiteNavBrandingLogoUrl;
    [Write, Description("SP2016+: Text to display at the left hand side of the suite bar")] String SuiteNavBrandingText;
    [Write, Description("SP2013+: HTML to inject in the left hand-side of the Suite Bar")] String SuiteBarBrandingElementHtml;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
