[ClassVersion("1.0.0.0"), FriendlyName("SPInstallLanguagePack")]
class MSFT_SPInstallLanguagePack : OMI_BaseResource
{
    [Key, Description("The directory that contains all of the SharePoint binaries")] String BinaryDir;
    [Write, Description("Specify on which dates the installation is allowed"), ValueMap{"mon","tue","wed","thu","fri","sat","sun"}, Values{"mon","tue","wed","thu","fri","sat","sun"}] String BinaryInstallDays[];
    [Write, Description("Specify in which time frame the installation is allowed")] String BinaryInstallTime;
    [Write, Description("Present to install SharePoint. Absent is currently not supported"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

