[ClassVersion("1.0.0.0"), FriendlyName("SPUserProfileSection")]
class MSFT_SPUserProfileSection : OMI_BaseResource
{
    [Key, Description("The internal name of the user profile section")] string Name;
    [Write, Description("Present if the section should exist, absent if it should be removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("The name of the user profile service application this section exists in")] string UserProfileService;
    [Write, Description("The display name of the section")] string DisplayName;
    [Write, Description("A number used to sort sections by")] uint32 DisplayOrder;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
