[ClassVersion("1.0.0.0"), FriendlyName("SPSubscriptionSettingsServiceApp")]
class MSFT_SPSubscriptionSettingsServiceApp  : OMI_BaseResource
{
    [Key, Description("The name of the subscription settings service app")] string Name;
    [Required, Description("The name of the application pool the service app runs in")] String ApplicationPool;
    [Write, Description("The name of the database for the service app")] string DatabaseName;
    [Write, Description("The name of the database server")] String DatabaseServer;
    [Write, Description("Present if the service app should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

