- hosts: localhost
  become: yes
  become_user: root
  vars:
    MOUNT_POINT: "/exports/bastion"
    SOURCE_DISK: ""
    SOURCE_DISK_SIZE: "60.00 GB"
  tasks:
    - import_role:
        name: mount_export_disk