[ClassVersion("1.0.0.0"), FriendlyName("SPDatabaseAAG")]
class MSFT_SPDatabaseAAG : OMI_BaseResource
{
    [Key, Description("The name of the database to put in the AlwaysOn group")] string DatabaseName;
    [Required, Description("Name of the AlwaysOn group on the SQL server - this must already exist")] string AGName;
    [Write, Description("The fileshare to use for the SQL backup when adding to the group")] string FileShare;
    [Write, Description("Present if the database should be in this AlwaysOn group, or Absent if it should not be in the group"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

