[ClassVersion("1.0.0.0"), FriendlyName("SPStateServiceApp")]
class MSFT_SPStateServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the state service app")] string Name;
    [Write, Description("The proxy name, if not specified will be /Name of service app/ Proxy")] string ProxyName;
    [Write, Description("The database credentials for accessing the database"), EmbeddedInstance("MSFT_Credential")] String DatabaseCredentials;
    [Required, Description("The name of the database for the service app")] string DatabaseName;
    [Write, Description("The name of the database server")] string DatabaseServer;
    [Write, Description("Present if the service app should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
