[ClassVersion("1.1.0.0"), FriendlyName("SPWebApplicationExtension")]
class MSFT_SPWebApplicationExtension : OMI_BaseResource
{
    [Key, Description("The URL of the parent web application")] string WebAppUrl;
    [Required, Description("The name of the web application extension")] string Name;
    [Required, Description("The URL of the web application extension")] string Url;
    [Key, Description("Specifies one of the five zones with which the internal URL of this new extension is to be associated."),ValueMap{"Default","Intranet","Internet","Extranet","Custom"}, Values{"Default","Intranet","Internet","Extranet","Custom"}] string Zone; 
    [Write, Description("Should anonymous access be enabled for this web app extension")] boolean AllowAnonymous;
    [Write, Description("The host header to use for the web app extension")] string HostHeader;
    [Write, Description("The path on the local servers to host the IIS web site from")] string Path;
    [Write, Description("The port to run the site on")] string Port;
    [Write, Description("Should this web app extension use SSL")] boolean UseSSL;
    [Write, Description("Present if the web app should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};

