[ClassVersion("1.0.0.0"), FriendlyName("SPDistributedCacheService")]
class MSFT_SPDistributedCacheService : OMI_BaseResource
{
    [Key, Description("A name to assign to this resource - not really used. For example - AppFabricCachingService")] String Name;
    [Write, Description("Present to ensure the current server should be running distributed cache, absent to ensure that it isn't running"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Required, Description("How many MB should be used for the cache. The maximum supported is 16384")] UInt32 CacheSizeInMB;
    [Required, Description("The name of the service account to run the service as. This should already be registered as a managed account in SharePoint")] String ServiceAccount;
    [Write, Description("A list of servers which specifies the order they should provision the cache in to ensure that two servers do not do it at the same time")] String ServerProvisionOrder[];
    [Required, Description("Should the Windows Firewall rules for distributed cache be created?")] Boolean CreateFirewallRules;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
