
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerAvailabilityGroupListener")]
class MSFT_xSQLServerAvailabilityGroupListener : OMI_BaseResource
{
    [Key, Description("The SQL Server instance name of the primary replica.")] String InstanceName;
    [Required, Description("The host name or FQDN of the primary replica.")] String NodeName;
    [Required, Description("The name of the availability group listener, max 15 characters. This name will be used as the Virtual Computer Object (VCO).")] String Name;
    [Write, Description("If the availability group listener should be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("The name of the availability group to which the availability group listener is or will be connected.")] String AvailabilityGroup;
    [Write, Description("The IP address used for the availability group listener, in the format 192.168.10.45/255.255.252.0. If using DCHP, set to the first IP-address of the DHCP subnet, in the format 192.168.8.1/255.255.252.0. Must be valid in the cluster-allowed IP range.")] String IpAddress[];
    [Write, Description("The port used for the availability group listener")] UInt16 Port;
    [Write, Description("If DHCP should be used for the availability group listener instead of static IP address.")] Boolean DHCP;
};

