[ClassVersion("1.0.0.0"), FriendlyName("SPManagedMetaDataServiceAppDefault")]
class MSFT_SPManagedMetaDataServiceAppDefault : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("The name of the managed metadata service application proxy used as default column terms set")] String DefaultSiteCollectionProxyName;
    [Required, Description("The name of the managed metadata service application proxy used as default keyword terms set")] String DefaultKeywordProxyName;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
