[ClassVersion("1.0.0"), FriendlyName("xWebSiteDefaults")] 
class MSFT_xWebSiteDefaults : OMI_BaseResource
{
  [Key, Description("Dummy value because we need a key, always 'Machine'"), ValueMap{"Machine"}, Values{"Machine"}] string ApplyTo;
  [write, Description("sites/siteDefaults/logFile/logFormat"), ValueMap{"W3C","IIS","NCSA","Custom"}, Values{"W3C","IIS","NCSA","Custom"}] string LogFormat;
  [write, Description("sites/siteDefaults/logFile/directory")] string LogDirectory;
  [write, Description("sites/siteDefaults/traceFailedRequestsLogging/directory")] string TraceLogDirectory;
  [write, Description("sites/applicationDefaults/applicationPool")] string DefaultApplicationPool;
  [write, Description("sites/virtualDirectoryDefaults/allowSubDirConfig"), ValueMap{"true","false"}, Values{"true","false"}] string AllowSubDirConfig;
};
