[ClassVersion("1.0.0.0"), FriendlyName("SPCacheAccounts")]
class MSFT_SPCacheAccounts : OMI_BaseResource
{
    [Key, Description("The URL of the web application to set the accounts for")] string WebAppUrl;
    [Required, Description("The account name for the super user")] string SuperUserAlias;
    [Required, Description("The account name for the super reader")] string SuperReaderAlias;
    [Write, Description("Should the web app policy be set for these accounts?")] boolean SetWebAppPolicy;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

