[ClassVersion("1.0.0.0"), FriendlyName("SPInfoPathFormsServiceConfig")]
class MSFT_SPInfoPathFormsServiceConfig : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Present ensures the settings are applied"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("True sets the InfoPath Forms Service to allow users to browse forms")] Boolean AllowUserFormBrowserEnabling;
    [Write, Description("True sets the InfoPath Forms Service to render forms in the browser")] Boolean AllowUserFormBrowserRendering;
    [Write, Description("Sets the maximum connection timeout in milliseconds")] Uint32 MaxDataConnectionTimeout;
    [Write, Description("Sets the default connection timeout in milliseconds")] Uint32 DefaultDataConnectionTimeout;
    [Write, Description("Sets the maximum response size in kb for the user response")] Uint32 MaxDataConnectionResponseSize;
    [Write, Description("True sets the InfoPath Forms Service to require SSL for its connections")] Boolean RequireSslForDataConnections;
    [Write, Description("True sets the InfoPath Forms Service to allow embedded SQL sonnections in Forms")] Boolean AllowEmbeddedSqlForDataConnections;
    [Write, Description("True sets the InfoPath Forms Service to allow User Defined connections")] Boolean AllowUdcAuthenticationForDataConnections;
    [Write, Description("True sets the InfoPath Forms Service to allow Cross-Domain connections")] Boolean AllowUserFormCrossDomainDataConnections;
    [Write, Description("Maximum number of postback allowed per session")] Uint16 MaxPostbacksPerSession;
    [Write, Description("Maximum number of actions that can be triggered per postback")] Uint16 MaxUserActionsPerPostback;
    [Write, Description("Timeout in minutes for active sessions")] Uint16 ActiveSessionsTimeout;
    [Write, Description("Maximum size of user session data")] Uint16 MaxSizeOfUserFormState;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
