[ClassVersion("1.0.0.0"), FriendlyName("SPMinRoleCompliance")]
class MSFT_SPMinRoleCompliance : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("Should the state be set to compliant"), ValueMap{"Compliant", "NonCompliant"}, Values{"Compliant", "NonCompliant"}] string State;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
