#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0"), FriendlyName("xSqlCreateVirtualDataDisk")] 
class MicrosoftAzure_xSqlCreateVirtualDataDisk : OMI_BaseResource
{
    [key, Description("The number of disks.")]
    Uint32 NumberOfDisks;

    [required, Description("The starting device id of disks.")]
    Uint32 StartingDeviceID;

    [write, Description("The number of columns.")]
    Uint32 NumberOfColumns;
	
    [required, Description("The letter of new disk.")]
    string DiskLetter;

    [required, Description("Storage Optimization Type")]
    string OptimizationType;

    [write, Description("The flag to indicate if a virtual machine reboot is needed or not")]
    boolean RebootVirtualMachine;
};
