---
# tasks file for deploy_saswork_restart_service

- name: make a systemd scripts folder in etc
  file:
    path: "{{ SYSTEMD_SCRIPTS_PATH }}"
    state: directory

- name: copy the setup script file to the system
  copy:
    src: setupSasWorkOnStartup.sh
    dest: "{{ SYSTEMD_SCRIPTS_PATH }}"
    mode: "0744"

- name: copy the service unit file to the system
  copy:
    src: setupSasWorkOnStartup.service
    dest: "{{ SYSTEMD_SYSTEM_PATH }}"
    mode: "0644"

- name: enable the new service for the next restart
  systemd:
    daemon_reload: yes
    enabled: yes
    name: setupSasWorkOnStartup.service
    state: started

- name: set the timeout higher on the sas services startup block
  lineinfile:
    path: /usr/lib/systemd/system/sas-viya-all-services.service
    regexp: "^TimeoutSec="
    line: "TimeoutSec=90min"