#!/bin/sh

printf "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
printf "+ Note:\n"
printf "+ You have set this dev box as a DNS.\n"
printf "+ If you reboot it, the public IP address of the dev box may change.\n"
printf "+ You should edit /etc/bind/cf.com.wan to apply the new public IP.\n"
printf "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
