---

- hosts: [CommandLine]
  gather_facts: False
  tasks:

  - name: retrieve certificate from Data Prep environment
    shell:
      cmd: |
        openssl s_client -connect {{ data_prep_host }}:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'
    register: cert

  - name: add the certificate to Consul
    become: yes
    become_user: sas
    shell:
      cmd: |
        source /opt/sas/viya/config/consul.conf
        export CONSUL_HTTP_SSL=true;
        /opt/sas/viya/home/bin/sas-bootstrap-config --token-file /opt/sas/viya/config/etc/SASSecurityCertificateFramework/tokens/consul/default/client.token kv write --key "cacerts/op1" --value "{{ cert.stdout }}" --force

  - name: decode cert
    shell:
      cmd: |
        echo -n "{{ cert.stdout }}" | openssl x509 -text -noout
    register: certdecode
  - debug:
      var: certdecode.stdout_lines

- import_playbook: utility/rebuild-trust-stores.yml

- hosts: [DataAgent]
  gather_facts: False
  become: yes
  become_user: root

  tasks:

  - name: Add the Data Preparation endpoint to the Data Agent Configuration
    lineinfile:
      path: /etc/sysconfig/sas/sas-viya-dagentsrv-default
      regexp: ".*DA_SERVICES_HOST.*"
      line: "DA_SERVICES_HOST={{ data_prep_host }}"


  - name: Add OAuth Secret to Vault
    become: yes
    become_user: sas
    shell:
      cmd: |
        /opt/sas/viya/home/bin/da_init_tenant.sh --customerid shared --secret "{{ secret }}"


  - name: Restart data agent server
    service:
      name: sas-viya-dagentsrv-default
      state: restarted

