[ClassVersion("1.0.0"), FriendlyName("xSSLSettings")]
class MSFT_xSSLSettings : OMI_BaseResource
{
    [Key, Description("Name of website in which to modify the SSL Settings")] String Name;
    [Required, Description("The Bindings in which to modify for the website"), ValueMap{"","Ssl","SslNegotiateCert","SslRequireCert","Ssl128"},Values{"","Ssl","SslNegotiateCert","SslRequireCert","Ssl128"}] String Bindings[];
    [Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"},Description("Whether the bindings should be present or absent")] String Ensure;
};
