
[ClassVersion("1.0.0"), FriendlyName("xIisModule")]
class MSFT_xIisModule : OMI_BaseResource
{
    [Key, Description("The path to the module, usually a dll, to be added to IIS.")] String Path;
    [Required, Description("The logical name of the module to add to IIS.")] String Name;
    [Required, Description("The allowed request Path example: *.php")] String RequestPath;
    [Required, Description("The supported verbs for the module.")] String Verb[];
    [Write, Description("The IIS Site to register the module.")] String SiteName;
    [Write, Description("Should the module be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The type of the module."), ValueMap{"FastCgiModule"}, Values{"FastCgiModule"}] String ModuleType;
    [Read, Description("The End Point is setup.  Such as a Fast Cgi endpoint.")] Boolean EndPointSetup;
};




