[ClassVersion("1.0.0.0"), FriendlyName("SPServiceAppProxyGroup")]
class MSFT_SPServiceAppProxyGroup : OMI_BaseResource
{
    [Key, Description("Name of the Proxy Group to create")] String Name;
    [Write, Description("Present creates the proxy group if it does not already exist, Absent will delete the proxy group if it exists"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("List of service application proxies that belong in this proxy group, all others will be removed")] String ServiceAppProxies[];
    [Write, Description("List of service application proxies to add to this proxy group, existing proxies will remain")] String ServiceAppProxiesToInclude[];
    [Write, Description("List of service application proxies to remove from this proxy grop, all others will remain")] String ServiceAppProxiesToExclude[];
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
