
[ClassVersion("1.0.0.0"), FriendlyName("SPSearchCrawlMapping")]
class MSFT_SPSearchCrawlMapping : OMI_BaseResource
{
    [Key, Description("Search Service Application Name")] String ServiceAppName;
    [Key, Description("Source URI for the crawl mapping")] String Url;
    [Required, Description("Target URI for the crawl mapping")] String Target;
    [Write, Description("Ensure the crawl mapping is Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5")] String InstallAccount;
};
