#
# Copyright (c) 2019, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Install xauth on jumpvm
  hosts: [localhost]
  become_user: root
  become: yes
  gather_facts: false
  tasks:
#    - name: doing the update
#      yum:
#        name: '*'
#        state: latest

    - name: install xauth
      package:
        name: xauth
        state: latest

- name: Installing all updates with zypper
  hosts: [sas_servers]
  become_user: root
  become: yes
  gather_facts: false
  tasks:
    - name: doing the update
      zypper:
        name: '*'
        state: latest

    - name: install required packages
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - xauth
        - libXi6
        - libXt6
        - libXmu6
        - libcap1
        - libjpeg62
        - libpng12-0
        - libfreetype6
        - fontconfig
        - libz1
        - libexpat.so.1
        - libcurl4
        - libXdamage1
        - libxcb-shape0
        - numactl
        - glibc

    - name: install useful packages
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - xclock
        - dstat
        - time
