#
# Copyright (c) 2020, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Create grid.hosts file and installing expect module requirements
  hosts: [va_controllers]
  become_user: root
  become: yes
  gather_facts: yes
  tasks:
  - name: Creating /etc/grid.hosts file
    lineinfile:
      path: "/etc/grid.hosts"
      line: "{{ hostvars[item]['inventory_hostname'] }}"
      state: present
      create: yes
    with_items: "{{ groups['va_controllers'] }},{{ groups['va_workers'] }}"
  - name: Install python2-pip
    package:
      name: python2-pip
      state: latest
  - name: Install pexpect
    pip:
      name: pexpect
      state: latest
      executable: pip2

- name: Run TKGrid install
  hosts: [va_controllers]
  become_user: sasinst
  become: yes
  vars_files:
    - /tmp/ansible_vars.yaml
  tasks:
  - name: Find revision of TKGrid script in path
    find:
      paths: /sasshare/depot/standalone_installs/SAS_High-Performance_Node_Installation
      file_type: directory
    register: revision

  - name: TKGrid questions and responses
    expect:
      chdir: "{{ sasFolder }}"
      echo: yes
      timeout: 180
      command: "{{ item.path }}/Linux_for_x64/TKGrid_Linux_x86_64.sh"
      responses:
        'Shared install or replicate to each node': 'n'
        'Enter additional paths to include in LD_LIBRARY_PATH': "\n"
        'Enter NFS mount to MAPR directory': "\n"
        'Enter additional options to mpirun': "\n"
        'Enter path to use for Utility files': "\n"
        'Enter path to Hadoop': '{{ sasFolder }}/hadoop'
        'Force Root Rank to run on headnode': "\n"
        'Enter full path to machine list': '/etc/grid.hosts'
        'Enter maximum runtime for grid jobs': "\n"
        'Enter value for UMASK': "\n"
        'Perform copy': 'YES'
    with_items: "{{ revision.files }}"

  - name: TKTGDat questions and responses
    expect:
      chdir: "{{ sasFolder }}"
      echo: yes
      timeout: 180
      command: "{{ item.path }}/Linux_for_x64/TKTGDat.sh"
      responses:
        'Shared install or replicate to each node': 'n'
        'Enter full path to machine list': '/etc/grid.hosts'
        'Perform copy': 'YES'
    with_items: "{{ revision.files }}"
        