---
- name: install sas on midtier, metadata head and vacontroller nodes
  hosts: [va_controllers,midtier_servers,metadata_head]
  become: yes
  gather_facts: false
  vars_files:
    - /tmp/ansible_vars.yaml
  tasks:
     - name: Run metadata head, midtier and vacontroller install response file(s)
       become: yes
       shell: |
         # Run install response file for midtier and vacontroller
         # Run complete response file for metadata head
         if [[ "{{ inventory_hostname }}" == *"metadata"* ]]; then
           #{{ sasFolder }}/SASHome/SASFoundation/9.4/utilities/bin/setuid.sh
           /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}.txt
         else
           /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_install.txt
         fi

- name: pause long enough for metadata server to be stable
  hosts: [localhost]
  become: yes
  gather_facts: false
  tasks:
    - name: pause for 5 minutes
      pause:
        minutes: 5

- name: install and configure sas on metadata nodes
  hosts: [metadata_nodes]
  serial: 1
  become: yes
  gather_facts: false
  vars_files:
    - /tmp/ansible_vars.yaml
  tasks:
    - name: Run metadata install and config response files
      become: yes
      shell: |
        /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}.txt
        #{{ sasFolder }}/SASHome/SASFoundation/9.4/utilities/bin/setuid.sh
        #/sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt
    - name: pause for 5 minutes
      pause:
        minutes: 5

- name: configure sas on visual analytics controller
  hosts: [va_controllers]
  become: yes
  gather_facts: false
  tasks:
     - name: Run va install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt

- name: configure sas on midtier head
  hosts: [midtier_head]
  become: yes
  gather_facts: false
  tasks:
     - name: create vfabric folders
       file:
         path: /etc/opt/vmware/vfabric
         state: directory

     - name: Change ownership of vmware folder
       file:
         path: /etc/opt/vmware
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Change ownership of vfabric folder
       file:
         path: /etc/opt/vmware/vfabric
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Run midtier install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt

- name: install sas on midtier node(s)
  hosts: [midtier_nodes]
  become: yes
  gather_facts: false
  tasks:
     - name: create vfabric folders
       file:
         path: /etc/opt/vmware/vfabric
         state: directory

     - name: Change ownership of vmware folder
       file:
         path: /etc/opt/vmware
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Change ownership of vfabric folder
       file:
         path: /etc/opt/vmware/vfabric
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Run midtier node install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt
