//  Create a landing table for Event Hub's events
.create-merge table RawEvents(document:dynamic)

//  Create mapping from JSON ingestion to landing table
.create-or-alter table RawEvents ingestion json mapping 'DirectJson' '[{"column":"document","path":"$","datatype":"dynamic"}]'

//  We modify the ingestion batching policy to make it easy to see records coming ingestion
//  THIS CONFIGURATION SHOULDN'T BE USED IN PRODUCTION:  MaximumBatchingTimeSpan SHOULD BE AT LEAST 1 MINUTE
.alter table RawEvents policy ingestionbatching "{'MaximumBatchingTimeSpan': '0:0:10', 'MaximumNumberOfItems': 10000}"