[ClassVersion("1.0.0.0"), FriendlyName("SPWebAppProxyGroup")]
class MSFT_SPWebAppProxyGroup : OMI_BaseResource
{
    [Key, Description("URL of the web application")] String WebAppUrl;
    [Required, Description("Name of the Service Application Proxy Group")] string ServiceAppProxyGroup; 
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
