[ClassVersion("1.0.0.0"), FriendlyName("SPPowerPointAutomationServiceApp")]
class MSFT_SPPowerPointAutomationServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the service application")] String Name;
    [Write, Description("The name of the service application proxy")] String ProxyName;
    [Write, Description("The name of the application pool to run the service app in")] String ApplicationPool;
    [Write, Description("Specifies the maximum time, in seconds, that items remain in the back-end server cache. The default value is 600 seconds (10 minutes).")] Uint32 CacheExpirationPeriodInSeconds;
    [Write, Description("Specifies the maximum number of presentations that a conversion worker process can convert before recycling. The default value is 5.")] Uint32 MaximumConversionsPerWorker;
    [Write, Description("Specifies the maximum time, in seconds, that a conversion worker process can be unresponsive before being terminated. The default value is 120 seconds.")] Uint32 WorkerKeepAliveTimeoutInSeconds;
    [Write, Description("Specifies the number of active instances of the conversion worker process on each back-end. This value must be less than the Windows Communication Foundation (WCF) connection limit for this computer. The default value is 3.")] Uint32 WorkerProcessCount;
    [Write, Description("Specifies the maximum time, in seconds, that a conversion worker process is given for any single conversion. The default is 300 seconds (5 minutes).")] Uint32 WorkerTimeoutInSeconds;
    [Write, Description("Ensure the crawl rule is Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("POWERSHELL 4 ONLY: The account to run thsi resource as, use PsDscRunAsCredential if using PowerShell 5")] String InstallAccount;
};
