[ClassVersion("1.0.0.0"), FriendlyName("SPProjectServerAdditionalSettings")]
class MSFT_SPProjectServerAdditionalSettings : OMI_BaseResource
{
    [Key, Description("The default zone URL of the Project site to manage settings at")] string Url;
    [Write, Description("What is the minimum build number for the Project Professional client that can connect?")] string ProjectProfessionalMinBuildNumber;
    [Write, Description("What is the default server currency?")] string ServerCurrency;
    [Write, Description("Should all projects be forced to use the server currency?")] boolean EnforceServerCurrency;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
