
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerAlwaysOnService")]
class MSFT_xSQLServerAlwaysOnService : OMI_BaseResource
{
    [Key, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] String SQLServer;
    [Write] String SQLInstanceName;
};

