[ClassVersion("1.0.0.0"), FriendlyName("SPDiagnosticsProvider")]
class MSFT_SPDiagnosticsProvider : OMI_BaseResource
{
    [Key, Description("Name of the Diagnostics Provider to configure")] string Name;
    [Write, Description("Sets the retention period in days")] Uint16 Retention;
    [Write, Description("Sets the maximum retention size in bytes")] Uint64 MaxTotalSizeInBytes;
    [Write, Description("True enables the Diagnostics Provider")] Boolean Enabled;
    [Write, Description("Present to configure the diagnostics provider"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
