
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerPowerPlan")]
class MSFT_xSQLServerPowerPlan : OMI_BaseResource
{
    [Key, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

