apiVersion: v1
kind: Service
metadata:
  name: prom-pls-svc-new
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true" # Use an internal LB with PLS
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: prometheusManagedPls
    service.beta.kubernetes.io/azure-pls-resource-group: '' #Add RG Name for pls deployment
    service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
    service.beta.kubernetes.io/azure-pls-visibility: "*"
spec:
  type: LoadBalancer
  selector:
    # app: myApp
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-kube-prometheus-prometheus # note that this is related to the release name
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
