[ClassVersion("1.0.0.0"), FriendlyName("SPPasswordChangeSettings")]
class MSFT_SPPasswordChangeSettings  : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("The email address to send notifications of password changes to")] string MailAddress;
    [Write, Description("The number of days before password expiry to send send emails")] Uint32 DaysBeforeExpiry;
    [Write, Description("The duration that a password reset will wait for before it times out")] Uint32 PasswordChangeWaitTimeSeconds;
    [Write, Description("How many retries if the password change fails")] Uint32 NumberOfRetries;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
