[ClassVersion("1.0.0.0"), FriendlyName("SPUserProfileSyncConnection")]
class MSFT_SPUserProfileSyncConnection : OMI_BaseResource
{
    [Key, Description("The name of the connection")] string Name;
    [Required, Description("The name of the AD forest to read from")] string Forest;
    [Required, Description("The name of the user profile service that this connection is attached to")] string UserProfileService;
    [Required, Description("The credentials to connect to Active Directory with"), EmbeddedInstance("MSFT_Credential")] string ConnectionCredentials;
    [Required, Description("A list of the OUs to import users from")] string IncludedOUs[];
    [Write, Description("A list of the OUs to ignore users from")] string ExcludedOUs[];
    [Write, Description("The specific AD server to connect to")] string Server;
    [Write, Description("The specific port to connect to")] uint32 Port;
    [Write, Description("Should SSL be used for the connection")] boolean UseSSL;
    [Write, Description("Should disabled accounts be filtered")] boolean UseDisabledFilter;
    [Write, Description("Set to true to run the set method on every call to this resource")] boolean Force;
    [Write, Description("The type of the connection - currently only Active Directory is supported"), ValueMap{"ActiveDirectory","BusinessDataCatalog"}, Values{"ActiveDirectory","BusinessDataCatalog"}] string ConnectionType;
    [Write, Description("Present if the connection should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};
