---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: StorageCluster.v1alpha1.core.libopenstorage.org,StorageNode.v1alpha1.core.libopenstorage.org
  generateName: kube-system-og
  generation: 1
spec:
  targetNamespaces:
  - kube-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  name: portworx-certified
spec:
  channel: stable
  installPlanApproval: Automatic
  name: portworx-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: portworx-operator.v1.2.0