---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-shared-sc
provisioner: kubernetes.io/portworx-volume
parameters:
    repl: "1"
    priority_io: "high"
    sharedv4: "true"
    allow_others: "true"
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-couchdb-sc
provisioner: kubernetes.io/portworx-volume
parameters:
    repl: "1"
    priority_io: "high"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-elastic-sc
provisioner: kubernetes.io/portworx-volume
parameters:
    repl: "1"
    priority_io: "high"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-solr-sc
provisioner: kubernetes.io/portworx-volume
parameters:
    repl: "3"
    priority_io: "high"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-cassandra-sc
provisioner: kubernetes.io/portworx-volume
parameters:
    repl: "3"
    priority_io: "high"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-kafka-sc
provisioner: kubernetes.io/portworx-volume
parameters:
    repl: "3"
    priority_io: "high"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: portworx-db2-sc
provisioner: kubernetes.io/portworx-volume
parameters:
    repl: "3"
    priority_io: "high"
    io_profile: "db"
    block_size: "4096b"
    sharedv4: "false"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-metastoredb-sc
parameters:
    priority_io: high
    io_profile: db
    repl: "3"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-shared-gp
parameters:
    priority_io: high
    repl: "1"
    sharedv4: "true"
    allow_others: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-shared-gp2
parameters:
    priority_io: high
    repl: "2"
    sharedv4: "true"
    allow_others: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-shared-gp3
parameters:
    priority_io: high
    repl: "3"
    sharedv4: "true"
    io_profile: db
    allow_others: "true"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-db-gp
parameters:
    io_profile: "db"
    repl: "1"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-db-gp3
parameters:
    io_profile: "db"
    repl: "3"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-nonshared-gp
parameters:
    priority_io: high
    repl: "1"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-nonshared-gp2
parameters:
    priority_io: medium
    repl: "1"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-nonshared-gp3
parameters:
    priority_io: high
    repl: "3"
allowVolumeExpansion: true
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-shared-gp-allow
parameters:
    priority_io: high
    repl: "1"
    sharedv4: "true"
    io_profile: "cms"
    allow_others: "true"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-db2-rwx-sc
parameters:
    block_size: 4096b
    repl: "3"
    sharedv4: "true"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-db2-rwo-sc
parameters:
    block_size: 4096b
    io_profile: db
    priority_io: high
    repl: "3"
    sharedv4: "false"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-dv-shared-gp
parameters:
    block_size: 4096b
    priority_io: high 
    repl: "1"
    shared: "true"
provisioner: kubernetes.io/portworx-volume
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: portworx-db2-fci-sc
provisioner: kubernetes.io/portworx-volume
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
    block_size: 512b
    io_profile: db
    priority_io: high
    repl: "3"
    sharedv4: "false"
