[ClassVersion("1.0.0.0"), FriendlyName("SPQuotaTemplate")]
class MSFT_SPQuotaTemplate : OMI_BaseResource
{
    [Key, Description("The name of the quota template")] string Name;
    [Write, Description("The maximum storage for sites of this template in MB")] uint32 StorageMaxInMB;
    [Write, Description("The amount of storage for sites of this template that triggers a warning")] uint32 StorageWarningInMB;
    [Write, Description("The maximum number of performance points for sandbox solutions for this template")] uint32 MaximumUsagePointsSolutions;
    [Write, Description("The warning number of performance points for sandbox solutions for this template")] uint32 WarningUsagePointsSolutions;
    [Write, Description("Present to create this template, absent to ensure it does not exist"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
