[ClassVersion("1.0.0.0"), FriendlyName("SPOutgoingEmailSettings")]
class MSFT_SPOutgoingEmailSettings : OMI_BaseResource
{
    [key, Description("The URL of the web application. If you want to set the global settings use the Central Admin URL")] string WebAppUrl;
    [Required, Description("The SMTP server for outgoing mail")] string SMTPServer;
    [Required, Description("The from address to put on messages")] string FromAddress;
    [Required, Description("The email address that replies should be directed to")] string ReplyToAddress;
    [Required, Description("The character set to use on messages")] string CharacterSet;
    [Write, Description("Use TLS when connecting to the SMTP server (SharePoint 2016 and 2019 only)")] boolean UseTLS;
    [Write, Description("The port which is used to connect to the SMTP server (SharePoint 2016 and 2019 only)")] uint32 SMTPPort;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

