
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerEndpointPermission")]
class MSFT_xSQLServerEndpointPermission : OMI_BaseResource
{
    [Key, Description("The SQL Server instance name.")] String InstanceName;
    [Required, Description("The host name or FQDN.")] String NodeName;
    [Write, Description("If the permission should be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("The name of the endpoint.")] String Name;
    [Key, Description("The login to which permission will be set.")] String Principal;
    [Write, Description("The permission to set for the login."), ValueMap{"CONNECT"}, Values{"CONNECT"}] String Permission;
};

