[ClassVersion("1.0.0.0"), FriendlyName("SPWeb")]
class MSFT_SPWeb : OMI_BaseResource
{
    [Key, Description("The URL of the web")] string Url;
    [Write, Description("Present if the web should exist or Absent if it should be removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("The description to apply to the web")] string Description;
    [Write, Description("The Name of the web")] string Name;
    [Write, Description("The Lanhuage (LCID) of the web")] uint32 Language;
    [Write, Description("The WebTemplate to use to create the web")] string Template;
    [Write, Description("True if the web should have unique permissions, otherwise false.")] Boolean UniquePermissions;
    [Write, Description("True if the web should use the parent nav bar, otherwise false.")] Boolean UseParentTopNav;
    [Write, Description("True if the web should be in the quick launch of the parent web, otherwise false.")] Boolean AddToQuickLaunch;
    [Write, Description("True if the web should be added to the top nav bar of the parent web, otherwise false.")] Boolean AddToTopNav;    
    [Write, Description("The e-mail address to which requests for access are sent. Set to emtpy string to disable access requests.")] string RequestAccessEmail;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
