---
# defaults file for 3.3
ORCHESTRATION_DIRECTORY: "/exports/bastion/setup/orchestration"
ORCHESTRATION_INVENTORY: "{{ ORCHESTRATION_DIRECTORY }}/sas_viya_playbook/inventory.ini"
CAS_CONTROLLER_SERVERS_GROUP: CasControllerServers
STATEFUL_SERVICES_SERVERS_GROUP: StatefulServicesServers
PROGRAMMING_SERVICES_SERVERS_GROUP: ProgrammingServicesServers
VISUAL_SERVICES_SERVERS_GROUP: VisualServicesServers
ORCHESTRATION_VARS: "{{ ORCHESTRATION_DIRECTORY }}/sas_viya_playbook/vars.yml"
ORCHESTRATION_SITE_DEFAULT_FILE: "{{ ORCHESTRATION_DIRECTORY }}/sas_viya_playbook/roles/consul/files/sitedefault.yml"
ALL_SERVICES_GROUP: sas-services
