[ClassVersion("1.0.0.0"), FriendlyName("SPSiteUrl")]
class MSFT_SPSiteUrl : OMI_BaseResource
{
    [Key, Description("The URL of the site collection")] string Url;
    [Write, Description("The URL of the Intranet zone")] string Intranet;
    [Write, Description("The URL of the Internet zone")] string Internet;
    [Write, Description("The URL of the Extranet zone")] string Extranet;
    [Write, Description("The URL of the Custom zone")] string Custom;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

