[ClassVersion("1.0.1.0"), FriendlyName("xComputer")]
class MSFT_xComputer : OMI_BaseResource
{
    [key] string Name;
    [write] string DomainName;
    [write,EmbeddedInstance("MSFT_Credential")] String Credential;
    [write,EmbeddedInstance("MSFT_Credential")] String UnjoinCredential;
    [write] string WorkGroupName;
};