apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb-pod
  name: mongodb-pod
spec:
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb-pod
    - port: 9631
      targetPort: 9631
      name: habsup
  selector:
    name: mongodb-pod

