apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: npapp
spec:
  replicas: 3
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: ossacr.azurecr.io/national-parks:latest
        name: web
        args:
          - "--peer"
          - "mongodb-pod" # Main command to run
          - "--bind"
          - "database:national-parks.default"
        ports:
        - name: np-app
          containerPort: 8080
        - name: habsup
          containerPort: 9631
        - name: habsup1
          containerPort: 9638
        - name: mongodb
          containerPort: 27017
