apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: npapp
      protocol: TCP
    - port: 9631
      targetPort: 9631
      name: habsup
      protocol: TCP
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    name: web

