using './main.bicep'

param resourceGroupName = 'GEN-UNIQUE'
param sharePointVersion = 'Subscription-RTM'
param adminUsername = 'GEN-UNIQUE'
param adminPassword =  'GEN-PASSWORD'
param otherAccountsPassword =  'GEN-PASSWORD'
param vmDcSize = 'Standard_B2s'
param vmSqlSize = 'Standard_B2ms'
param vmSharePointSize = 'Standard_B4ms'