[ClassVersion("1.0.0.0"), FriendlyName("xADComputer")]
class MSFT_xADComputer : OMI_BaseResource
{
    [Key, Description("Specifies the name of the computer")] String ComputerName;
    [Write, Description("Specifies the location of the computer, such as an office number")] String Location;
    [Write, Description("Specifies the fully qualified domain name (FQDN) of the computer")] String DnsHostName;
    [Write, Description("Specifies the service principal names for the computer account")] String ServicePrincipalNames[];
    [Write, Description("Specifies the UPN assigned to the computer account")] String UserPrincipalName;
    [Write, Description("Specifies the display name of the computer")] String DisplayName;
    [Write, Description("Specifies the X.500 path of the Organizational Unit (OU) or container where the computer is located")] String Path;
    [Write, Description("Specifies a description of the computer object")] String Description;
    [Write, Description("Specifies if the computer account is enabled")] Boolean Enabled;
    [Write, Description("Specifies the user or group Distinguished Name that manages the computer object")] String Manager;
    [Write, Description("Specifies the Active Directory Domain Services instance to connect to perform the task")] String DomainController;
    [Write, Description("Specifies the user account credentials to use to perform the task"), EmbeddedInstance("MSFT_Credential")] String DomainAdministratorCredential;
    [Write, Description("Specifies the full path to the Offline Domain Join Request file to create.")] String RequestFile;
    [Write, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
    [Read, Description("Returns the X.500 path of the computer object")] String DistinguishedName;
    [Read, Description("Returns the security identifier of the computer object")] String SID;
};
