---

- name: Perform common tasks on all machines
  hosts: openldapall
  become: yes
  become_user: root
  roles:
    - role: openldap/openldapcommon
  tags:
    - openldapcommon

- name: Install OpenLDAP Server on a single machine
  hosts: OpenLdapServer
  become: yes
  become_user: root
  roles:
    - role: openldap/openldapserver
  tags:
    - openldapserver
  tasks:
    - name: Allow openldap server through the firewall
      firewalld:
        service: ldaps
        permanent: true
        state: enabled
        zone: public
        immediate: yes



- name: Install KDC/LDAP Client on one or more machines
  hosts: OpenLdapClients
  become: yes
  become_user: root
  roles:
     - role: openldap/openldapclients
  tags:
     - openldapclients
