---
- hosts: sas_servers
  become: yes
  become_user: root
  roles:
  - post_deployment/deploy_saswork_restart_service

#- hosts: CASControllerServer
#  become: yes
#  become_user: sas
#  tasks:
#  - name: add ELB/Domain to CAS configuration
#    lineinfile:
#      dest: /opt/sas/viya/config/etc/cas/default/casconfig_usermods.lua
#      line: "env.CAS_VIRTUAL_HOST = '{{cas_virtual_host}}'"
#      state: present
#    tags:
#      - cas
#
#  - name: restart cas controller
#    become: yes
#    become_user: root
#    service:
#      name: sas-viya-cascontroller-default
#      state: restarted
#    tags:
#      - cas

- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - replace:
      path: "{{ item }}"
      regexp: '^(.*)password:.*'
      replace: '\1password: <Password Obfiscated by post processing>'
    with_items:
      - /var/log/messages


- name: install mysql client
  hosts: [NeedDatabaseAccessClients]
  gather_facts: False
  become: yes
  become_user: root
  roles:
    - role: post_deployment/install_mysql_client
  tags:
    - install_mysql_client





