[ClassVersion("1.0.1"), FriendlyName("cChocoPackageInstaller")] 
class cChocoPackageInstall : OMI_BaseResource
{
  [Key] string Name;
  [Write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
  [write] string Params;
  [write] string Version;
  [write] string Source;
  [Write] String chocoParams;
  [Write] Boolean AutoUpgrade;
};
