
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerRole")]
class MSFT_xSQLServerRole : OMI_BaseResource
{
    [Key, Description("The name of the SQL login.  If LoginType='WindowsUser' or 'WindowsGroup', this is also the name of the user or group in format DOMAIN\name.")] String Name;
    [Write, Description("Present to ensure that the login has the defined roles, or absent to ensure that these roles are not defined for the login."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("Type of SQL role to add"), ValueMap{"bulkadmin","dbcreator","diskadmin","processadmin","public","securityadmin","serveradmin","setupadmin","sysadmin"}, Values{"bulkadmin","dbcreator","diskadmin","processadmin","public","securityadmin","serveradmin","setupadmin","sysadmin"}] String ServerRole[];
    [Required, Description("The SQL Server for the login.")] String SQLServer;
    [Key, Description("The SQL instance for the login.")] String SQLInstanceName;
};

