[ClassVersion("1.0.0.0"), FriendlyName("SPSearchServiceApp")]
class MSFT_SPSearchServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the search service application")] string Name;
    [Write, Description("The proxy name, if not specified will be /Name of service app/ Proxy")] string ProxyName;
    [Required, Description("The application pool that it should run in")] string ApplicationPool;
    [Write, Description("The URL of the enterprise search center site collection")] string SearchCenterUrl;
    [Write, Description("The name of the database (noting that some search databases will use this as a prefix)")] string DatabaseName;
    [Write, Description("The server that host the databases for this service application")] string DatabaseServer;
    [Write, Description("The default content access account for this search service app"), EmbeddedInstance("MSFT_Credential")] String DefaultContentAccessAccount;
    [Write, Description("Should this search service application be a cloud based service app")] boolean CloudIndex;
    [Write, Description("Present if the service app should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("This setting is moved to SPSearchServiceSettings and deprecated here."), EmbeddedInstance("MSFT_Credential")] string WindowsServiceAccount;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

