[ClassVersion("1.0.0.0"), FriendlyName("SPUserProfileSyncService")]
class MSFT_SPUserProfileSyncService : OMI_BaseResource
{
    [Key, Description("The name of the user profile service for this sync instance")] string UserProfileServiceAppName;
    [Write, Description("Present to ensure the service is running, absent to ensure it is not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("PARAMETER IS NOT USED ANYMORE, WILL BE REMOVED IN V3.0"), EmbeddedInstance("MSFT_Credential")] String FarmAccount;
    [Write, Description("Should the sync service only run when the user profile database is in a writeable state?")] Boolean RunOnlyWhenWriteable;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
