[ClassVersion("1.0.0.0"), FriendlyName("SPBlobCacheSettings")]
class MSFT_SPBlobCacheSettings : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Key, Description("The zone of the web application for which blob cache has to be configured"), ValueMap{"Default","Intranet","Internet","Custom","Extranet"}, Values{"Default","Intranet","Internet","Custom","Extranet"}] string Zone;
    [Required, Description("Specify if the blob cache has to be enabled")] Boolean EnableCache;
    [Write, Description("The location where the blob cache has to store its files")] string Location;
    [Write, Description("The maximum size (in GB) of disk space the blob cache is allowed to use")] Uint16 MaxSizeInGB;
    [Write, Description("The maximum age (in seconds) that a browser caches a blob")] Uint32 MaxAgeInSeconds;
    [Write, Description("Specify the file types that must be stored by the blob cache")] string FileTypes;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

 
