[ClassVersion("1.1"), FriendlyName("xNetworkTeam")]
class MSFT_xNetworkTeam : OMI_BaseResource
{
    [Key] String Name;
    [Write, ValueMap{"SwitchIndependent","LACP","Static"}, Values{"SwitchIndependent","LACP","Static"}] String TeamingMode;
    [Write, ValueMap{"Dynamic","HyperVPort","IPAddresses","MacAddresses","TransportPorts"}, Values{"Dynamic","HyperVPort","IPAddresses","MacAddresses","TransportPorts"}] String LoadBalancingAlgorithm;
    [Required] String TeamMembers[];
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
