[ClassVersion("1.0.0.0"), FriendlyName("SPSearchManagedProperty")]
class MSFT_SPSearchManagedProperty : OMI_BaseResource
{
    [Key, Description("The name of the managed property")] String Name;
    [Key, Description("The name of the search service app that this managed property exists within")] String ServiceAppName;
    [Required, Description("The type of managed property - choose between Binary, DateTime, Decimal, Double, Integer, Text, and YesNo"), ValueMap{"Binary","DateTime","Decimal","Double","Integer","Text","YesNo"}, Values{"Binary","DateTime","Decimal","Double","Integer","Text","YesNo"}] String PropertyType;
    [Write, Description("Should the property be Searchable")] Boolean Searchable;
    [Write, Description("Should the property be Queryable")] Boolean Queryable;
    [Write, Description("Should the property be Retrievable")] Boolean Retrievable;
    [Write, Description("Should the property allow for multiple values to be selected")] Boolean HasMultipleValues;
    [Write, Description("Should the property be Refinable")] Boolean Refinable;
    [Write, Description("Should the property be Sortable")] Boolean Sortable;
    [Write, Description("Should the property be marked as safe for anonymous access")] Boolean SafeForAnonymous;
    [Write, Description("Aliases of the managed property")] String Aliases[];
    [Write, Description("Should the property be case sensitive")] Boolean TokenNormalization;
    [Write, Description("Should the property only match exact content")] Boolean NoWordBreaker;
    [Write, Description("Should the property be mapped to all crawled properties")] Boolean IncludeAllCrawledProperties;
    [Write, Description("List of crawled properties that the property is mapped with")] String CrawledProperties[];
    [Write, Description("Present if the source should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
