[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerLogin")]
class MSFT_xSQLServerLogin : OMI_BaseResource
{
    [Write, Description("If the values should be present or absent. Valid values are 'Present' or 'Absent'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("The name of the SQL login. If LoginType is 'WindowsUser' or 'WindowsGroup' then provide the name in the format DOMAIN\name.")] String Name;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("If LoginType is 'SqlLogin' then a PSCredential is needed for the password to the login.")] String LoginCredential;
    [Write, Description("The SQL login type. Valid values are 'SqlLogin', 'WindowsUser' or 'WindowsGroup'."), ValueMap{"SqlLogin","WindowsUser","WindowsGroup"}, Values{"SqlLogin","WindowsUser","WindowsGroup"}] String LoginType;
    [Key, Description("The SQL Server for the login.")] String SQLServer;
    [Key, Description("The SQL instance for the login.")] String SQLInstanceName;
};
