[ClassVersion("1.0.0"), FriendlyName("xDefaultGatewayAddress")] 
class MSFT_xDefaultGatewayAddress : OMI_BaseResource
{
  [Write] string Address;
  [Key] string InterfaceAlias;
  [Key,Write,ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
};
