
[ClassVersion("0.1.0.0"), FriendlyName("xMountImage")]
class MSFT_xMountImage : OMI_BaseResource
{
    [Key, Description("This setting provides a unique name for the configuration")] String Name;
    [Required, Description("Specifies the path of the VHD or ISO file")] String ImagePath;
    [Write, Description("Specifies the drive letter after the ISO is mounted")] String DriveLetter;
    [Write, Description("Determines whether the setting should be applied or removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

