[ClassVersion("1.0.0"), FriendlyName("xDHCPClient")]
class MSFT_xDHCPClient: OMI_BaseResource
{
  [Required,ValueMap{"Enabled", "Disabled"},Values{"Enabled", "Disabled"}] string State;
  [Key] string InterfaceAlias;
  [Key,Write,ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
};
