[ClassVersion("1.0.0.0"), FriendlyName("xDnsClientGlobalSetting")]
class MSFT_xDnsClientGlobalSetting : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Specifies a list of global suffixes that can be used in the specified order by the DNS client for resolving the IP address of the computer name.")] String SuffixSearchList[];
    [Write, Description("Specifies that devolution is activated.")] Boolean UseDevolution;
    [Write, Description("Specifies the number of labels up to which devolution should occur.")] Uint32 DevolutionLevel;
};
