azs:
- name: z1
- name: z2

vm_types:
- name: compilation
  cloud_properties:
    instance_type: Standard_D1_v2
- name: concourse_web_or_db
  cloud_properties:
    instance_type: Standard_DS2_v2
    security_group: ((security_group))
- name: concourse_worker
  cloud_properties:
    instance_type: Standard_DS4_v2
    security_group: ((security_group))
    ephemeral_disk:
      size: ((ephemeral_disk_size))

disk_types:
- name: default
  disk_size: 10_240

networks:
- name: concourse
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    reserved: [((internal_gw))/30]
    dns: [168.63.129.16]
    azs: [z1, z2]
    cloud_properties:
      virtual_network_name: ((vnet_name))
      subnet_name: ((subnet_name))
- name: public
  type: vip

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: concourse
