[ClassVersion("1.0.0.0"), FriendlyName("SPSearchFileType")]
class MSFT_SPSearchFileType : OMI_BaseResource
{
    [Key, Description("The name of the file type")] string FileType;
    [Key, Description("The name of the search service application")] string ServiceAppName;
    [Write, Description("The description of the file type")] string Description;
    [Write, Description("The mime type of the file type")] string MimeType;
    [Write, Description("The state of the file type")] boolean Enabled;
    [Write, Description("Present if the file type should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

