
[ClassVersion("1.0.0.0"), FriendlyName("xRemoteDesktopAdmin")]
class xRemoteDesktopAdmin : OMI_BaseResource
{
    [Key, Description("Determines whether or not the computer should accept remote connections.  Present sets the value to Enabled and Absent sets the value to Disabled."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("User Authentication.  Setting this value to Secure configures the machine to require NLA."), ValueMap{"Secure","NonSecure"}, Values{"Secure","NonSecure"}] String UserAuthentication;
};



