[ClassVersion("1.0.0.0"), FriendlyName("SPProjectServerTimeSheetSettings")]
class MSFT_SPProjectServerTimeSheetSettings : OMI_BaseResource
{
    [Key, Description("The default zone URL of the Project site to set timesheet settings for")] string Url;
    [Write, Description("Should timesheets allow tracking of overtime and non-billable work types")] boolean EnableOvertimeAndNonBillableTracking;
    [Write, Description("What is the default mode for timesheets to be created in"), ValueMap{"CurrentTaskAssignments","CurrentProjects","NoPrepopulation"}, Values{"CurrentTaskAssignments","CurrentProjects","NoPrepopulation"}] string DefaultTimesheetCreationMode;
    [Write, Description("What is the default tracking unit for timesheets"), ValueMap{"Days","Weeks"}, Values{"Days","Weeks"}] string DefaultTrackingUnit;
    [Write, Description("What is the default reporting unit for timesheets"), ValueMap{"Hours","Days"}, Values{"Hours","Days"}] string DefaultReportingUnit;
    [Write, Description("How many hours are in a standard timesheeet day?")] Real32 HoursInStandardDay;
    [Write, Description("How many hours are in a standard timesheeet week?")] Real32 HoursInStandardWeek;
    [Write, Description("Maximum hours per timesheet")] Real32 MaxHoursPerTimesheet;
    [Write, Description("Minimum hours per timesheet")] Real32 MinHoursPerTimesheet;
    [Write, Description("Maximum hours per day")] Real32 MaxHoursPerDay;
    [Write, Description("Allow future time reporting?")] boolean AllowFutureTimeReporting;
    [Write, Description("Allow new personal tasks?")] boolean AllowNewPersonalTasks;
    [Write, Description("Allow top-level time reporting?")] boolean AllowTopLevelTimeReporting;
    [Write, Description("Require task status manager approval?")] boolean RequireTaskStatusManagerApproval;
    [Write, Description("Require line approval before timesheet approval?")] boolean RequireLineApprovalBeforeTimesheetApproval;
    [Write, Description("Enable timesheet auditing?")] boolean EnableTimesheetAuditing;
    [Write, Description("Enable fixed approval routing?")] boolean FixedApprovalRouting;
    [Write, Description("Enable single entry mode?")] boolean SingleEntryMode;
    [Write, Description("What is the default tracking mode for tasks?"), ValueMap{"PercentComplete","ActualDoneAndRemaining","HoursPerPeriod","FreeForm"}, Values{"PercentComplete","ActualDoneAndRemaining","HoursPerPeriod","FreeForm"}] string DefaultTrackingMode;
    [Write, Description("Force project managers to use the specified tracking mode for each project?")] boolean ForceTrackingModeForAllProjects;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};


