[ClassVersion("1.0.0"), FriendlyName("xIisHandler")] 
class MSFT_xIisHandler : OMI_BaseResource
{
  [Key] string Name;
  [Required,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
};
