[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerReplication")]
class MSFT_xSQLServerReplication : OMI_BaseResource
{
    [Key, Description("SQL Server instance name where replication distribution will be configured")] String InstanceName;
    [Write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
    [Required, ValueMap{"Local", "Remote"}, Values{"Local", "Remote"}] String DistributorMode;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Distributor administration link password")] String AdminLinkCredentials;
    [Write, Description("Distribution database name")] String DistributionDBName;
    [Write, Description("Distributor server name if configuring publisher with remote distributor")] String RemoteDistributor;
    [Required, Description("Publisher working directory")] String WorkingDirectory;
    [Write, Description("Publisher security mode")] Boolean UseTrustedConnection;
    [Write, Description("Force flag for uninstall procedure")] Boolean UninstallWithForce;
};
