[ClassVersion("1.0.0.0"), FriendlyName("SPWorkManagementServiceApp")]
class MSFT_SPWorkManagementServiceApp : OMI_BaseResource
{
    [Key, Description("The name of the work management service application")] string Name;
    [Write, Description("The proxy name, if not specified will be /Name of service app/ Proxy")] string ProxyName;
    [Write, Description("Present to ensure the app exists, Absent to ensure it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("The name of the application pool this will run in")] String ApplicationPool;
    [Write, Description("The minimum amount of time bween EWS sync subscription searches")] uint32 MinimumTimeBetweenEwsSyncSubscriptionSearches;
    [Write, Description("The minimum time between provider refreshes")] uint32 MinimumTimeBetweenProviderRefreshes;
    [Write, Description("The minimum time between search queries")] uint32 MinimumTimeBetweenSearchQueries;
    [Write, Description("The number of subscription syncronisations per EWS sync run")] uint32 NumberOfSubscriptionSyncsPerEwsSyncRun;
    [Write, Description("How many users will EWS calls include at once")] uint32 NumberOfUsersEwsSyncWillProcessAtOnce;
    [Write, Description("How many users are included in a batch for EWS")] uint32 NumberOfUsersPerEwsSyncBatch;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
