[ClassVersion("1.0.0.0"), FriendlyName("SPProjectServerUserSyncSettings")]
class MSFT_SPProjectServerUserSyncSettings : OMI_BaseResource
{
    [Key, Description("The default zone URL of the Project site to set user sync settings for")] string Url;
    [Required, Description("Enable Project Web App Sync")] boolean EnableProjectWebAppSync;
    [Required, Description("Enable Project Site Sync")] boolean EnableProjectSiteSync;
    [Required, Description("Enable Project Site Sync for SharePoint Task List Projects")] boolean EnableProjectSiteSyncForSPTaskLists;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
