
[ClassVersion("1.0"), FriendlyName("xNetworkTeamInterface")]
class MSFT_xNetworkTeamInterface : OMI_BaseResource
{
    [Key] String Name;
    [Required] String TeamName;
    [Write] Uint32 VlanID;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};

