[ClassVersion("1.0.0.0"), FriendlyName("xADRecycleBin")]
class MSFT_xADRecycleBin : OMI_BaseResource
{
    [Key] String ForestFQDN;
    [Required, EmbeddedInstance("MSFT_Credential")] String EnterpriseAdministratorCredential;
    [Read] String RecycleBinEnabled;
    [Read] String ForestMode;
};
