
[ClassVersion("1.0.0"), FriendlyName("xSqlLogin")] 
class MicrosoftAzure_xSqlLogin : OMI_BaseResource
{
    [key] string Name;
    [write,EmbeddedInstance("MSFT_Credential")] string Password;
    [write] string LoginType;
    [write] string ServerRoles[];
    [write] boolean Enabled;
    [write,EmbeddedInstance("MSFT_Credential")] string Credential;
};