[ClassVersion("1.0.0.0"), FriendlyName("SPRemoteFarmTrust")]
class MSFT_SPRemoteFarmTrust : OMI_BaseResource
{
    [Key, Description("A name of the remote farm, used to create token issuer and root authority")] string Name;
    [Required, Description("The URL of a web app in the remote farm, must use HTTPS")] string RemoteWebAppUrl;
    [Required, Description("The URL of a local web app to connect the remote farm to")] string LocalWebAppUrl;
    [Write, Description("Set to present to ensure the trust exists, or absent to ensure it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
