
[ClassVersion("1.0.0.0"), FriendlyName("xWaitForVolume")]
class MSFT_xWaitForVolume : OMI_BaseResource
{
    [Key, Description("Specifies the drive letter of the volume to wait for.")] String DriveLetter;
    [Write, Description("Specifies the number of seconds to wait for the volume to become available.")] Uint32 RetryIntervalSec;
    [Write, Description("The number of times to loop the retry interval while waiting for the volume.")] Uint32 RetryCount;
};
