[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerDatabaseOwner")]
class MSFT_xSQLServerDatabaseOwner : OMI_BaseResource
{
    [Key, Description("The SQL database.")] String Database;
    [Required, Description("The name of the SQL login for the owner.")] String Name;
    [Write, Description("The SQL Server for the database.")] String SQLServer;
    [Write, Description("The SQL instance for the database.")] String SQLInstanceName;
};
