[ClassVersion("1.0.0.0"), FriendlyName("SPInstall")]
class MSFT_SPInstall : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("The directory that contains all of the SharePoint binaries")] String BinaryDir;
    [Required, Description("The product key to use during the installation")] String ProductKey;
    [Write, Description("The install directory to use in the installation, leave blank to use the setup defaults")] String InstallPath;
    [Write, Description("The data directory to use in the installation, leave blank to use the setup defaults")] String DataPath;
    [Write, Description("Present to install SharePoint. Absent is currently not supported"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
};

