@description('Valid locations for all resources. This value can be same as the Region.')
@allowed([
  'australiaeast'
  'brazilsouth'
  'canadacentral'
  'centralus'
  'polandcentral'
  'spaincentral'
  'uaenorth'
  'westeurope'
  'germanywestcentral'
  'italynorth'
  'japaneast'
  'japanwest'
  'uksouth'
  'eastus'
  'eastus2'
  'southafricanorth'
  'southcentralus'
  'southeastasia'
  'switzerlandnorth'
  'swedencentral'
  'westus3'
  'centralindia'
  'eastasia'
  'northeurope'
  'koreacentral'
])
param location string

@description('The name of the Devcenter resource e.g. [devCenterName]-[autoGeneratedUniqueString]-dc. The autoGeneratedUniqueString will be 6 characters long.')
param devCenterName string

@description('The name of the Project resource e.g. [projectName]')
param projectName string

@description('A Microsoft Hosted Network Pool in the region of the resouce group. The name of the Pool resource e.g. [poolName]-[region]-pool')
param poolName string

var roleDefinitionId = '45d50f46-0b78-4001-a660-4198cbe8cd05'
var principalId = deployer().objectId
var devCenterUniqueName = '${devCenterName}-${substring(uniqueString(resourceGroup().id),0,6)}-dc'
var formattedPoolName = '${poolName}-${location}'
var poolPropertyAdmin = 'Enabled'
var poolPropertyNetworkType = 'Managed'
var poolPropertyNetworkName = 'mhn-network'
var image_win11_ent_vs2022 = 'microsoftvisualstudio_visualstudioplustools_vs-2022-ent-general-win11-m365-gen2'
var compute_16c_64gb = 'general_i_16c64gb512ssd_v2'

resource devCenterUnique 'Microsoft.DevCenter/devcenters@2024-10-01-preview' = {
  name: devCenterUniqueName
  location: location
  tags: {
    'hidden-created-with': 'devbox-quickstart-resource'
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    projectCatalogSettings: {
      catalogItemSyncEnableStatus: 'Enabled'
    }
    networkSettings: {
      microsoftHostedNetworkEnableStatus: 'Enabled'
    }
    devBoxProvisioningSettings: {
      installAzureMonitorAgentEnableStatus: 'Enabled'
    }
  }
}

resource project 'Microsoft.DevCenter/projects@2023-04-01' = {
  name: projectName
  location: location
  tags: {
    'hidden-created-with': 'devbox-quickstart-resource'
  }
  properties: {
    devCenterId: devCenterUnique.id
  }
}

resource id_id_principalId_roleDefinitionId 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: project
  name: guid(subscription().id, resourceGroup().id, principalId, roleDefinitionId)
  properties: {
    description: 'Allows deployer to create dev boxes in the project resource.'
    principalId: principalId
    roleDefinitionId: resourceId('Microsoft.Authorization/roleDefinitions', roleDefinitionId)
  }
}

resource projectName_formattedPool 'Microsoft.DevCenter/projects/pools@2024-10-01-preview' = {
  parent: project
  name: formattedPoolName
  location: location
  tags: {
    'hidden-created-with': 'devbox-quickstart-resource'
  }
  properties: {
    devBoxDefinitionType: 'Value'
    devBoxDefinitionName: 'MarketplaceImage'
    devBoxDefinition: {
      imageReference: {
        id: '${devCenterUnique.id}/galleries/default/images/${image_win11_ent_vs2022}'
      }
      sku: {
        name: compute_16c_64gb
      }
    }
    licenseType: 'Windows_Client'
    localAdministrator: poolPropertyAdmin
    managedVirtualNetworkRegions: [
      location
    ]
    virtualNetworkType: poolPropertyNetworkType
    networkConnectionName: '${poolPropertyNetworkName}-${location}'
  }
}
