
[ClassVersion("1.0.0.0"), FriendlyName("SPSearchCrawlerImpactRule")]
class MSFT_SPSearchCrawlerImpactRule : OMI_BaseResource
{
    [Key, Description("Search Service Application Name")] String ServiceAppName;
    [Key, Description("The Site for the crawl impact rule")] String Name;
    [Read, Description("The Behavior (RequestLimit or WaitTime) for this crawl impact rule")] String Behavior;
    [Write, Description("The RequestLimit setting for the crawl impact rule")] UInt32 RequestLimit;
    [Write, Description("The WaitTime setting for the crawl impact rule")] UInt32 WaitTime;
    [Write, Description("Ensure the crawl rule is Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5")] String InstallAccount;
};

