[ClassVersion("1.0.0.0"), FriendlyName("SPSearchMetadataCategory")]
class MSFT_SPSearchMetadataCategory : OMI_BaseResource
{
    [Key, Description("The name of the Metadata Category")] String Name;
    [Key, Description("The name of the search service app that this Metadata Category exists within")] String ServiceAppName;
    [Write, Description("Specifies that when a new crawled property in this category is found, a corresponding managed property is created and mapped to this new crawled property")] Boolean AutoCreateNewManagedProperties;
    [Write, Description("Specifies that if there are unknown properties in this category, these new properties are discovered during a crawl.")] Boolean DiscoverNewProperties;
    [Write, Description("Specifies that all crawled properties of type string are mapped to corresponding managed properties of this category.")] Boolean MapToContents;
    [Write, Description("Present if the result source should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
