
[ClassVersion("1.0.0.0"), FriendlyName("SPAccessServices2010")]
class MSFT_SPAccessServices2010 : OMI_BaseResource
{
    [Key, Description("The name of the service application")] String Name;
    [Required, Description("The name of the application pool to run the service app in")] String ApplicationPool;
    [Write, Description("Present ensures service app exists, absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("POWERSHELL 4 ONLY: The account to run thsi resource as, use PsDscRunAsCredential if using PowerShell 5")] String InstallAccount;
};
