
[ClassVersion("1.0.0.0"), FriendlyName("xWebVirtualDirectory")]
class MSFT_xWebVirtualDirectory : OMI_BaseResource
{
    [Key, Description("Name of website with which Web Application is associated")] string Website;
    [Key, Description("Web application name for the virtual directory")] string WebApplication;
    [Key, Description("Name of virtual directory")] string Name;
    [Required, Description("Physical path for the virtual directory")] string PhysicalPath;
    [Write, Description("Whether virtual directory should be present or absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
};




