---
# Default cf-deployment deploys a (mostly) HA configuration.
# Use this override to deploy the instance of each job,
# into an availability set whose fault domain count and update domain count is 1.
- type: replace
  path: /instance_groups/name=consul/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=nats/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=adapter/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=doppler/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=database/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=diego-api/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=uaa/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=singleton-blobstore/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=api/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=cc-worker/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=router/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=tcp-router/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=scheduler/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=diego-cell/vm_extensions?/-
  value: availability-set-no-HA
- type: replace
  path: /instance_groups/name=log-api/vm_extensions?/-
  value: availability-set-no-HA
