[ClassVersion("1.0.0.0"), FriendlyName("SPAppCatalog")]
class MSFT_SPAppCatalog : OMI_BaseResource
{
    [Key, Description("The URL of the site collection that will be the app catalog for the web app that it is in")] string SiteUrl;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
