
[ClassVersion("1.0.0.0"), FriendlyName("xNetBIOS")]
class MSFT_xNetBIOS : OMI_BaseResource
{
    [Key] String InterfaceAlias;
    [Required, Description("Default - Use NetBios settings from the DHCP server. If static IP, Enable NetBIOS."), ValueMap{"Default","Enable","Disable"}, Values{"Default","Enable","Disable"}] String Setting;
};

