[ClassVersion("1.0.0.0")]
class MSFT_SPProviderRealm
{
    [Key, Description("Realm Url")] String RealmUrl;
    [Required, Description("RealmUrn")] String RealmUrn;
};
[ClassVersion("1.0.0.0"), FriendlyName("SPTrustedIdentityTokenIssuerProviderRealms")]
class MSFT_SPTrustedIdentityTokenIssuerProviderRealms : OMI_BaseResource
{
    [Key, Description("Name of the SPTrustedIdentityTokenIssuer")] String IssuerName;
    [Write, EmbeddedInstance("MSFT_SPProviderRealm"), Description("Realms to set. Those not in this list will be removed")] String ProviderRealms[];
    [Write, EmbeddedInstance("MSFT_SPProviderRealm"), Description("Realms to add. Realms not in this list will be left")] String ProviderRealmsToInclude[];
    [Write, EmbeddedInstance("MSFT_SPProviderRealm"), Description("Realms to remove. Realms not in this list will be left")] String ProviderRealmsToExclude[];
    [Write, Description("Present if the ProviderRealms should be created, or Absent if it should be removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
