[ClassVersion("1.0.0.0"), FriendlyName("xIPAddress")]
class MSFT_xIPAddress : OMI_BaseResource
{
  [Key] string IPAddress;
  [Key] string InterfaceAlias;
  [Write] uint32 PrefixLength;
  [Write,ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
};
