[ClassVersion("1.0.0.0"), FriendlyName("SPProjectServerGroup")]
class MSFT_SPProjectServerGroup : OMI_BaseResource
{
    [Key, Description("The default zone URL of the Project site to manage the group at")] string Url;
    [Key, Description("The name of the group")] string Name;
    [Write, Description("The description of the group")] string Description;
    [Write, Description("What AD group should be used to synchronise membership to this Project Server group, cannot be used with Members, MembersToInclude or MembersToExclude")] string ADGroup;
    [Write, Description("A fixed list of members to be in this group, cannot be used with ADGroup, MembersToInclude or MembersToExclude")] string Members[];
    [Write, Description("A list of members to ensure are in this group, cannot be used with ADGroup or Members")] string MembersToInclude[];
    [Write, Description("A list of members to ensure are not in this group, cannot be used with ADGroup or Members")] string MembersToExclude[];
    [Write, Description("Present if the service app should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
