[ClassVersion("1.0.0.0"), FriendlyName("SPFarmAdministrators")]
class MSFT_SPFarmAdministrators : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("A list of members to set the group to. Those not in this list will be removed")] String Members[];
    [Write, Description("A list of members to add. Members not in this list will be left in the group")] String MembersToInclude[];
    [Write, Description("A list of members to remove. Members not in this list will be left in the group")] String MembersToExclude[];
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

