[ClassVersion("1.0.0.0")]
Class MSFT_SPWebAppAuthenticationMode
{
    [Required, Description("Specifies the used authentication method"), ValueMap{"Classic","NTLM","Kerberos","FBA","Federated"}, Values{"Classic","NTLM","Kerberos","FBA","Federated"}] String AuthenticationMethod;
    [Write, Description("Name of the TrustedIdentityTokenIssuer (only for Federated)")] String AuthenticationProvider;
    [Write, Description("Name of Membership Provider (only for FBA)")] String MembershipProvider;
    [Write, Description("Name of the Role Manager (only for FBA)")] String RoleProvider;
};
[ClassVersion("1.0.0.0"), FriendlyName("SPWebAppAuthentication")]
class MSFT_SPWebAppAuthentication : OMI_BaseResource
{
    [Key, Description("The URL of the web application")] string WebAppUrl;
    [Write, Description("Specifies the authentication for the Default zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Default[];
    [Write, Description("Specifies the authentication for the Intranet zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Intranet[];
    [Write, Description("Specifies the authentication for the Internet zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Internet[];
    [Write, Description("Specifies the authentication for the Extranet zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Extranet[];
    [Write, Description("Specifies the authentication for the Custom zone."), EmbeddedInstance("MSFT_SPWebAppAuthenticationMode")] string Custom[];
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};

