---
# tasks file for readSASLicenseInformation
- name: readLicenseFile
  set_fact:
    SAS_LICENSE: "{{ lookup('sas_license', LICENSE_FILE) }}"
    
# - debug: var="SAS_LICENSES"

- name: setting variables for version 3.3
  set_fact:
    SAS_HOME_PATH: "/SASHome"
    SAS_STUDIO_PATH: "/SASStudio"
    # VIRK_BRANCH: ""
    # VIRK_COMMIT: "e210c8d"
  when: SAS_LICENSE.viya_version == '3.3'
  
- name: setting variables for version 3.4
  set_fact:
    SAS_HOME_PATH: "/SASDrive"
    SAS_STUDIO_PATH: "/SASStudioV"
    # VIRK_BRANCH: ""
    # VIRK_COMMIT: "ee1e6f9"
  when: SAS_LICENSE.viya_version == '3.4'
  
- name: setting url paths and VIYA_VERSION
  set_fact:
    SAS_HOME_URL: "{{ SAS_BASE_URL }}{{ SAS_HOME_PATH }}"
    SAS_STUDIO_URL: "{{ SAS_BASE_URL }}{{ SAS_STUDIO_PATH }}"
    
    