#!/bin/bash
function getBase36()
{
        C=$1
        if [ -z "${C##[0-9]}" ]; then
                echo $C
        else
                echo "$(printf "%d" "'$C") - $(printf "%d" "'A") + 10" | bc
        fi
}
RES=0
for digit in $(echo $1 | grep -o .); do
        RES=$(echo "$RES * 36" | bc)
        RES=$(echo "$RES + $(getBase36 $digit)" | bc)
done
echo $RES
