[ClassVersion("1.0.0.0"), FriendlyName("SPProductUpdate")]
class MSFT_SPProductUpdate : OMI_BaseResource
{
    [Key, Description("The name of the update setup file")] String SetupFile;
    [Write, Description("Shutdown SharePoint services to speed up installation")] Boolean ShutdownServices;
    [Write, Description("Specify on which dates the installation is allowed"), ValueMap{"mon","tue","wed","thu","fri","sat","sun"}, Values{"mon","tue","wed","thu","fri","sat","sun"}] String BinaryInstallDays[];
    [Write, Description("Specify in which time frame the installation is allowed")] String BinaryInstallTime;
    [Write, Description("Present to install SharePoint. Absent is currently not supported"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

