
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerMemory")]
class MSFT_xSQLServerMemory : OMI_BaseResource
{
    [Write, Description("An enumerated value that describes if Min and Max memory is configured"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("Flag to Dynamically allocate SQL memory based on Best Practices")] Boolean DynamicAlloc;
    [Write, Description("Minimum memory value to set SQL Server memory to")] Sint32 MinMemory;
    [Write, Description("Maximum memory value to set SQL Server memory to")] Sint32 MaxMemory;
    [Write, Description("SQL Server to configure memory on")] String SQLServer;
    [Key, Description("SQL Instance to configure memory on")] String SQLInstanceName;
};

