[ClassVersion("1.0.0.0"), FriendlyName("SPDistributedCacheClientSettings")]
class MSFT_SPDistributedCacheClientSettings : OMI_BaseResource
{
    [Key, Description("Unique key for the resource. Set to 'Yes' to apply configuration."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Maximum number of connections to the Distributed Logon Token Cache")] UInt32 DLTCMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Logon Token Cache")] UInt32 DLTCRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Logon Token Cache")] UInt32 DLTCChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed View State Cache")] UInt32 DVSCMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed View State Cache")] UInt32 DVSCRequestTimeout;
    [Write, Description("Channel timeout for the Distributed View State Cache")] UInt32 DVSCChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed Access Cache")] UInt32 DACMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Access Cache")] UInt32 DACRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Access Cache")] UInt32 DACChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed Activity Feed Cache")] UInt32 DAFMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Activity Feed Cache")] UInt32 DAFRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Activity Feed Cache")] UInt32 DAFChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed Activity Feed LMT Cache")] UInt32 DAFCMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Activity Feed LMT Cache")] UInt32 DAFCRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Activity Feed LMT Cache")] UInt32 DAFCChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed Bouncer Cache")] UInt32 DBCMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Bouncer Cache")] UInt32 DBCRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Bouncer Cache")] UInt32 DBCChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed Default Cache")] UInt32 DDCMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Default Cache")] UInt32 DDCRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Default Cache")] UInt32 DDCChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed Search Cache")] UInt32 DSCMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Search Cache")] UInt32 DSCRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Search Cache")] UInt32 DSCChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed Security Trimming Cache")] UInt32 DTCMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Security Trimming Cache")] UInt32 DTCRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Security Trimming Cache")] UInt32 DTCChannelOpenTimeOut;
    [Write, Description("Maximum number of connections to the Distributed Server to Application Server Cache")] UInt32 DSTACMaxConnectionsToServer;
    [Write, Description("Request timeout for the Distributed Server to Application Server Cache")] UInt32 DSTACRequestTimeout;
    [Write, Description("Channel timeout for the Distributed Server to Application Server Cache")] UInt32 DSTACChannelOpenTimeOut;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
