
[ClassVersion("1.0.0.0"), FriendlyName("xWaitForAvailabilityGroup")]
class MSFT_xWaitForAvailabilityGroup : OMI_BaseResource
{
    [Key, Description("Availability Group Name")] String Name;
    [Write, Description("Interval to check for Availability Group")] Uint64 RetryIntervalSec;
    [Write, Description("Maximum number of retries to check Availabilty group creation")] Uint32 RetryCount;
};

