[ClassVersion("1.0"), FriendlyName("cConfigureSharepoint")]
class SAMPLE_cConfigureSharepoint : OMI_BaseResource
{
[Key] string DomainName;
[Required,EmbeddedInstance("MSFT_Credential")] string DomainAdministratorCredential;
[Required,EmbeddedInstance("MSFT_Credential")] string SetupUserAccountCredential;
[Required,EmbeddedInstance("MSFT_Credential")] string FarmAccountCredential;
[Required,EmbeddedInstance("MSFT_Credential")] string FarmPassphrase;
[Key] string DatabaseName;
[Key] string AdministrationContentDatabaseName;
[Key] string DatabaseServer;
[Key] string Configuration;
};
