
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerDatabaseRole")]
class MSFT_xSQLServerDatabaseRole : OMI_BaseResource
{
    [Write, Description("An enumerated value that describes if the login has the role on the database.\nPresent {default}  \nAbsent   \n"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("The name of the SQL login or the role on the database.")] String Name;
    [Write, Description("The SQL Server for the database.")] String SQLServer;
    [Write, Description("The SQL instance for the database.")] String SQLInstanceName;
    [Required, Description("The SQL database for the role.")] String Database;
    [Required, Description("The SQL role for the database.")] String Role;
};

