---

- set_fact:
    TEMPORARY_TGZ_FILE: "/tmp/SAS_Viya_playbook.tgz"

- name: set mirror option
  set_fact:
    MIRROR_OPT: " --repository-warehouse {{ MIRROR_URL }}"
  when: USE_MIRROR | default()


- name: build playbook
  shell: |
    cp "{{ TEMPORARY_SOE_FILE }}" "{{ TEMPORARY_SOE_FILE }}.tmp"
    {{ UTILITIES_DIR }}/sas-orchestration build --input {{ TEMPORARY_SOE_FILE }} --deployment-type default {{ MIRROR_OPT }}
  args:
   chdir: /tmp

- name: untar playbook
  unarchive:
    src: "{{ TEMPORARY_TGZ_FILE }}"
    dest: "{{ ANSIBLE_DIR }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755

- name: restore soe file
  shell: |
    mv -f "{{ TEMPORARY_SOE_FILE }}.tmp" "{{ TEMPORARY_SOE_FILE }}"
  args:
   chdir: /tmp
