[ClassVersion("1.0.0"), FriendlyName("xEnvironment")] 
class MSFT_xEnvironmentResource : OMI_BaseResource
{
  [Key, Description("The name of the environment variable for which you want to ensure a specific state.")] String Name;
  [Write, Description("The desired value for the environment variable.")] String Value;
  [Write, Description("Specifies if the environment varaible should exist."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
  [Write, Description("Indicates whether or not the environment variable is the Path variable.")] Boolean Path;
  [Write, Description("Indicates the target where the environment variable should be set."), ValueMap{"Process", "Machine"}, Values{"Process", "Machine"}] String Target[];
};
