[ClassVersion("1.0.1.0"), FriendlyName("xWaitForADDomain")]
class MSFT_xWaitForADDomain : OMI_BaseResource
{
    [Key] String DomainName;
    [Write, EmbeddedInstance("MSFT_Credential")] String DomainUserCredential;
    [Write] uint64 RetryIntervalSec;
    [Write] uint32 RetryCount;
    [Write] uint32 RebootRetryCount;
};
