[ClassVersion("1.0.0.0"), FriendlyName("xSQLAlias")]
class MSFT_xSQLAlias : OMI_BaseResource
{
    [Key, Description("The name of Alias (e.g. svr01\\inst01).")] String Name;
    [Write, Description("Protocol to use when connecting. Valid values are 'TCP' or 'NP' (Named Pipes). Default value is 'TCP'."), ValueMap{"TCP","NP"}, Values{"TCP","NP"}] String Protocol;
    [Key, Description("The SQL Server you are aliasing (the netbios name or FQDN).")] String ServerName;
    [Write, Description("The TCP port SQL is listening on. Only used when protocol is set to 'TCP'. Default value is port 1433.")] UInt16 TcpPort;
    [Read, Description("Named Pipes path from the Get-TargetResource method.")] String PipeName;
    [Write, Description("Determines whether the alias should be added or removed. Default value is 'Present'"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
