[ClassVersion("1.0.0.0"), FriendlyName("SPInstallPrereqs")]
class MSFT_SPInstallPrereqs : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Required, Description("The full path to prerequisiteinstaller.exe")] String InstallerPath;
    [Required, Description("Should the installer download prerequisites from the internet or not")] Boolean OnlineMode;
    [Write, Description("The path to the Windows Server Operating System SXS source files, for use in closed environments without access to Windows Update")] String SXSpath;
    [Write, Description("The path to the installer for this prerequisite (SP2013 and SP2016)")] String SQLNCli;
    [Write, Description("The path to the installer for this prerequisite (SP2013 only)")] String PowerShell;
    [Write, Description("The path to the installer for this prerequisite (SP2013 only)")] String NETFX;
    [Write, Description("The path to the installer for this prerequisite (SP2013 only)")] String IDFX;
    [Write, Description("The path to the installer for this prerequisite (SP2013 and SP2016)")] String Sync;
    [Write, Description("The path to the installer for this prerequisite (SP2013 and SP2016)")] String AppFabric;
    [Write, Description("The path to the installer for this prerequisite (SP2013 and SP2016)")] String IDFX11;
    [Write, Description("The path to the installer for this prerequisite (SP2013 and SP2016)")] String MSIPCClient;
    [Write, Description("The path to the installer for this prerequisite (SP2013 only)")] String WCFDataServices;
    [Write, Description("The path to the installer for this prerequisite (SP2013 only)")] String KB2671763;
    [Write, Description("The path to the installer for this prerequisite (SP2013 and SP2016)")] String WCFDataServices56;
    [Write, Description("The path to the installer for this prerequisite (SP2016 only)")] String MSVCRT11;
    [Write, Description("The path to the installer for this prerequisite (SP2016 only)")] String MSVCRT14;
    [Write, Description("The path to the installer for this prerequisite (SP2016 only)")] String KB3092423;
    [Write, Description("The path to the installer for this prerequisite (SP2016 only)")] String ODBC;
    [Write, Description("The path to the installer for this prerequisite (SP2016 only)")] String DotNetFx;
    [Write, Description("The path to the installer for this prerequisite (SP2019 only)")] String DotNet472;
    [Write, Description("The path to the installer for this prerequisite (SP2019 only)")] String MSVCRT141;
    [Write, Description("Present to install the prerequisites. Absent is currently not supported"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
};
