- name: "Update External Connection Metadata"
  hosts: localhost
  become: yes
  vars_files:
    - /tmp/ansible_vars.yaml
  vars:
    metadata_server_host: "metadata-0.internal.cloudapp.net"
    metadata_server_port: 8561
    metadata_username: "sasadm@saspw"
    metadata_password: "{{ AdminPassword }}"
    external_host_name: "{{ LoadbalancerDNS }}"
    external_port: 443
    external_protocol: "https"

  tasks:
    - name: "Create SetWebURLs.sas script from template"
      template:
        src: "../responsefiles/SetWebURLs.sas.j2"
        dest: "/tmp/SetWebURLs.sas"
