- name: "Run sas scripts to update external connection urls in metadata"
  hosts: [metadata_servers]
  become: yes
  vars_files:
    - /tmp/ansible_vars.yaml

  tasks:
    - name: "Execute setWebURLs.sas script to update external connection metadata"
      command: "{{ SASFolder }}/SASHome/SASFoundation/9.4/sas -stdio /sasshare/sasfiles/{{ item }}.sas"
      register: sas_script_output
      with_items:
        - setSASWebUrls
        - setFoundationServices
        - setContentServerConnection
        - setUrlOverride
        - setCDPSKnownHosts

    - debug:
        var: sas_script_output
