---
- name: Copy response files to sasshare
  hosts: [localhost]
  become_user: root
  become: yes
  gather_facts: false
  vars_files:
    - /sas/install/ansible/vars.yaml
  tasks:
     - name: create the responsefiles directory in sasshare
       file:
         path: /sasshare/responsefiles
         state: directory
         
     - name: create the scripts directory in sasshare
       file:
         path: /sasshare/scripts
         state: directory

     - name: copy the install script to sasshare
       copy:
         src: ../scripts/run_install_as_user.sh
         dest: /sasshare/scripts
         mode: '0755'

     - name: replace variables in response files
       template:
         src: "/sas/install/responsefiles/{{ item }}.j2"
         dest: "/sasshare/responsefiles/{{ item }}"
         owner: sasinst
         group: sas
       with_items:
         - metadata.txt
         - midtier.txt
         - va.txt

- name: install sas on metadata
  hosts: [metadata_servers]
  become_user: root
  become: yes
  gather_facts: false
  tasks:
     - name: Run metadata install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/metadata.txt

- name: install sas on visual analytics controller
  hosts: [va_controllers]
  become_user: root
  become: yes
  gather_facts: false
  tasks:
     - name: Run va install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/va.txt

- name: install sas on midtier
  hosts: [midtier_servers]
  become_user: root
  become: yes
  gather_facts: false
  tasks:
     - name: create vfabric folders
       file:
         path: /etc/opt/vmware/vfabric
         state: directory

     - name: Change ownership of vmware folder
       file:
         path: /etc/opt/vmware
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Change ownership of vfabric folder
       file:
         path: /etc/opt/vmware/vfabric
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Run midtier install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/midtier.txt
