- name: "Update External Connection Metadata"
  hosts: localhost
  become: yes
  
  vars:
    metadata_server_host: "jowood-94-ext-host-test.dep-cloud.sashq-d.openstack.sas.com"
    metadata_server_port: 8561
    metadata_username: "sasadm@saspw"
    metadata_password: "Go4thsas"
    external_host_name: "my.external.host.sas.com"
    external_port: 443
    external_protocol: "https"
    sas_exec_dir: "/local/SASHome/SASFoundation/9.4"

  tasks:
    - name: "Create SetWebURLs.sas script from template"
      template:
        src: "SetWebURLs.sas.j2"
        dest: "SetWebURLs.sas"

    - name: "Execute SetWebURLs.sas script to update external connection metadata"
      command: "{{ sas_exec_dir }}/sas -stdio SetWebURLs.sas"
      register: ext_host_output

    - debug:
        var: ext_host_output