sas_user: sas
default_ulimits_dir: /etc/security/limits.d
ulimit_file_loc: /etc/security/limits.d/sas_9.4v_limits.conf
ulimits:
  -
    comment: "#Added (1) for Viya Installation"
    domain: "*"
    item: nofile
    type: "-"
    use_max: true
    use_min: false
    value: 20480
  -
    comment: "#Added (3) for Viya Installation"
    domain: "*"
    item: nproc
    type: "-"
    use_max: true
    use_min: false
    value: 10240
  -
    comment: "Added (4) for SAS Viya VI Installation"
    domain: "{{sas_user}}"
    item: nofile
    type: "-"
    use_max: true
    use_min: false
    value: 20480
  -
    comment: "Added (5) for SAS Viya VI Installation"
    domain: "{{sas_user}}"
    item: nproc
    type: "-"
    use_max: true
    use_min: false
    value: 10240
