[ClassVersion("1.0.0.0"), FriendlyName("SPSearchResultSource")]
class MSFT_SPSearchResultSource : OMI_BaseResource
{
    [Key, Description("The name of the result source")] String Name;
    [Key, Description("The scope at which the Result Source will be created. Options are SSA, SPSite or SPWeb"), ValueMap{"SSA","SPSite","SPWeb"}, Values{"SSA","SPSite","SPWeb"}] String ScopeName;
    [Key, Description("The URI of the site where to create the result source. Leave empty to have it created globally")] String ScopeUrl;
    [Required, Description("The name of the search service application to associate this result source with")] String SearchServiceAppName;
    [Required, Description("The query to pass to the provider source")] String Query;
    [Required, Description("The provider type to use for the result source"), ValueMap{"Exchange Search Provider","Local People Provider","Local SharePoint Provider","OpenSearch Provider","Remote People Provider","Remote SharePoint Provider"}, Values{"Exchange Search Provider","Local People Provider","Local SharePoint Provider","OpenSearch Provider","Remote People Provider","Remote SharePoint Provider"}] String ProviderType;
    [Write, Description("The URI to connect to the remote location")] String ConnectionUrl;
    [Write, Description("Present if the result source should exist, absent if it should not"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
