#!/usr/bin/env bash

function retryop()
{
  retry=0
  max_retries=10
  interval=30
  while [ ${retry} -lt ${max_retries} ]; do
    echo "Operation: $1, Retry #${retry}"
    eval $1
    if [ $? -eq 0 ]; then
      echo "Successfully."
      break
    else
      let retry=retry+1
      sleep $interval
    fi
  done
}

echo "Start to update package lists from repositories..."
retryop "apt-get update"

retryop "apt-get -y install python-pip jq"

set -e

custom_data_file="/var/lib/cloud/instance/user-data.txt"
settings=$(cat ${custom_data_file})
tenant_id=$1
client_id=$2
client_secret=$3

function get_setting() {
  key=$1
  local value=$(echo $settings | jq ".$key" -r)
  echo $value
}

environment=$(get_setting ENVIRONMENT)

set +e

echo "Start to install python packages..."
pkg_list="msrest msrestazure azure==2.0.0rc1 azure-storage netaddr"
if [ "$environment" = "AzureChinaCloud" ]; then
  for pkg in $pkg_list; do
    retryop "pip install $pkg --index-url https://pypi.mirrors.ustc.edu.cn/simple/ --default-timeout=60"
  done
else
  for pkg in $pkg_list; do
    retryop "pip install $pkg"
  done
fi

set -e

username=$(get_setting ADMIN_USER_NAME)
home_dir="/home/$username"

echo "Start to generate SSH key pair for BOSH..."
bosh_key="bosh"
ssh-keygen -t rsa -f $bosh_key -P "" -C ""
chmod 400 $bosh_key
cp $bosh_key $home_dir
cp "$bosh_key.pub" $home_dir

echo "Start to generate SSL certificate for cloud foundry..."
chmod +x create_cert.sh
cf_key="cloudfoundry.key"
cf_cert="cloudfoundry.cert"
./create_cert.sh $cf_key $cf_cert

echo "Start to run setup_env.py..."
bosh_director_ip=$(python setup_env.py ${tenant_id} ${client_id} ${client_secret} ${custom_data_file})

# For backward compatibility
sed -i "s/CLOUD_FOUNDRY_PUBLIC_IP/cf-ip/g" settings
cp settings $home_dir

echo "Start to specify params in bosh.yml..."
REPLACE_WITH_NATS_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
REPLACE_WITH_POSTGRES_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
REPLACE_WITH_REGISTRY_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
REPLACE_WITH_DIRECTOR_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
REPLACE_WITH_AGENT_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
REPLACE_WITH_ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
REPLACE_WITH_HM_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
REPLACE_WITH_MBUS_PASSWORD=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9')
sed -i "s/REPLACE_WITH_NATS_PASSWORD/$REPLACE_WITH_NATS_PASSWORD/g" bosh.yml
sed -i "s/REPLACE_WITH_POSTGRES_PASSWORD/$REPLACE_WITH_POSTGRES_PASSWORD/g" bosh.yml
sed -i "s/REPLACE_WITH_REGISTRY_PASSWORD/$REPLACE_WITH_REGISTRY_PASSWORD/g" bosh.yml
sed -i "s/REPLACE_WITH_DIRECTOR_PASSWORD/$REPLACE_WITH_DIRECTOR_PASSWORD/g" bosh.yml
sed -i "s/REPLACE_WITH_AGENT_PASSWORD/$REPLACE_WITH_AGENT_PASSWORD/g" bosh.yml
sed -i "s/REPLACE_WITH_ADMIN_PASSWORD/$REPLACE_WITH_ADMIN_PASSWORD/g" bosh.yml
sed -i "s/REPLACE_WITH_HM_PASSWORD/$REPLACE_WITH_HM_PASSWORD/g" bosh.yml
sed -i "s/REPLACE_WITH_MBUS_PASSWORD/$REPLACE_WITH_MBUS_PASSWORD/g" bosh.yml
cp bosh.yml $home_dir

sed -i "s/REPLACE_WITH_BOSH_DIRECOT_IP/$bosh_director_ip/g" deploy_bosh.sh
sed -i "s/REPLACE_WITH_ADMIN_PASSWORD/$REPLACE_WITH_ADMIN_PASSWORD/g" deploy_bosh.sh
chmod +x deploy_bosh.sh
cp deploy_bosh.sh $home_dir
echo $REPLACE_WITH_ADMIN_PASSWORD > "$home_dir/BOSH_DIRECTOR_ADMIN_PASSWORD"

chmod +x deploy_cloudfoundry.sh
cp deploy_cloudfoundry.sh $home_dir
example_manifests="$home_dir/example_manifests"
mkdir -p $example_manifests
cp single-vm-cf.yml $example_manifests 
cp multiple-vm-cf.yml $example_manifests

cp cf* $home_dir
bosh_init_url=$(get_setting BOSH_INIT_URL)
chmod +x init.sh
echo "Start to run init.sh..."
./init.sh $environment $bosh_init_url

chown -R $username $home_dir

auto_deploy_bosh=$(get_setting AUTO_DEPLOY_BOSH)
if [ "$auto_deploy_bosh" != "enabled" ]; then
  echo "Finish"
  exit 0
fi

echo "Start to run deploy_bosh.sh..."
su -c "./deploy_bosh.sh" - $username
echo "Finish"
