[ClassVersion("1.0.0.0"), FriendlyName("SPSessionStateService")]
class MSFT_SPSessionStateService : OMI_BaseResource
{
    [Key, Description("The name of the database for the service")] string DatabaseName;
    [Key, Description("The name of the database server for the database")] string DatabaseServer;
    [Write, Description("Present is the state service should be enabled, absent if it should be disabled"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("What is the timeout on sessions")] uint32 SessionTimeout;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

