---
####################################################################
#### gel.openldapsetup.yml                                      ####
####                                                            ####
####################################################################
#### DISCLAIMER                                                 ####
####################################################################
#### This Ansible Playbook is provided as-is, without warranty  ####
#### of any kind, either express or implied, including, but not ####
#### limited to, the implied warranties of merchantability,     ####
#### fitness for a particular purpose, or non-infringement.     ####
#### SAS Institute shall not be liable whatsoever for any       ####
#### damages arising out of the use of this documentation and   ####
#### code, including any direct, indirect, or consequential     ####
#### damages. SAS Institute reserves the right to alter or      ####
#### abandon use of this documentation and code at any time.    ####
#### In addition, SAS Institute will provide no support for the ####
#### materials contained herein.                                ####
####################################################################

# start the plays
- name: Perform common tasks on all machines
  hosts: openldapall
  become: yes
  become_user: root
  roles:
    - { role: gel.openldapcommon, tags: ["common"] }

- name: Install OpenLDAP Server on a single machine
  hosts: openldapserver
  become: yes
  become_user: root
  roles:
    - { role: gel.openldapserver, tags: ["server"] }

- name: Install KDC/LDAP Client on one or more machines
  hosts: openldapclients
  become: yes
  become_user: root
  roles:
    - { role: gel.openldapclients, tags: ["client"] }
