---
# tasks file for mountOptDisk

- name: Checking for existing mountpoint on {{ MOUNT_DIR }}
  command: >-
    mountpoint -q {{ MOUNT_DIR }}
  register: volume_stat
  failed_when: False
  changed_when: False

- block:
    - stat:
        path: /etc/foo.conf
      register: st

    - name: Creating temporary folder for moving opt denizens prior to mount
      tempfile:
        state: directory
      register: tempDirectoryForMountFiles
      changed_when: False
      when: "st.stat.exists"

    - name: move contents of mount folder to /tmp
      shell: >-
        mv {{ MOUNT_DIR }}/* "{{ tempDirectoryForMountFiles.path }}/"
      when: "st.stat.exists"

    - name: find the target disk
      set_fact:
        SOURCE_DISK: "/dev/{{ device.key }}"
      with_dict: "{{ ansible_devices }}"
      loop_control:
        loop_var: device
      when: "(device.value.partitions|length) == 0 and device.value.size == MOUNT_DISK and device.value.model == 'Virtual Disk'"

    - name: Ensure that the primary partition is present on the new disk
      parted:
        device: "{{ SOURCE_DISK }}"
        number: 1
        state: present
     
    - name: set primary partition device name
      set_fact:
        SOURCE_DISK_PARTITION: "{{ SOURCE_DISK }}1"
    
    - name: check for {{ SOURCE_DISK_PARTITION }} device
      stat:
        path: "{{ SOURCE_DISK_PARTITION }}"
      register: source_disk_stat
    
    - name: format new volume
      filesystem: fstype=xfs dev="{{ SOURCE_DISK_PARTITION }}"
      when: source_disk_stat.stat.exists == true

    - name: get the UUID of the new partition
      command: >-
        blkid {{ SOURCE_DISK_PARTITION }} -s UUID -o value
      register: volume_uuid
    
    - name: mount {{ MOUNT_DIR }}
      mount:
        name: "{{ MOUNT_DIR }}"
        fstype: xfs
        state: mounted
        src: "UUID={{ volume_uuid.stdout }}"
      when: source_disk_stat.stat.exists == true

    - name: return old files to the new mount
      shell: >-
        mv /{{ tempDirectoryForMountFiles.path }}/* "{{ MOUNT_DIR }}/"
      when: "st.stat.exists"

    - name: Cleanup working directory at {{ tempDirectoryForMountFiles.path }}
      file: path="{{ tempDirectoryForMountFiles.path }}" state=absent
      when: "st.stat.exists"

  when: volume_stat.rc != 0