[ClassVersion("1.0.0.0"), FriendlyName("xHostsFile")]
class MSFT_xHostsFile : OMI_BaseResource
{
    [Key, Description("The host name to check the local host file for")] string HostName;
    [Write, Description("The IP address that the host entry should be pointing to if the entry should exist")] string IPAddress;
    [Write, Description("Present if the host entry should exist, Absent if it should be removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure; 
};

