[ClassVersion("1.0.0.0"), FriendlyName("SPSearchTopology")]
class MSFT_SPSearchTopology : OMI_BaseResource
{
    [Key, Description("The name of the search service application for this topology")] String ServiceAppName;
    [Required, Description("A list of servers that will run the admin component")] String Admin[];
    [Required, Description("A list of servers that will run the crawler component")] String Crawler[];
    [Required, Description("A list of servers that will run the content processing component")] String ContentProcessing[];
    [Required, Description("A list of servers that will run the analytics processing component")] String AnalyticsProcessing[];
    [Required, Description("A list of servers that will run the query processing component")] String QueryProcessing[];
    [Required, Description("A list of servers that will host the first (0) index partition")] String IndexPartition[];
    [Required, Description("The local directory servers will use to store the first index partition")] String FirstPartitionDirectory;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
