[ClassVersion("1.0.0.0"), FriendlyName("SPSearchIndexPartition")]
class MSFT_SPSearchIndexPartition : OMI_BaseResource
{
    [Key, Description("The number of the partition in this farm")] Uint32 Index;
    [Required, Description("A list of the servers that this partition should exist on")] String Servers[];
    [Write, Description("The directory that the index should use locally on each server to store data")] String RootDirectory;
    [Key, Description("The name of the search service application")] String ServiceAppName;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
