[ClassVersion("1.0.0.0")]
Class MSFT_SPProxyLibraryEntry
{
    [Required, Description("Name of the account")] String AssemblyName;
    [Write, Description("Permission level of the account")] Boolean SupportAppAuthentication;
};
[ClassVersion("1.0.0"), FriendlyName("SPWebAppClientCallableSettings")]
class MSFT_SPWebAppClientCallableSettings : OMI_BaseResource
{
    [Key, Description("The URL of the web application to set blocked file types for")] string WebAppUrl;
    [write, Description("A list of proxy libraries to set. Those not in this list will be removed"), EmbeddedInstance("MSFT_SPProxyLibraryEntry")] string ProxyLibraries[];
    [write, Description("A list of proxy libraries to add. Proxy libraries not in this list will be kept"), EmbeddedInstance("MSFT_SPProxyLibraryEntry")] string ProxyLibrariesToInclude[];
    [write, Description("A list of proxy libraries to remove. Proxy libraries not in this list will be kept")] string ProxyLibrariesToExclude[];
    [write, Description("Sets the maximum number of internal SPRequest objects that can be included in one request")] UInt32 MaxResourcesPerRequest;
    [write, Description("Sets the maximum number of object paths that can be used within one request")] UInt32 MaxObjectPaths;
    [write, Description("Sets the execution timeout for the client request in minutes")] UInt32 ExecutionTimeout;
    [write, Description("Sets the maximum depth of the request XML that is sent by the client measured in 'tag' count")] UInt32 RequestXmlMaxDepth;
    [write, Description("Sets a Boolean value that specifies whether to enable XSD validation against an XML request or not")] Boolean EnableXsdValidation;
    [write, Description("Sets a Boolean value that specifies whether the server can send stack trace data to the client")] Boolean EnableStackTrace;
    [write, Description("Sets the threshold in milliseconds for logging csom request usage data ")] UInt32 RequestUsageExecutionTimeThreshold;
    [write, Description("Sets a Boolean value that specifies whether to log usage data or not")] Boolean EnableRequestUsage;
    [write, Description("Sets a Boolean value that specifies whether to log usage data when request has an exception or not")] Boolean LogActionsIfHasRequestException;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] string InstallAccount;
};
