[ClassVersion("1.0.0.0"), FriendlyName("xWebConfigKeyValue")]
class MSFT_xWebConfigKeyValue : OMI_BaseResource
{
    [Key, Description("Path to website location(IIS or WebAdministration format)")] String WebsitePath;
    [Key, Description("Config Section to be update"), ValueMap{"AppSettings"}, Values{"AppSettings"}] String ConfigSection;
    [Key, Description("Key for AppSettings")] String Key;    
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Value for AppSettings")] String Value;
    [Write, Description("If the given key value pair is for attribute, default is element")] Boolean IsAttribute;
};
