#
# Copyright (c) 2019, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
- name: download all the things
  hosts: [localhost]
  vars:
    DEPOT_DIRECTORY: /sasshare/depot
    DEPOT_DOWNLOAD_LOCATION: ""
    LICENSE_LOCATION: /sasshare/depot/sid_files/
    LICENSE_DOWNLOAD_LOCATION: ""
    PLANFILE_LOCATION: /sasshare/depot/plan.xml
    PLANFILE_DOWNLOAD_LOCATION: ""
  tasks:
  ############################################# Download the Depot folder ################################################
    - name: install azcopy prerequisites
      become: yes
      yum:
          name: "{{ item }}"
          state: "latest"
      with_items:
      - libunwind
      - libicu
      - rsync

    - name: create install folder
      file:
          state: directory
          path: /tmp/azcopy_install

    - name: downloading azcopy from microsoft
      become: yes
      unarchive:
          group: "{{ PRIMARY_USER }}"
          owner: "{{ PRIMARY_USER }}"
          remote_src: yes
          src: "https://aka.ms/downloadazcopy-v10-linux"
          dest: "/tmp/azcopy_install"
      register: task_result
      until: task_result is success
      retries: 10
      delay: 5

    - name: normalize the azure copy folder name
      become: yes
      shell: "mv /tmp/azcopy_install/azcopy_linux* /tmp/azcopy_install/azcopy_linux"

    - name: use azcopy to download mirror
      become: yes
      shell: >-
          timeout -k 7140 7000 /tmp/azcopy_install/azcopy_linux/azcopy copy "{{ DEPOT_DOWNLOAD_LOCATION }}" "{{ DEPOT_DIRECTORY }}" --recursive
      async: 7200
      failed_when: false
      register: copy_ret1

    - name: use azcopy to download mirror retry 1
      become: yes
      shell: |-
          timeout -k 7140 7000 /tmp/azcopy_install/azcopy_linux/azcopy copy "{{ DEPOT_DOWNLOAD_LOCATION }}" "{{ DEPOT_DIRECTORY }}" --recursive
      async: 7200
      failed_when: false
      register: copy_ret2
      when: "copy_ret1.rc != 0"

    - name: use azcopy to download mirror retry 2
      become: yes
      shell: |-
          timeout -k 7140 7000 /tmp/azcopy_install/azcopy_linux/azcopy copy "{{ DEPOT_DOWNLOAD_LOCATION }}" "{{ DEPOT_DIRECTORY }}" --recursive
      async: 7200
      failed_when: false
      register: copy_ret3
      when: "copy_ret1.rc != 0 and copy_ret2.rc != 0"

    - name: use azcopy to download mirror retry 3
      become: yes
      shell: |-
          timeout -k 7140 7000 /tmp/azcopy_install/azcopy_linux/azcopy copy "{{ DEPOT_DOWNLOAD_LOCATION }}" "{{ DEPOT_DIRECTORY }}" --recursive
      async: 7200
      failed_when: false
      register: copy_ret4
      when: "copy_ret1.rc != 0 and copy_ret2.rc != 0 and copy_ret3.rc != 0"

    - name: use azcopy to download mirror retry 4
      become: yes
      shell: |-
          timeout -k 7140 7000 /tmp/azcopy_install/azcopy_linux/azcopy copy "{{ DEPOT_DOWNLOAD_LOCATION }}" "{{ DEPOT_DIRECTORY }}" --recursive
      async: 7200
      register: copy_ret5
      when: "copy_ret1.rc != 0 and copy_ret2.rc != 0 and copy_ret3.rc != 0 and copy_ret4.rc != 0"

    - name: use azcopy to download plan file, if PLANFILE_DOWNLOAD_LOCATION is not blank
      become: yes
      shell: |-
          timeout -k 7140 7000 /tmp/azcopy_install/azcopy_linux/azcopy copy "{{ PLANFILE_DOWNLOAD_LOCATION }}" "{{ PLANFILE_LOCATION }}" --recursive
      when: PLANFILE_DOWNLOAD_LOCATION != ""

- name: Make sure necessary files are executable
  hosts: [localhost]
  become_user: root
  become: yes
  tasks:
  - name: Make depot executable
    file:
      path: "/sasshare/depot"
      state: directory
      recurse: yes
      mode: '0755'
