---
- name: Install the loadbalancer certificate on all SAS installations
  hosts: [metadata_servers, midtier_servers, va_controllers]
  become_user: sasinst
  become: yes
  gather_facts: false
  vars_files:
    - /tmp/ansible_vars.yaml

  tasks:
    - name: install loadbalancer certificate
      become: yes
      shell: |-
        {{ sasFolder }}/SASHome/SASDeploymentManager/9.4/sasdm.sh -quiet -responsefile "/sasshare/responsefiles/cert.txt"
