---
- name: install sas on metadata servers
  hosts: [metadata_servers,va_controllers,midtier_servers]
  become: yes
  gather_facts: false
  tasks:
     - name: Run metadata server and vacontroller install response file(s)
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_install.txt

- name: Run setuid
  hosts: [metadata_servers]
  become: yes
  gather_facts: false
  vars_files:
    - /tmp/ansible_vars.yaml
  tasks:
     - name: Run setuid.sh on the metadata nodes
       become: yes
       shell: >-
         {{ sasFolder }}/SASHome/SASFoundation/9.4/utilities/bin/setuid.sh

- name: configure sas on metadata head
  hosts: [metadata_head]
  become: yes
  gather_facts: false
  tasks:
     - name: Run metadata head config response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt
     - name: Pause for 5 minutes between metadata server configurations
       pause:
         minutes: 5

- name: configure sas on metadata nodes
  hosts: [metadata_nodes]
  serial: 1
  become: yes
  gather_facts: false
  tasks:
     - name: Run metadata node config response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt
     - name: Pause for 5 minutes between metadata server configurations
       pause:
         minutes: 5

- name: configure sas on visual analytics controller
  hosts: [va_controllers]
  become: yes
  gather_facts: false
  tasks:
     - name: Run va install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt

- name: configure sas on midtier head
  hosts: [midtier_head]
  become: yes
  gather_facts: false
  tasks:
     - name: create vfabric folders
       file:
         path: /etc/opt/vmware/vfabric
         state: directory

     - name: Change ownership of vmware folder
       file:
         path: /etc/opt/vmware
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Change ownership of vfabric folder
       file:
         path: /etc/opt/vmware/vfabric
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Run midtier install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt

- name: install sas on midtier node(s)
  hosts: [midtier_nodes]
  become: yes
  gather_facts: false
  tasks:
     - name: create vfabric folders
       file:
         path: /etc/opt/vmware/vfabric
         state: directory

     - name: Change ownership of vmware folder
       file:
         path: /etc/opt/vmware
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Change ownership of vfabric folder
       file:
         path: /etc/opt/vmware/vfabric
         owner: sasinst
         group: sas
         mode: '0755'

     - name: Run midtier node install response file
       become: yes
       shell: >-
         /sasshare/scripts/run_install_as_user.sh sasinst /sasshare/responsefiles/{{ inventory_hostname }}_config.txt
