- name: "Run sas scripts to update external connection urls in metadata"
  hosts: [metadata_head]
  become: yes
  vars_files:
    - /tmp/ansible_vars.yaml

  vars:
    sas_exec_dir: "{{ sasFolder }}/SASHome/SASFoundation/9.4"

  tasks:
    - name: "Execute setWebURLs.sas script to update external connection metadata"
      command: "{{ sas_exec_dir }}/sas -stdio /sasshare/sasfiles/{{ item }}.sas"
      register: sas_script_output
      with_items:
        - setSASWebUrls
        - setFoundationServices
        - setContentServerConnection
        - setUrlOverride
        - setCDPSKnownHosts

    - debug:
        var: sas_script_output
