---
- name: Copy response files to sasshare
  hosts: [localhost]
  become_user: root
  become: yes
  gather_facts: false
  vars_files:
    - /sas/install/ansible/vars.yaml
    - /tmp/ansible_vars.yaml
  tasks:
     - name: replace variables in response files
       template:
         src: "/sas/install/responsefiles/{{ item }}.j2"
         dest: "/tmp/responsefiles/{{ item }}"
         owner: sasinst
         group: sas
       with_items:
         - mpp_metadata.txt
         - mpp_metadata_node.txt
         - mpp_midtier.txt
         - mpp_midtier_node.txt
         - mpp_va.txt
         - cert.txt
