---
- name: Update WIP Data Server for loadbalancer
  hosts: [va_controllers]
  become_user: sasinst
  become: yes
  gather_facts: false
  vars_files:
    - /tmp/ansible_vars.yaml

  tasks:
    - name: run psql to update database
      become: yes
      shell: |-
        export POSTGRES_HOME={{ sasFolder }}/SASHome/SASWebInfrastructurePlatformDataServer/9.4
        export PATH=${POSTGRES_HOME}/bin:$PATH
        export LD_LIBRARY_PATH=${POSTGRES_HOME}/lib:$LD_LIBRARY_PATH
        export PGPASSWORD="{{ DBPassword | b64decode }}"
        psql -h localhost -p 9432 -U SharedServices -c "UPDATE public.sas_theme SET protocol_cd='https' WHERE theme_nm='SASTheme_default';"
        psql -h localhost -p 9432 -U SharedServices -c "UPDATE public.sas_theme SET hostname_txt='{{ LoadbalancerDNS }}' WHERE theme_nm='SASTheme_default';"
        psql -h localhost -p 9432 -U SharedServices -c "UPDATE public.sas_theme SET port_no='443' WHERE theme_nm='SASTheme_default';"
        psql -h localhost -p 9432 -U SharedServices -c "UPDATE public.sas_theme SET internal_protocol_cd='http' WHERE theme_nm='SASTheme_default';"
        psql -h localhost -p 9432 -U SharedServices -c "UPDATE public.sas_theme SET Internal_hostname_txt='midtier-0.internal.cloudapp.net' WHERE theme_nm='SASTheme_default';"
        psql -h localhost -p 9432 -U SharedServices -c "UPDATE public.sas_theme SET internal_port_no='7980' WHERE theme_nm='SASTheme_default';"
        psql -h localhost -p 9432 -U SharedServices -c "UPDATE public.sas_theme SET internal_context_txt='/SASTheme_default' WHERE theme_nm='SASTheme_default';"
