---
- name: Copy response files to sasshare
  hosts: [localhost]
  become_user: root
  become: yes
  gather_facts: false
  vars_files:
    - /sas/install/ansible/vars.yaml
    - /tmp/ansible_vars.yaml
  tasks:
     - name: replace variables in standard response files
       template:
         src: "/sas/install/responsefiles/{{ item }}.j2"
         dest: "/tmp/responsefiles/{{ item }}"
         owner: sasinst
         group: sas
       with_items:
         - cert.txt

     - name: replace variables in midtier install response files
       vars:
          NodeName: "{{ item }}"
       template:
          src: "/sas/install/responsefiles/mpp_midtier_install.txt.j2"
          dest: "/tmp/responsefiles/{{ item }}_install.txt"
          owner: sasinst
          group: sas
       loop: "{{ groups['midtier_head']}}"

     - name: replace variables in midtier config response files
       vars:
          NodeName: "{{ item }}"
       template:
          src: "/sas/install/responsefiles/mpp_midtier_config.txt.j2"
          dest: "/tmp/responsefiles/{{ item }}_config.txt"
          owner: sasinst
          group: sas
       loop: "{{ groups['midtier_head']}}"

     - name: replace variables in midtier node install response files
       vars:
          NodeName: "{{ item }}"
       template:
          src: "/sas/install/responsefiles/mpp_midtier_node_install.txt.j2"
          dest: "/tmp/responsefiles/{{ item }}_install.txt"
          owner: sasinst
          group: sas
       loop: "{{ groups['midtier_nodes']}}"

     - name: replace variables in midtier node config response files
       vars:
          NodeName: "{{ item }}"
       template:
          src: "/sas/install/responsefiles/mpp_midtier_node_config.txt.j2"
          dest: "/tmp/responsefiles/{{ item }}_config.txt"
          owner: sasinst
          group: sas
       loop: "{{ groups['midtier_nodes']}}"

     - name: replace variables in metadata head response file
       vars:
         NodeName: "{{ item }}"
       template:
         src: "/sas/install/responsefiles/mpp_metadata.txt.j2"
         dest: "/tmp/responsefiles/{{ item }}.txt"
         owner: sasinst
         group: sas
       loop: "{{ groups['metadata_head']}}"

     - name: replace variables in metadata node response files
       vars:
         NodeName: "{{ item }}"
       template:
         src: "/sas/install/responsefiles/mpp_metadata_node.txt.j2"
         dest: "/tmp/responsefiles/{{ item }}.txt"
         owner: sasinst
         group: sas
       loop: "{{ groups['metadata_nodes']}}"

     - name: replace variables in vacontroller install response files
       vars:
         NodeName: "{{ item }}"
       template:
         src: "/sas/install/responsefiles/mpp_va_install.txt.j2"
         dest: "/tmp/responsefiles/{{ item }}_install.txt"
         owner: sasinst
         group: sas
       loop: "{{ groups['va_controllers']}}"

     - name: replace variables in vacontroller config response files
       vars:
         NodeName: "{{ item }}"
       template:
         src: "/sas/install/responsefiles/mpp_va_config.txt.j2"
         dest: "/tmp/responsefiles/{{ item }}_config.txt"
         owner: sasinst
         group: sas
       loop: "{{ groups['va_controllers']}}"

