---
- name: Copy response files to sasshare
  hosts: [localhost]
  become_user: root
  become: yes
  gather_facts: false
  vars_files:
    - /sas/install/ansible/vars.yaml
    - /tmp/ansible_vars.yaml
  tasks:
     - name: replace variables in standard response files
       template:
         src: "/sas/install/responsefiles/{{ item }}.j2"
         dest: "/tmp/responsefiles/{{ item }}"
         owner: sasinst
         group: sas
       with_items:
         - mpp_metadata.txt
         - mpp_midtier.txt
         - mpp_va.txt
         - cert.txt

     - name: replace variables in midtier node response files
       vars:
          NodeName: "{{ item }}"
       template:
          src: "/sas/install/responsefiles/mpp_midtier_node.txt.j2"
          dest: "/tmp/responsefiles/{{ item }}.txt"
          owner: sasinst
          group: sas
       loop: "{{ groups['midtier_nodes']}}"

     - name: replace variables in metadata node response files
       vars:
         NodeName: "{{ item }}"
       template:
         src: "/sas/install/responsefiles/mpp_metadata_node.txt.j2"
         dest: "/tmp/responsefiles/{{ item }}.txt"
         owner: sasinst
         group: sas
       loop: "{{ groups['metadata_nodes']}}"
