#
# Copyright (c) 2019, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Wait for SAS VMs to be ready
  hosts: [sas_servers]
  become_user: root
  become: yes
  gather_facts: false
  tasks:
    - name: wait up to 30 min for all servers to be alive.
      wait_for_connection:
        connect_timeout: 5
        delay: 0
        sleep: 5
        timeout: 1800
