---

- name: Install openldap server packages
  yum: 
    pkg: "{{ item }} "
    state: present
  with_items:
     - openldap-clients
     - openldap


- name: ensure {{CACERTLOC}} folder exists
  file:
    path: "{{CACERTLOC}}"
    state: directory
    mode: 0755


- name: push the keys to the openldap clients
  copy: 
    src: "{{tmp_folder_controller}}/{{CERTNAME}}.pem"
    dest: "{{CACERTLOC}}/{{CERTNAME}}.pem"
  register: pushit
- debug: var=pushit

- name: sometimes I have to do this for the ldap.conf to exist. 
  shell: yum reinstall -y openldap

- name: edit ldap.conf
  lineinfile: 
    dest: /etc/openldap/ldap.conf
    regexp: "^TLS_CACERT.*"
    line: "TLS_CACERT {{CACERTLOC}}/{{CERTNAME}}.pem"
    state: present
    backup: yes

- name: check if it works with ldapsearch
  no_log: true
  shell: "ldapsearch -H ldaps://{{CERT_LDAP}}:636 -b \"{{OLCSUFFIX}}\" -x -D \"{{OLCROOTDN}}\" -w '{{OLCROOTPW | b64decode }}' "
  register: ldapsearch
  failed_when: "'Success' not in ldapsearch.stdout"
- debug: var=ldapsearch.stdout_lines



