---

- name: ensure folder exists
  file:
    path: "{{SSSD_BACKUP_FOL}}"
    state: directory
    mode: 0700

- name: Backup the authconfig
  shell: "authconfig --savebackup={{SSSD_BACKUP_FILE}}"
  register: authconfig
- debug: var=authconfig


- name: Ensure SSSD is installed and at the latest version
  yum: 
    pkg: "{{ item }}"
    state: latest
  with_items:
     - sssd

- name: Enable LDAP and SSSD
  shell: authconfig --enableldap --enableldapauth --ldapserver="{{CERT_LDAP}}" --ldapbasedn="{{OLCSUFFIX}}" --enablesssd --enablesssdauth --enablemkhome --update
  register: enablesssd
- debug: var=enablesssd


- name: create sssd.conf
  template:
    src: sssd.conf.j2
    dest: "/etc/sssd/sssd.conf"
    mode: 0600   
    backup: yes

- name: Restart SSSD service
  service: 
    name: sssd
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: check the users
  shell: "id {{item.name}} ; getent passwd {{item.name}}"
  with_items: "{{user_list}}"
  register: user_check
- debug: var=user_check

- name: log in once to create home directories
  shell: "su - {{item.name}} "
  with_items:
    - "{{user_list}}"
    - { name: sasadmin }
  register: user_login
- debug: var=user_login

