[ClassVersion("1.0.0.0"), FriendlyName("SPTimerJobState")]
class MSFT_SPTimerJobState : OMI_BaseResource
{
    [Key, Description("The type name of the timer job (not the display name)")] String TypeName;
    [Key, Description("The URL of the web application that the timer job belongs to. Use the value 'N/A' if no web application is applicable")] String WebAppUrl;
    [Write, Description("Should the timer job be enabled or not")] Boolean Enabled;
    [Write, Description("The schedule for the timer job to execute on")] String Schedule;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

