trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  # The variables are referenced from build_images.ps1 script
  SUBSCRIPTION_ID: $[ variables['PipelineVars_SubscriptionId'] ]
  RESOURCE_GROUP: $[ variables['PipelineVars_ResourceGroup'] ]
  BUILDER_IDENTITY: $[ variables['PipelineVars_BuilderIdentity'] ]
  IMAGE_IDENTITY: $[ variables['PipelineVars_ImageIdentity'] ]
  GALLERY_NAME: $[ variables['PipelineVars_GalleryName'] ]
  RESOURCES_LOCATION: $[ variables['PipelineVars_Location'] ]
  VM_SKU: $[ variables['PipelineVars_VmSku'] ]
  ARTIFACTS_SOURCE_OBJ: $[ variables['PipelineVars_ArtifactSourceObj'] ]
  DEPLOYMENT_NAME: $(Build.BuildId)_$(System.JobId)
  PIPELINE_TIMEOUT_IN_MINUTES: 180

  ThisFileRelativeDir: $[ coalesce(variables['PipelineVars_ThisFileRelativeDir'], 'quickstarts/microsoft.devcenter/devbox-ready-to-code-image') ]

jobs:
- job: Build_DevBox_Image
  timeoutInMinutes: $[ variables['PIPELINE_TIMEOUT_IN_MINUTES'] ]

  steps:
  - checkout: self
  - task: AzureCLI@2
    displayName: Build
    inputs:
      azureSubscription: DevBoxReadyToCodeSampleConnection
      scriptType: pscore
      scriptPath: ./$(ThisFileRelativeDir)/build_images.ps1
      useGlobalConfig: false
