
[ClassVersion("1.0"), FriendlyName("xSQLDatabaseRecoveryModel")]
class MSFT_xSQLDatabaseRecoveryModel : OMI_BaseResource
{
    [Key, Description("The SQL database name")] String DatabaseName;
    [Required, Description("The SQL server and instance.")] String SqlServerInstance;
    [Required, Description("Recovery Model"), ValueMap{"Full","Simple","BulkLogged"}, Values{"Full","Simple","BulkLogged"}]  String RecoveryModel;
};
