[ClassVersion("1.0.0"), FriendlyName("xIisFeatureDelegation")] 
class MSFT_xIisFeatureDelegation : OMI_BaseResource
{
  [Key] string SectionName;
  [Key,ValueMap{"Allow", "Deny"},Values{"Allow", "Deny"}] string OverrideMode;
};
