[ClassVersion("1.0.0.0"), FriendlyName("SPUserProfileServiceAppPermissions")]
class MSFT_SPUserProfileServiceAppPermissions : OMI_BaseResource
{
    [Key, Description("The name of the proxy that is attached to the user profile service you wish to set permissions for")] string ProxyName;
    [Write, Description("A list of user principals that will have the Create personal site permission")] string CreatePersonalSite[];
    [Write, Description("A list of user principals that will have the Follow users and edit profile permission")] string FollowAndEditProfile[];
    [Write, Description("A list of user principals that will have the Use tags and notes permission")] string UseTagsAndNotes[];
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
