---
name: bosh

releases:
- name: bosh
  url: REPLACE_WITH_BOSH_RELEASE_URL
  sha1: REPLACE_WITH_BOSH_RELEASE_SHA1
- name: bosh-azure-cpi
  url: REPLACE_WITH_BOSH_AZURE_CPI_RELEASE_URL
  sha1: REPLACE_WITH_BOSH_AZURE_CPI_RELEASE_SHA1

networks:
- name: public
  type: vip

- name: private
  type: manual
  subnets: # You need to update the subnet configuration if you change to another subnet
  - range: REPLACE_WITH_SUBNET_ADDRESS_RANGE_FOR_BOSH
    gateway: REPLACE_WITH_GATEWAY_IP
    dns: [168.63.129.16]
    cloud_properties:
      virtual_network_name: REPLACE_WITH_VNET_NAME # Replace with virtual network name
      subnet_name: REPLACE_WITH_SUBNET_NAME_FOR_BOSH # Replace with subnet name for BOSH VM

resource_pools:
- name: vms
  network: private
  stemcell:
    url: REPLACE_WITH_STEMCELL_URL
    sha1: REPLACE_WITH_STEMCELL_SHA1
  cloud_properties:
    instance_type: Standard_DS2

disk_pools:
- name: disks
  disk_size: 25_000

jobs:
- name: bosh
  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: cpi, release: bosh-azure-cpi}

  instances: 1
  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - {name: private, static_ips: [REPLACE_WITH_BOSH_DIRECTOR_IP], default: [dns, gateway]}
#  - {name: public, static_ips: [REPLACE_WITH_BOSH_PUBLIC_IP]}

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: REPLACE_WITH_BOSH_DIRECTOR_IP
      host: REPLACE_WITH_BOSH_DIRECTOR_IP
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: REPLACE_WITH_BOSH_DIRECTOR_IP
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: bosh
      db: *db
      cpi_job: cpi
      enable_snapshots: true
      debug:
        keep_unreachable_vms: REPLACE_WITH_KEEP_UNREACHABLE_VMS
      max_threads: 10
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm-user, password: hm-password}

    hm:
      director_account: {user: hm-user, password: hm-password}
      resurrector_enabled: true

    azure: &azure
      environment: REPLACE_WITH_ENVIRONMENT
      subscription_id: REPLACE_WITH_SUBSCRIPTION_ID
      storage_account_name: REPLACE_WITH_DEFAULT_STORAGE_ACCOUNT_NAME
      resource_group_name: REPLACE_WITH_RESOURCE_GROUP_NAME
      tenant_id: REPLACE_WITH_TENANT_ID
      client_id: REPLACE_WITH_CLIENT_ID
      client_secret: REPLACE_WITH_CLIENT_SECRET
      ssh_user: vcap
      ssh_public_key: REPLACE_WITH_SSH_PUBLIC_KEY
      default_security_group: REPLACE_WITH_NSG_NAME_FOR_BOSH

    agent: {mbus: "nats://nats:nats-password@REPLACE_WITH_BOSH_DIRECTOR_IP:4222"}

    ntp: &ntp [0.north-america.pool.ntp.org]

cloud_provider:
  template: {name: cpi, release: bosh-azure-cpi}

  ssh_tunnel:
#    host: REPLACE_WITH_BOSH_PUBLIC_IP
    host: REPLACE_WITH_BOSH_DIRECTOR_IP
    port: 22
    user: vcap # The user must be as same as above ssh_user
    private_key: ~/bosh

#  mbus: https://mbus-user:mbus-password@REPLACE_WITH_BOSH_PUBLIC_IP:6868
  mbus: https://mbus-user:mbus-password@REPLACE_WITH_BOSH_DIRECTOR_IP:6868

  properties:
    azure: *azure
    agent: {mbus: "https://mbus-user:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
