[ClassVersion("1.0.0.0"), FriendlyName("SPAntivirusSettings")]
class MSFT_SPAntivirusSettings : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Should documents be scanned before being downloaded")] Boolean ScanOnDownload;
    [Write, Description("Should documents be scanned on upload")] Boolean ScanOnUpload;
    [Write, Description("Should documents that are infected be allowed to be downloaded")] Boolean AllowDownloadInfected;
    [Write, Description("Should infected documents be handed to the AV engine to attempt cleaning")] Boolean AttemptToClean;
    [Write, Description("What is the timeout for an AV scan in seconds")] Uint16 TimeoutDuration;
    [Write, Description("How many concurrent threads should the AV engine be able to run on a server")] Uint16 NumberOfThreads;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};

