---
# defaults file for getLocalVIRK

VIRK_CLONE_DIRECTORY: "/exports/bastion/setup/virk"
VIRK_ORIGIN_CONNECTOR: "https://github.com/sassoftware/virk.git"
VIRK_PLAYBOOK: ""
ORCHESTRATION_DIRECTORY: "/exports/bastion/setup/orchestration"
SSL_WORKING_FOLDER: "/exports/bastion/setup/ssl"
LOCAL_DIRECTORY_MIRROR: ""
REMOTE_DIRECTORY_MIRROR: ""
MIRROR_HTTP: ""
LICENSE_FILE: ""
#SSL_CA_CERT_FILENAME: "sas_certificate_ca.crt"
#SSL_CA_KEY_FILENAME: "sas_certificate_ca.key"
#SSL_CHILD_CERT_FILENAME: "localhost.crt"
#SSL_CHILD_KEY_FILENAME: "localhost.key"
#SSL_CLIENT_CERT_TARGET_FOLDER: "/etc/pki/tls/certs"
#SSL_CLIENT_KEY_TARGET_FOLDER: "/etc/pki/tls/private"
SAS:
  "3.3":
    VIRK_COMMIT: "e210c8d"
    ORCHESTRATION_URL: "https://support.sas.com/installation/viya/sas-orchestration-cli/lax/sas-orchestration.tgz"
    MIRROR_MANAGER_URL: ""
    ORCHESTRATION_MIRROR_MANAGER: ""
    USE_MIRROR: False
    
    
  "3.4":
    VIRK_COMMIT: "fec76e556"
    ORCHESTRATION_URL: "https://support.sas.com/installation/viya/34/sas-orchestration-cli/lax/sas-orchestration-linux.tgz"
    MIRROR_MANAGER_URL: "https://support.sas.com/installation/viya/34/sas-mirror-manager/lax/mirrormgr-linux.tgz"
    ORCHESTRATION_MIRROR_MANAGER: "{{ ORCHESTRATION_DIRECTORY }}/mirrormgr"
    USE_MIRROR: True

