---
- block:

  # Host definitions
  - name: remove default deployTarget
    lineinfile:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='ansible_host'
      state=absent

# we will assume the host definitions are those that
  - name: "insert host definitions (by chopping them out of our current inventory)"
    blockinfile:
      insertafter='\[host-definitions\]'
      dest="{{ ORCHESTRATION_INVENTORY }}"
      block="{{ lookup('file', inventory_file).split("[")[0] }}"
      marker="# {mark} ADD HOST DEFINITIONS"

  # Programming Services
  - name: Programming - ComputeServer
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[ComputeServer\]\ndeployTarget'
      replace="[ComputeServer]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}"

  - name: Programming - programming
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[programming\]\ndeployTarget'
      replace='[programming]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - spre
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[spre\]\ndeployTarget'
      replace='[spre]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - CommandLine
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[CommandLine\]\ndeployTarget'
      replace='[CommandLine]\n{{ groups["sas-servers"]|unique|join("\n") }}'

  - name: Programming - connect
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[connect\]\ndeployTarget'
      replace='[connect]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - pcfile
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[pcfile\]\ndeployTarget'
      replace='[pcfile]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - platform
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[platform\]\ndeployTarget'
      replace='[platform]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - Operations
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[Operations\]\ndeployTarget'
      replace='[Operations]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - psqllib
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[psqllib\]\ndeployTarget'
      replace='[psqllib]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - psqllib1
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[psqllib1\]\ndeployTarget'
      replace='[psqllib1]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - psqlodbc
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[psqlodbc\]\ndeployTarget'
      replace='[psqlodbc]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Programming - psqlodbc1
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[psqlodbc1\]\ndeployTarget'
      replace='[psqlodbc1]\n{{ groups[PROGRAMMING_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'


  # Stateful Services
  - name: Stateful - configuratn
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[configuratn]\\ndeployTarget'
      replace='[configuratn]\n{{ groups[STATEFUL_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Stateful -pgpoolc
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[pgpoolc\]\ndeployTarget'
      replace='[pgpoolc]\n{{ groups[STATEFUL_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Stateful -rabbitmq
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[rabbitmq\]\ndeployTarget'
      replace='[rabbitmq]\n{{ groups[STATEFUL_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'

  - name: Stateful -sasdatasvrc
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[sasdatasvrc\]\ndeployTarget'
      replace='[sasdatasvrc]\n{{ groups[ALL_SERVICES_GROUP]|unique|join("\n") }}'

  # multiple
  - name: Multiple - CoreServices
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[CoreServices\]\ndeployTarget'
      replace='[CoreServices]\n{{ groups[ALL_SERVICES_GROUP]|unique|join("\n") }}'

  - name: Multiple - Consul
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[Consul\]\ndeployTarget'
      replace='[Consul]\n{{ groups[ALL_SERVICES_GROUP]|unique|join("\n") }}'


  - name: Multiple - httpproxy
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[httpproxy\]\ndeployTarget'
      replace='[httpproxy]\n{{ groups[ALL_SERVICES_GROUP]|unique|join("\n") }}'

  # CAS
  - name: Set CAS controller target
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^\[sas-casserver-primary\]\ndeployTarget'
      replace='[sas-casserver-primary]\n{{ groups[CAS_CONTROLLER_SERVERS_GROUP][0] }}'

  - name: Set CAS workers
    blockinfile:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      insertafter='^\[sas-casserver-worker\]'
      block="{{ groups[CAS_CONTROLLER_SERVERS_GROUP][2:]|join("\n") }}"
      marker="# {mark} ADD WORKERS"
    when: "(groups[CAS_CONTROLLER_SERVERS_GROUP]|length) > 2"


  # Everything else
  - name: All other services
    replace:
      dest="{{ ORCHESTRATION_INVENTORY }}"
      regexp='^deployTarget'
      replace='{{ groups[VISUAL_SERVICES_SERVERS_GROUP]|unique|join("\n") }}'
      backup=yes
  run_once: true
  delegate_to: localhost