---
- type: replace
  path: /releases/name=bosh-azure-cpi/url
  value: ((cpi_release_url))

- type: replace
  path: /releases/name=bosh-azure-cpi/sha1
  value: ((cpi_release_sha1))

- type: replace
  path: /resource_pools/name=vms/cloud_properties?
  value:
    instance_type: ((director_vm_instance_type))
