- type: replace
  path: /releases/name=os-conf?
  value:
    name: os-conf
    version: 18
    url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=18
    sha1: 78d79f08ff5001cc2a24f572837c7a9c59a0e796

- type: replace
  path: /instance_groups/name=bosh/properties/director/default_ssh_options?/gateway_user
  value: jumpbox

- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value:
    name: user_add
    release: os-conf
    properties:
      users:
      - name: jumpbox
        public_key: ((jumpbox_ssh.public_key))

- type: replace
  path: /variables/-
  value:
    name: jumpbox_ssh
    type: ssh
