---
- type: replace
  path: /instance_groups/name=bosh/properties/azure/use_managed_disks?
  value: true

- type: remove
  path: /instance_groups/name=bosh/properties/azure/storage_account_name

- type: replace
  path: /cloud_provider/properties/azure/use_managed_disks?
  value: true

- type: remove
  path: /cloud_provider/properties/azure/storage_account_name
