---
- path: /releases/name=concourse/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/concourse/concourse-release-3.12.0.tgz
- path: /releases/name=garden-runc/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/concourse/garden-runc-release-1.13.1.tgz
- path: /releases/name=postgres/url
  type: replace
  value: https://cloudfoundry.blob.core.chinacloudapi.cn/concourse/postgres-release-28.tgz
