[ClassVersion("1.0.0.0"), FriendlyName("SPServiceInstance")]
class MSFT_SPServiceInstance : OMI_BaseResource
{
    [Key, Description("The name of the service instance to manage")] string Name;
    [Write, Description("Present to ensure it runs on this server, or absent to ensure it is stopped"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
