#pragma namespace("\\\\.\\root\\microsoft\\windows\\DesiredStateConfiguration")

[ClassVersion("1.0.0"), FriendlyName("xSqlExtendVirtualDataDisk")] 
class MicrosoftAzure_xSqlExtendVirtualDataDisk : OMI_BaseResource
{
    [key, Description("The number of disks.")]
    Uint32 NumberOfDisks;

    [required, Description("The starting device id of disks.")]
    Uint32 StartingDeviceID;
	
    [required, Description("The letter of new disk.")]
    string DiskLetter;

    [required, Description("The target virtual disk name.")]
    string VirtualDiskName;

    [required, Description("The target storage pool name.")]
    string StoragePoolName;

    [write, Description("The disk size in byte.")]
    Uint64 DiskSizeInByte;
};
