
[ClassVersion("1.0.0.0"), FriendlyName("xSQLAOGroupJoin")]
class MSFT_xSQLAOGroupJoin : OMI_BaseResource
{
    [Key, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key] String AvailabilityGroupName;
    [Write] String SQLServer;
    [Write] String SQLInstanceName;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to Grant Permissions in SQL.")] String SetupCredential;
};

