
[ClassVersion("1.0.0"),FriendlyName("xScript")] 
class MSFT_xScriptResource : OMI_BaseResource
{
  [Key, Description("A string that can be used to create a PowerShell script block that retrieves the current state of the resource.")] String GetScript;
  [Key, Description("A string that can be used to create a PowerShell script block that sets the resource to the desired state.")] String SetScript;
  [Key, Description("A string that can be used to create a PowerShell script block that validates whether or not the resource is in the desired state.")] String TestScript;
  [Write, EmbeddedInstance("MSFT_Credential"), Description("The credential of the user account to run the script under if needed.")] String Credential;
  [Read, Description("The result from the GetScript script block.")] String Result;
};
