[ClassVersion("1.0.0.0"), FriendlyName("xADOrganizationalUnit")] 
class MSFT_xADOrganizationalUnit : OMI_BaseResource
{
    [Key, Description("The name of OU")] string Name;
    [Key, Description("Specifies the X500 path of the OU or container where the new object is created")] string Path;
   
    [Write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] string Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"),Description("The credential to be used to perform the operation on Active Directory")] string Credential;
    [Write, Description("Defaults to True")] boolean ProtectedFromAccidentalDeletion;
    [Write, Description("The description of the OU")] string Description;
};

