[mongod.net]
bind_ip = "0.0.0.0"
ipv6 = false
max_incoming_connections = 65536
port = 27017
wire_object_check = true

[mongod.net.http]
enabled = false
jsonp_enabled = false
rest_interface_enabled = false

[mongod.net.ssl]
allow_connections_without_certificates = false
allow_invalid_certificates = false
allow_invalid_hostnames = false
ca_file = ""
cluster_file = ""
cluster_password = ""
crl_file = ""
disabled_protocols = ""
enabled = false
mode = "disabled"
pem_key_file = ""
pem_key_password = ""

[mongod.net.unix_domain_socket]
enabled = true
file_permissions = "0700"

[mongod.operation_profiling]
mode = "off"
slow_op_threshold = 100

[mongod.process_management]
fork = false
pid_file_path = ""

[mongod.replication]
enable_majority_read_concern = false
new_oplog_size = false
oplog_size_mb = 100
repl_set_name = ""
secondary_prefix_prefetch = "all"

[mongod.security]
authorization = "disabled"
cluster_auth_mode = "keyFile"
javascript_enabled = true
key_file = ""

[mongod.security.sasl]
enabled = false
host_name = ""
sasl_authd_socket_path = ""

[mongod.sharding]
archive_moved_chunks = false
cluster_role = ""

[mongod.snmp]
enabled = false
master = false
subagent = false

[mongod.storage]
directory_per_db = false
engine = "wiredTiger"
index_build_retry = true
repair_path = ""
sync_period_secs = 60

[mongod.storage.journal]
commit_intervals = 100
enabled = true

[mongod.storage.mmapv1]
ns_size = 16
prealloc_data_files = true
small_files = false

[mongod.storage.mmapv1.journal]
debug_flags = 0

[mongod.storage.mmapv1.quota]
enforced = false
max_files_per_db = 8
[mongod.storage.wired_tiger.collection_config]
block_compressor = "snappy"

[mongod.storage.wired_tiger.engine_config]
cache_size_gb = 1
directory_for_indexes = false
journal_compressor = "snappy"
new_cache = false

[mongod.storage.wired_tiger.index_config]
prefix_compression = true

[mongod.system_log]
destination = "file"
log_append = true
log_rotate = "rename"
quiet = false
syslog_facility = "user"
time_stamp_format = "iso8601-local"
trace_all_exceptions = true
verbosity = 0
[mongod.system_log.component.access_control]
verbosity = 0

[mongod.system_log.component.command]
verbosity = 0

[mongod.system_log.component.control]
verbosity = 0

[mongod.system_log.component.ftdc]
verbosity = 0

[mongod.system_log.component.geo]
verbosity = 0

[mongod.system_log.component.index]
verbosity = 0

[mongod.system_log.component.network]
verbosity = 0

[mongod.system_log.component.query]
verbosity = 0

[mongod.system_log.component.replication]
verbosity = 0

[mongod.system_log.component.sharding]
verbosity = 0

[mongod.system_log.component.storage]
verbosity = 0

[mongod.system_log.component.storage.journal]
verbosity = 0

[mongod.system_log.component.write]
verbosity = 0
[mongos.net]
bind_ip = "127.0.0.1"
ipv6 = false
max_incoming_connections = 65536
port = 27017
wire_object_check = true

[mongos.net.http]
enabled = false

[mongos.net.ssl]
allow_connections_without_certificates = false
allow_invalid_certificates = false
allow_invalid_hostnames = false
ca_file = ""
cluster_file = ""
cluster_password = ""
crl_file = ""
disabled_protocols = ""
mode = "disabled"
pem_key_file = ""
pem_key_password = ""

[mongos.net.unix_domain_socket]
enabled = true
file_permissions = "0700"

[mongos.process_management]
fork = false
pid_file_path = ""

[mongos.replication]
enable_majority_read_concern = false
local_ping_threshold = 15

[mongos.security]
cluster_auth_mode = ""
javascript_enabled = true
key_file = ""

[mongos.security.sasl]
enabled = false
host_name = ""
sasl_authd_socket_path = ""

[mongos.sharding]
archive_moved_chunks = false
auto_split = true
chunk_size = 64
config_db = ""
configsvr_mode = ""

[mongos.storage]
engine = "wiredTiger"
[mongos.storage.wired_tiger.collection_config]
block_compressor = "snappy"

[mongos.storage.wired_tiger.engine_config]
cache_size_gb = 1
directory_for_indexes = false
journal_compressor = "snappy"

[mongos.storage.wired_tiger.index_config]
prefix_compression = true

[mongos.system_log]
destination = ""
log_append = true
log_rotate = "rename"
quiet = false
syslog_facility = "user"
time_stamp_format = "iso8601-local"
trace_all_exceptions = true
verbosity = 0
[mongos.system_log.component.access_control]
verbosity = 0

[mongos.system_log.component.command]
verbosity = 0

[mongos.system_log.component.control]
verbosity = 0

[mongos.system_log.component.ftdc]
verbosity = 0

[mongos.system_log.component.geo]
verbosity = 0

[mongos.system_log.component.index]
verbosity = 0

[mongos.system_log.component.network]
verbosity = 0

[mongos.system_log.component.query]
verbosity = 0

[mongos.system_log.component.replication]
verbosity = 0

[mongos.system_log.component.sharding]
verbosity = 0

[mongos.system_log.component.storage]
verbosity = 0

[mongos.system_log.component.storage.journal]
verbosity = 0

[mongos.system_log.component.write]
verbosity = 0
