[ClassVersion("1.0.0.0"), FriendlyName("SPSelfServiceSiteCreation")]
class MSFT_SPSelfServiceSiteCreation : OMI_BaseResource
{
    [Key, Description("The url of the web application")] string WebAppUrl;
    [Required, Description("Specifies if users are allowed to create site collections or not")] boolean Enabled;
    [Write, Description("Specifies if site collections are created in SharePoint Online in a hybrid configuration. Hybrid configuration needs to be caried out seperately using the Hybrid Picker")] boolean OnlineEnabled;
    [Write, Description("The quota template to apply to new site collections. Specify null to not apply any qouta template")] string QuotaTemplate;
    [Write, Description("Should the Start a Site link be displayed. Must be false or not specified if Enabled is false")] boolean ShowStartASiteMenuItem;
    [Write, Description("Should Self Service Site Creation create an individual Site, false for a Site Collection")] boolean CreateIndividualSite;
    [Write, Description("Specifies the URL of the parent site where new sites are to be created. This is only used when CreateIndividualSite is true. Use [%userid%] to represent the ID of the user who is creating the site, for example: /projects/[%userid%]")] string ParentSiteUrl;
    [Write, Description("Specifies what site classification should be displayed"), ValueMap{"MustHavePolicy","CanHavePolicy","NotHavePolicy"}, Values{"MustHavePolicy","CanHavePolicy","NotHavePolicy"}] string PolicyOption;
    [Write, Description("Specifies if users needs to provide one or more additional site administrators")] boolean RequireSecondaryContact;
    [Write, Description("Specifies a custom form URL to use for Self Service Site Creation. This is only used when CreateIndividualSite is true. Must be an absolute URL or empty to use built in form (_layouts/_layouts/15/scsignup.aspx)")] string CustomFormUrl;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
