[ClassVersion("1.0.0.0")]
Class MSFT_SPLogLevelItem
{
    [Key, Description("Log Item Area")] String Area;
    [Key, Description("Log Item Name")] String Name;
    [Write, Description("Minimum severity to capture in the trace logs "), ValueMap{"None","Unexpected","Monitorable","High","Medium","Verbose","VerboseEx","Default"}, Values{"None","Unexpected","Monitorable","High","Medium","Verbose","VerboseEx","Default"}] String TraceLevel;
    [Write, Description("Minimum severity to capture in the event logs"), ValueMap{"None","ErrorCritical","Error","Warning","Information","Verbose","Default"}, Values{"None","ErrorCritical","Error","Warning","Information","Verbose","Default"}] String EventLevel;
};

[ClassVersion("1.0.0.0"), FriendlyName("SPLogLevel")]
class MSFT_SPLogLevel : OMI_BaseResource
{
    [Key, Description("Friendly Name used to reference this collection of log level settings")] String Name;
    [Required, Description("Collection of SPLogLevelItems to set"), EmbeddedInstance("MSFT_SPLogLevelItem")] String SPLogLevelSetting[];
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsCredential if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;
};
