// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

.create-or-alter function 
with (docstring = 'Return details about the specified ID.', folder = 'OpenData/Internal')
_resource_type_4(id: string) {
    dynamic({
        "microsoft.resourcegraph/queries": { "SingularDisplayName": "Resource Graph query" }
        ,"microsoft.resourcehealth/availabilitystatuses": { "SingularDisplayName": "Microsoft.ResourceHealth availability statuse" }
        ,"microsoft.resourcehealth/childavailabilitystatuses": { "SingularDisplayName": "Microsoft.ResourceHealth child availability statuse" }
        ,"microsoft.resourcehealth/emergingissues": { "SingularDisplayName": "Microsoft.ResourceHealth emerging issue" }
        ,"microsoft.resourcehealth/events": { "SingularDisplayName": "Microsoft.ResourceHealth event" }
        ,"microsoft.resourcehealth/events/impactedresources": { "SingularDisplayName": "Microsoft.ResourceHealth events impacted resource" }
        ,"microsoft.resourcehealth/metadata": { "SingularDisplayName": "Microsoft.ResourceHealth metadata" }
        ,"microsoft.resources/builtintemplatespecs": { "SingularDisplayName": "Built-in template spec" }
        ,"microsoft.resources/changes": { "SingularDisplayName": "Microsoft.Resources change" }
        ,"microsoft.resources/databoundaries": { "SingularDisplayName": "Microsoft.Resources data boundary" }
        ,"microsoft.resources/deletedresources": { "SingularDisplayName": "Recycle Bin" }
        ,"microsoft.resources/deployments": { "SingularDisplayName": "Microsoft.Resources deployment" }
        ,"microsoft.resources/deployments/operations": { "SingularDisplayName": "Microsoft.Resources deployments operation" }
        ,"microsoft.resources/deploymentscripts": { "SingularDisplayName": "Deployment Script" }
        ,"microsoft.resources/deploymentstacks": { "SingularDisplayName": "Deployment stack" }
        ,"microsoft.resources/mobobrokers": { "SingularDisplayName": "Microsoft.Resources mobo broker" }
        ,"microsoft.resources/resourcechange": { "SingularDisplayName": "Change Analysis" }
        ,"microsoft.resources/resourcechanges": { "SingularDisplayName": "Resource change" }
        ,"microsoft.resources/resourcegraphvisualizer": { "SingularDisplayName": "Resource Graph Visualizer" }
        ,"microsoft.resources/resourcegroups": { "SingularDisplayName": "Microsoft.Resources resource group" }
        ,"microsoft.resources/resources": { "SingularDisplayName": "Resource" }
        ,"microsoft.resources/snapshots": { "SingularDisplayName": "Microsoft.Resources snapshot" }
        ,"microsoft.resources/subscriptions": { "SingularDisplayName": "Subscription" }
        ,"microsoft.resources/subscriptions/resourcegroups": { "SingularDisplayName": "Resource group" }
        ,"microsoft.resources/tags": { "SingularDisplayName": "Microsoft.Resources tag" }
        ,"microsoft.resources/templatespecs": { "SingularDisplayName": "Template spec" }
        ,"microsoft.saas/applications": { "SingularDisplayName": "Software as a Service (classic)" }
        ,"microsoft.saas/resources": { "SingularDisplayName": "SaaS" }
        ,"microsoft.saas/saasresources": { "SingularDisplayName": "SaaS (classic)" }
        ,"microsoft.saashub/cloudservices/hidden": { "SingularDisplayName": "Microsoft SaaS" }
        ,"microsoft.salescopilot/conversationintelligencerecordingaccounts": { "SingularDisplayName": "Microsoft.SalesCopilot conversation intelligence recording account" }
        ,"microsoft.samplepartner/organizations": { "SingularDisplayName": "Sample Partner Resource" }
        ,"microsoft.scheduler/jobcollections": { "SingularDisplayName": "Scheduler job collection" }
        ,"microsoft.scheduler/jobcollections/jobs": { "SingularDisplayName": "Scheduler job" }
        ,"microsoft.scom/managedinstances": { "SingularDisplayName": "SCOM managed instance" }
        ,"microsoft.scvmm/availabilitysets": { "SingularDisplayName": "Microsoft.ScVmm availability set" }
        ,"microsoft.scvmm/clouds": { "SingularDisplayName": "Microsoft.ScVmm cloud" }
        ,"microsoft.scvmm/virtualmachineinstances": { "SingularDisplayName": "Microsoft.ScVmm virtual machine instance" }
        ,"microsoft.scvmm/virtualmachineinstances/guestagents": { "SingularDisplayName": "Microsoft.ScVmm virtual machine instances guest agent" }
        ,"microsoft.scvmm/virtualmachineinstances/hybrididentitymetadata": { "SingularDisplayName": "Microsoft.ScVmm virtual machine instances hybrid identity metadata" }
        ,"microsoft.scvmm/virtualmachines": { "SingularDisplayName": "SCVMM virtual machine - Azure Arc" }
        ,"microsoft.scvmm/virtualmachinetemplates": { "SingularDisplayName": "Microsoft.ScVmm virtual machine template" }
        ,"microsoft.scvmm/virtualnetworks": { "SingularDisplayName": "Microsoft.ScVmm virtual network" }
        ,"microsoft.scvmm/vmmservers": { "SingularDisplayName": "SCVMM management server" }
        ,"microsoft.search/searchservices": { "SingularDisplayName": "Search service" }
        ,"microsoft.secretmanagementsampleprovider/forecasts": { "SingularDisplayName": "Microsoft.SecretManagementSampleProvider forecast" }
        ,"microsoft.secretsynccontroller/azurekeyvaultsecretproviderclasses": { "SingularDisplayName": "Microsoft.SecretSyncController Azure key vault secret provider class" }
        ,"microsoft.secretsynccontroller/secretsyncs": { "SingularDisplayName": "Microsoft.SecretSyncController secret sync" }
        ,"microsoft.security/adaptivenetworkhardenings": { "SingularDisplayName": "Microsoft.Security adaptive network hardening" }
        ,"microsoft.security/advancedthreatprotectionsettings": { "SingularDisplayName": "Microsoft.Security advanced threat protection setting" }
        ,"microsoft.security/alertssuppressionrules": { "SingularDisplayName": "Microsoft.Security alerts suppression rule" }
        ,"microsoft.security/apicollections": { "SingularDisplayName": "Microsoft.Security API collection" }
        ,"microsoft.security/applications": { "SingularDisplayName": "Microsoft.Security application" }
        ,"microsoft.security/assessmentmetadata": { "SingularDisplayName": "Microsoft.Security assessment metadata" }
        ,"microsoft.security/assessments": { "SingularDisplayName": "Microsoft.Security assessment" }
        ,"microsoft.security/assessments/governanceassignments": { "SingularDisplayName": "Microsoft.Security assessments governance assignment" }
        ,"microsoft.security/assessments/subassessments": { "SingularDisplayName": "Microsoft.Security assessments sub assessment" }
        ,"microsoft.security/assignments": { "SingularDisplayName": "Microsoft.Security assignment" }
        ,"microsoft.security/automations": { "SingularDisplayName": "Microsoft.Security automation" }
        ,"microsoft.security/autoprovisioningsettings": { "SingularDisplayName": "Microsoft.Security auto provisioning setting" }
        ,"microsoft.security/complianceresults": { "SingularDisplayName": "Microsoft.Security compliance result" }
        ,"microsoft.security/compliances": { "SingularDisplayName": "Microsoft.Security compliance" }
        ,"microsoft.security/connectors": { "SingularDisplayName": "Microsoft.Security connector" }
        ,"microsoft.security/customassessmentautomations": { "SingularDisplayName": "Microsoft.Security custom assessment automation" }
        ,"microsoft.security/defenderforstoragesettings": { "SingularDisplayName": "Microsoft.Security defender for storage setting" }
        ,"microsoft.security/defenderforstoragesettings/malwarescans": { "SingularDisplayName": "Microsoft.Security defender for storage settings malware scan" }
        ,"microsoft.security/devicesecuritygroups": { "SingularDisplayName": "Microsoft.Security device security group" }
        ,"microsoft.security/governancerules": { "SingularDisplayName": "Microsoft.Security governance rule" }
        ,"microsoft.security/governancerules/operationresults": { "SingularDisplayName": "Microsoft.Security governance rules operation result" }
        ,"microsoft.security/healthreports": { "SingularDisplayName": "Microsoft.Security health report" }
        ,"microsoft.security/informationprotectionpolicies": { "SingularDisplayName": "Microsoft.Security information protection policy" }
        ,"microsoft.security/iotsecuritysolutions": { "SingularDisplayName": "Microsoft.Security IoT security solution" }
        ,"microsoft.security/iotsecuritysolutions/analyticsmodels": { "SingularDisplayName": "Microsoft.Security IoT security solutions analytics model" }
        ,"microsoft.security/iotsecuritysolutions/analyticsmodels/aggregatedalerts": { "SingularDisplayName": "Microsoft.Security IoT security solutions analytics models aggregated alert" }
        ,"microsoft.security/iotsecuritysolutions/analyticsmodels/aggregatedrecommendations": { "SingularDisplayName": "Microsoft.Security IoT security solutions analytics models aggregated recommendation" }
        ,"microsoft.security/iotsecuritysolutions/iotalerts": { "SingularDisplayName": "Microsoft.Security IoT security solutions IoT alert" }
        ,"microsoft.security/iotsecuritysolutions/iotalerttypes": { "SingularDisplayName": "Microsoft.Security IoT security solutions IoT alert type" }
        ,"microsoft.security/iotsecuritysolutions/iotrecommendations": { "SingularDisplayName": "Microsoft.Security IoT security solutions IoT recommendation" }
        ,"microsoft.security/iotsecuritysolutions/iotrecommendationtypes": { "SingularDisplayName": "Microsoft.Security IoT security solutions IoT recommendation type" }
        ,"microsoft.security/locations/alerts": { "SingularDisplayName": "Security Alert" }
        ,"microsoft.security/mdeonboardings": { "SingularDisplayName": "Microsoft.Security mde onboarding" }
        ,"microsoft.security/pricings": { "SingularDisplayName": "Defender for Cloud" }
        ,"microsoft.security/pricings/securityoperators": { "SingularDisplayName": "Microsoft.Security pricings security operator" }
        ,"microsoft.security/regulatorycompliancestandards": { "SingularDisplayName": "Microsoft.Security regulatory compliance standard" }
        ,"microsoft.security/regulatorycompliancestandards/regulatorycompliancecontrols": { "SingularDisplayName": "Microsoft.Security regulatory compliance standards regulatory compliance control" }
        ,"microsoft.security/regulatorycompliancestandards/regulatorycompliancecontrols/regulatorycomplianceassessments": { "SingularDisplayName": "Microsoft.Security regulatory compliance standards regulatory compliance controls regulatory compliance assessment" }
        ,"microsoft.security/securescores": { "SingularDisplayName": "Microsoft.Security secure score" }
        ,"microsoft.security/securityconnectors": { "SingularDisplayName": "Microsoft.Security security connector" }
        ,"microsoft.security/securityconnectors/devops": { "SingularDisplayName": "Microsoft.Security security connectors devop" }
        ,"microsoft.security/securitycontacts": { "SingularDisplayName": "Microsoft.Security security contact" }
        ,"microsoft.security/sensitivitysettings": { "SingularDisplayName": "Microsoft.Security sensitivity setting" }
        ,"microsoft.security/servervulnerabilityassessments": { "SingularDisplayName": "Microsoft.Security server vulnerability assessment" }
        ,"microsoft.security/servervulnerabilityassessmentssettings": { "SingularDisplayName": "Microsoft.Security server vulnerability assessments setting" }
        ,"microsoft.security/settings": { "SingularDisplayName": "Microsoft.Security setting" }
        ,"microsoft.security/standards": { "SingularDisplayName": "Microsoft.Security standard" }
        ,"microsoft.security/workspacesettings": { "SingularDisplayName": "Microsoft.Security workspace setting" }
        ,"microsoft.securitycopilot/capacities": { "SingularDisplayName": "Microsoft Security Copilot compute capacity" }
        ,"microsoft.securitydetonation/chambers": { "SingularDisplayName": "Security Detonation Chamber" }
        ,"microsoft.securityinsightsarg/sentinel": { "SingularDisplayName": "Microsoft Sentinel" }
        ,"microsoft.serialconsole/consoleservices": { "SingularDisplayName": "Microsoft.SerialConsole console service" }
        ,"microsoft.serialconsole/serialports": { "SingularDisplayName": "Microsoft.SerialConsole serial port" }
        ,"microsoft.servicebus/namespaces": { "SingularDisplayName": "Service Bus namespace" }
        ,"microsoft.servicebus/namespaces/disasterrecoveryconfigs": { "SingularDisplayName": "Service Bus Geo-DR Alias" }
        ,"microsoft.servicebus/namespaces/queues": { "SingularDisplayName": "Service Bus queue" }
        ,"microsoft.servicebus/namespaces/topics": { "SingularDisplayName": "Service Bus topic" }
        ,"microsoft.servicebus/namespaces/topics/subscriptions": { "SingularDisplayName": "Service Bus Subscription" }
        ,"microsoft.servicefabric/clusters": { "SingularDisplayName": "Service Fabric cluster" }
        ,"microsoft.servicefabric/managedclusters": { "SingularDisplayName": "Service Fabric managed cluster" }
        ,"microsoft.servicefabricmesh/applications": { "SingularDisplayName": "Microsoft.ServiceFabricMesh application" }
        ,"microsoft.servicefabricmesh/applications/services": { "SingularDisplayName": "Microsoft.ServiceFabricMesh applications service" }
        ,"microsoft.servicefabricmesh/applications/services/replicas": { "SingularDisplayName": "Microsoft.ServiceFabricMesh applications services replica" }
        ,"microsoft.servicefabricmesh/gateways": { "SingularDisplayName": "Microsoft.ServiceFabricMesh gateway" }
        ,"microsoft.servicefabricmesh/networks": { "SingularDisplayName": "Microsoft.ServiceFabricMesh network" }
        ,"microsoft.servicefabricmesh/secrets": { "SingularDisplayName": "Microsoft.ServiceFabricMesh secret" }
        ,"microsoft.servicefabricmesh/secrets/values": { "SingularDisplayName": "Microsoft.ServiceFabricMesh secrets value" }
        ,"microsoft.servicefabricmesh/volumes": { "SingularDisplayName": "Microsoft.ServiceFabricMesh volume" }
        ,"microsoft.servicelinker/dryruns": { "SingularDisplayName": "Microsoft.ServiceLinker dryrun" }
        ,"microsoft.servicelinker/linkers": { "SingularDisplayName": "Microsoft.ServiceLinker linker" }
        ,"microsoft.servicenetworking/trafficcontrollers": { "SingularDisplayName": "Application Gateway for Containers" }
        ,"microsoft.serviceshub/connectors": { "SingularDisplayName": "Services Hub Connector" }
        ,"microsoft.signalrservice/signalr": { "SingularDisplayName": "SignalR" }
        ,"microsoft.signalrservice/signalr/replicas": { "SingularDisplayName": "SignalR Replica" }
        ,"microsoft.signalrservice/webpubsub": { "SingularDisplayName": "Web PubSub Service" }
        ,"microsoft.signalrservice/webpubsub/replicas": { "SingularDisplayName": "Web PubSub Service Replica" }
        ,"microsoft.skytap/billingnodes": { "SingularDisplayName": "Microsoft.Skytap billing node" }
        ,"microsoft.skytap/interfaces": { "SingularDisplayName": "Microsoft.Skytap interface" }
        ,"microsoft.skytap/nodes": { "SingularDisplayName": "Microsoft.Skytap node" }
        ,"microsoft.softwareplan/hybridusebenefits": { "SingularDisplayName": "Microsoft.SoftwarePlan hybrid use benefit" }
        ,"microsoft.solutions/applicationdefinitions": { "SingularDisplayName": "Service catalog managed application definition" }
        ,"microsoft.solutions/applications": { "SingularDisplayName": "Managed application" }
        ,"microsoft.solutions/jitrequests": { "SingularDisplayName": "Microsoft.Solutions JIT request" }
        ,"microsoft.sovereign/landingzoneaccounts": { "SingularDisplayName": "Landing zone accounts" }
        ,"microsoft.sovereign/landingzoneaccounts/landingzoneconfigurations": { "SingularDisplayName": "Landing Zone Configuration" }
        ,"microsoft.sovereign/landingzoneaccounts/landingzoneregistrations": { "SingularDisplayName": "Landing Zone Registration" }
        ,"microsoft.sovereign/landingzoneconfigurations": { "SingularDisplayName": "Landing Zone Configuration" }
        ,"microsoft.sovereign/landingzoneregistrations": { "SingularDisplayName": "Landing Zone Registration" }
        ,"microsoft.sovereign/transparencylogs": { "SingularDisplayName": "Transparency log" }
        ,"microsoft.sql/azuresql": { "SingularDisplayName": "Azure SQL resource" }
        ,"microsoft.sql/instancepools": { "SingularDisplayName": "Instance pool" }
        ,"microsoft.sql/managedinstances": { "SingularDisplayName": "SQL managed instance" }
        ,"microsoft.sql/managedinstances/databases": { "SingularDisplayName": "Managed database" }
        ,"microsoft.sql/servers": { "SingularDisplayName": "SQL server" }
        ,"microsoft.sql/servers/databases": { "SingularDisplayName": "SQL database" }
        ,"microsoft.sql/servers/elasticpools": { "SingularDisplayName": "SQL elastic pool" }
        ,"microsoft.sql/servers/jobagents": { "SingularDisplayName": "Elastic Job agent" }
        ,"microsoft.sql/virtualclusters": { "SingularDisplayName": "Virtual cluster" }
        ,"microsoft.sqlvirtualmachine/sqlvirtualmachinegroups": { "SingularDisplayName": "Microsoft.SqlVirtualMachine sql virtual machine group" }
        ,"microsoft.sqlvirtualmachine/sqlvirtualmachinegroups/availabilitygrouplisteners": { "SingularDisplayName": "Microsoft.SqlVirtualMachine sql virtual machine groups availability group listener" }
        ,"microsoft.sqlvirtualmachine/sqlvirtualmachines": { "SingularDisplayName": "SQL virtual machine" }
        ,"microsoft.standbypool/standbycontainergrouppools": { "SingularDisplayName": "Microsoft.StandbyPool standby container group pool" }
        ,"microsoft.standbypool/standbycontainergrouppools/runtimeviews": { "SingularDisplayName": "Microsoft.StandbyPool standby container group pools runtime view" }
        ,"microsoft.standbypool/standbyvirtualmachinepools": { "SingularDisplayName": "Microsoft.StandbyPool standby virtual machine pool" }
        ,"microsoft.standbypool/standbyvirtualmachinepools/runtimeviews": { "SingularDisplayName": "Microsoft.StandbyPool standby virtual machine pools runtime view" }
        ,"microsoft.standbypool/standbyvirtualmachinepools/standbyvirtualmachines": { "SingularDisplayName": "Microsoft.StandbyPool standby virtual machine pools standby virtual machine" }
        ,"microsoft.storage/storageaccounts": { "SingularDisplayName": "Storage account" }
        ,"microsoft.storageactions/storagetasks": { "SingularDisplayName": "Storage task - Azure Storage Actions" }
        ,"microsoft.storagecache/amlfilesystems": { "SingularDisplayName": "Azure Managed Lustre" }
        ,"microsoft.storagecache/caches": { "SingularDisplayName": "HPC cache" }
        ,"microsoft.storageinsights/storagecollectionrules": { "SingularDisplayName": "Microsoft.StorageInsights storage collection rule" }
        ,"microsoft.storagemover/storagemovers": { "SingularDisplayName": "Storage mover" }
        ,"microsoft.storagepool/diskpools": { "SingularDisplayName": "Microsoft.StoragePool disk pool" }
        ,"microsoft.storagepool/diskpools/iscsitargets": { "SingularDisplayName": "Microsoft.StoragePool disk pools iscsi target" }
        ,"microsoft.storagesync/storagesyncservices": { "SingularDisplayName": "Storage Sync Service" }
        ,"microsoft.storagetasks/storagetasks": { "SingularDisplayName": "Microsoft.StorageTasks storage task" }
        ,"microsoft.storsimple/managers": { "SingularDisplayName": "StorSimple device manager" }
        ,"microsoft.storsimple/managers/accesscontrolrecords": { "SingularDisplayName": "Microsoft.StorSimple managers access control record" }
        ,"microsoft.storsimple/managers/bandwidthsettings": { "SingularDisplayName": "Microsoft.StorSimple managers bandwidth setting" }
        ,"microsoft.storsimple/managers/certificates": { "SingularDisplayName": "Microsoft.StorSimple managers certificate" }
        ,"microsoft.storsimple/managers/devices": { "SingularDisplayName": "Microsoft.StorSimple managers device" }
        ,"microsoft.storsimple/managers/devices/alertsettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices alert setting" }
        ,"microsoft.storsimple/managers/devices/backuppolicies": { "SingularDisplayName": "Microsoft.StorSimple managers devices backup policy" }
        ,"microsoft.storsimple/managers/devices/backuppolicies/schedules": { "SingularDisplayName": "Microsoft.StorSimple managers devices backup policies schedule" }
        ,"microsoft.storsimple/managers/devices/backupschedulegroups": { "SingularDisplayName": "Microsoft.StorSimple managers devices backup schedule group" }
        ,"microsoft.storsimple/managers/devices/chapsettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices chap setting" }
        ,"microsoft.storsimple/managers/devices/fileservers": { "SingularDisplayName": "Microsoft.StorSimple managers devices fileserver" }
        ,"microsoft.storsimple/managers/devices/fileservers/shares": { "SingularDisplayName": "Microsoft.StorSimple managers devices fileservers share" }
        ,"microsoft.storsimple/managers/devices/iscsiservers": { "SingularDisplayName": "Microsoft.StorSimple managers devices iscsiserver" }
        ,"microsoft.storsimple/managers/devices/iscsiservers/disks": { "SingularDisplayName": "Microsoft.StorSimple managers devices iscsiservers disk" }
        ,"microsoft.storsimple/managers/devices/jobs": { "SingularDisplayName": "Microsoft.StorSimple managers devices job" }
        ,"microsoft.storsimple/managers/devices/networksettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices network setting" }
        ,"microsoft.storsimple/managers/devices/securitysettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices security setting" }
        ,"microsoft.storsimple/managers/devices/timesettings": { "SingularDisplayName": "Microsoft.StorSimple managers devices time setting" }
        ,"microsoft.storsimple/managers/devices/updatesummary": { "SingularDisplayName": "Microsoft.StorSimple managers devices update summary" }
        ,"microsoft.storsimple/managers/devices/volumecontainers": { "SingularDisplayName": "Microsoft.StorSimple managers devices volume container" }
        ,"microsoft.storsimple/managers/devices/volumecontainers/volumes": { "SingularDisplayName": "Microsoft.StorSimple managers devices volume containers volume" }
        ,"microsoft.storsimple/managers/encryptionsettings": { "SingularDisplayName": "Microsoft.StorSimple managers encryption setting" }
        ,"microsoft.storsimple/managers/extendedinformation": { "SingularDisplayName": "Microsoft.StorSimple managers extended information" }
        ,"microsoft.storsimple/managers/storageaccountcredentials": { "SingularDisplayName": "Microsoft.StorSimple managers storage account credential" }
        ,"microsoft.storsimple/managers/storagedomains": { "SingularDisplayName": "Microsoft.StorSimple managers storage domain" }
        ,"microsoft.streamanalytics/clusters": { "SingularDisplayName": "Stream Analytics cluster" }
        ,"microsoft.streamanalytics/streamingjobs": { "SingularDisplayName": "Stream Analytics job" }
        ,"microsoft.subscription/aliases": { "SingularDisplayName": "Microsoft.Subscription aliase" }
        ,"microsoft.subscription/changetenantrequest": { "SingularDisplayName": "Microsoft.Subscription change tenant request" }
        ,"microsoft.subscription/policies": { "SingularDisplayName": "Microsoft.Subscription policy" }
        ,"microsoft.subscription/subscriptiondefinitions": { "SingularDisplayName": "Microsoft.Subscription subscription definition" }
        ,"microsoft.subscription/subscriptionoperations": { "SingularDisplayName": "Microsoft.Subscription subscription operation" }
        ,"microsoft.support/fileworkspaces": { "SingularDisplayName": "Microsoft.Support file workspace" }
        ,"microsoft.support/fileworkspaces/files": { "SingularDisplayName": "Microsoft.Support file workspaces file" }
        ,"microsoft.support/services": { "SingularDisplayName": "Microsoft.Support service" }
        ,"microsoft.support/services/problemclassifications": { "SingularDisplayName": "Microsoft.Support services problem classification" }
        ,"microsoft.support/supporttickets": { "SingularDisplayName": "Support Request" }
        ,"microsoft.sustainabilityservices/calculations": { "SingularDisplayName": "Microsoft.SustainabilityServices calculation" }
        ,"microsoft.symphony/instances": { "SingularDisplayName": "Microsoft.Symphony instance" }
        ,"microsoft.symphony/solutions": { "SingularDisplayName": "Microsoft.Symphony solution" }
        ,"microsoft.symphony/targets": { "SingularDisplayName": "Microsoft.Symphony target" }
        ,"microsoft.synapse/privatelinkhubs": { "SingularDisplayName": "Synapse private link hub" }
        ,"microsoft.synapse/workspaces": { "SingularDisplayName": "Synapse workspace" }
        ,"microsoft.synapse/workspaces/bigdatapools": { "SingularDisplayName": "Apache Spark pool" }
        ,"microsoft.synapse/workspaces/kustopools": { "SingularDisplayName": "Data Explorer pool" }
        ,"microsoft.synapse/workspaces/kustopools/databases": { "SingularDisplayName": "Data Explorer Database" }
        ,"microsoft.synapse/workspaces/scopepools": { "SingularDisplayName": "SCOPE pool" }
        ,"microsoft.synapse/workspaces/sqlpools": { "SingularDisplayName": "Dedicated SQL pool" }
        ,"microsoft.syntex/accounts": { "SingularDisplayName": "Microsoft.Syntex account" }
        ,"microsoft.syntex/documentprocessors": { "SingularDisplayName": "Microsoft.Syntex document processor" }
        ,"microsoft.test/healthdataaiservices": { "SingularDisplayName": "Azure Health Data and AI Services" }
        ,"microsoft.timeseriesinsights/environments": { "SingularDisplayName": "Microsoft.TimeSeriesInsights environment" }
        ,"microsoft.timeseriesinsights/environments/accesspolicies": { "SingularDisplayName": "Microsoft.TimeSeriesInsights environments access policy" }
        ,"microsoft.timeseriesinsights/environments/eventsources": { "SingularDisplayName": "Microsoft.TimeSeriesInsights environments event source" }
        ,"microsoft.timeseriesinsights/environments/referencedatasets": { "SingularDisplayName": "Microsoft.TimeSeriesInsights environments reference data set" }
        ,"microsoft.toolchainorchestrator/activations": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator activation" }
        ,"microsoft.toolchainorchestrator/campaigns": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator campaign" }
        ,"microsoft.toolchainorchestrator/campaigns/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator campaigns version" }
        ,"microsoft.toolchainorchestrator/catalogs": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator catalog" }
        ,"microsoft.toolchainorchestrator/catalogs/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator catalogs version" }
        ,"microsoft.toolchainorchestrator/instances": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator instance" }
        ,"microsoft.toolchainorchestrator/instances/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator instances version" }
        ,"microsoft.toolchainorchestrator/solutions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator solution" }
        ,"microsoft.toolchainorchestrator/solutions/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator solutions version" }
        ,"microsoft.toolchainorchestrator/targets": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator target" }
        ,"microsoft.toolchainorchestrator/targets/versions": { "SingularDisplayName": "Microsoft.ToolchainOrchestrator targets version" }
        ,"microsoft.usagebilling/accounts": { "SingularDisplayName": "Microsoft.UsageBilling account" }
        ,"microsoft.usagebilling/accounts/dataexports": { "SingularDisplayName": "Microsoft.UsageBilling accounts data export" }
        ,"microsoft.usagebilling/accounts/inputs": { "SingularDisplayName": "Microsoft.UsageBilling accounts input" }
        ,"microsoft.usagebilling/accounts/metricexports": { "SingularDisplayName": "Microsoft.UsageBilling accounts metric export" }
        ,"microsoft.usagebilling/accounts/pav2outputs": { "SingularDisplayName": "Microsoft.UsageBilling accounts pav2output" }
        ,"microsoft.usagebilling/accounts/pipelines": { "SingularDisplayName": "Microsoft.UsageBilling accounts pipeline" }
        ,"microsoft.usagebilling/accounts/pipelines/outputselectors": { "SingularDisplayName": "Microsoft.UsageBilling accounts pipelines output selector" }
        ,"microsoft.verifiedid/authorities": { "SingularDisplayName": "Microsoft.VerifiedId authority" }
        ,"microsoft.videoindexer/accounts": { "SingularDisplayName": "Azure AI Video Indexer" }
        ,"microsoft.virtualmachineimages/imagetemplates": { "SingularDisplayName": "Image template" }
        ,"microsoft.visualstudio/account": { "SingularDisplayName": "Azure DevOps organization" }
        ,"microsoft.vmware/resourcepools": { "SingularDisplayName": "Microsoft.VMware resource pool" }
        ,"microsoft.vmware/vcenters": { "SingularDisplayName": "Microsoft.VMware vcenter" }
        ,"microsoft.vmware/vcenters/inventoryitems": { "SingularDisplayName": "Microsoft.VMware vcenters inventory item" }
        ,"microsoft.vmware/virtualmachines": { "SingularDisplayName": "Microsoft.VMware virtual machine" }
        ,"microsoft.vmware/virtualmachinetemplates": { "SingularDisplayName": "Microsoft.VMware virtual machine template" }
        ,"microsoft.vmware/virtualnetworks": { "SingularDisplayName": "Microsoft.VMware virtual network" }
        ,"microsoft.vmwarecloudsimple/dedicatedcloudnodes": { "SingularDisplayName": "Microsoft.VMwareCloudSimple dedicated cloud node" }
        ,"microsoft.vmwarecloudsimple/dedicatedcloudservices": { "SingularDisplayName": "Microsoft.VMwareCloudSimple dedicated cloud service" }
        ,"microsoft.vmwarecloudsimple/virtualmachines": { "SingularDisplayName": "Microsoft.VMwareCloudSimple virtual machine" }
        ,"microsoft.vnfmanager/devices": { "SingularDisplayName": "Microsoft.VnfManager device" }
        ,"microsoft.vnfmanager/vendors": { "SingularDisplayName": "Microsoft.VnfManager vendor" }
        ,"microsoft.vnfmanager/vendors/skus": { "SingularDisplayName": "Microsoft.VnfManager vendors SKU" }
        ,"microsoft.vnfmanager/vnfs": { "SingularDisplayName": "Microsoft.VnfManager vnf" }
        ,"microsoft.voiceservices/communicationsgateways": { "SingularDisplayName": "Communications Gateway" }
        ,"microsoft.voiceservices/communicationsgateways/testlines": { "SingularDisplayName": "Communications Gateway Test Line" }
        ,"microsoft.vsonline/accounts": { "SingularDisplayName": "Microsoft.VSOnline account" }
        ,"microsoft.vsonline/plans": { "SingularDisplayName": "Visual Studio Online Plan" }
        ,"microsoft.web/certificates": { "SingularDisplayName": "Microsoft.Web certificate" }
        ,"microsoft.web/connectiongateways": { "SingularDisplayName": "App Service on-premises data gateway" }
        ,"microsoft.web/connections": { "SingularDisplayName": "App Service API connection" }
        ,"microsoft.web/containerapps": { "SingularDisplayName": "Microsoft.Web container app" }
        ,"microsoft.web/containerapps/revisions": { "SingularDisplayName": "Microsoft.Web container apps revision" }
        ,"microsoft.web/customapis": { "SingularDisplayName": "Logic apps custom connector" }
        ,"microsoft.web/deletedsites": { "SingularDisplayName": "Microsoft.Web deleted site" }
        ,"microsoft.web/hostingenvironments": { "SingularDisplayName": "App Service Environment" }
        ,"microsoft.web/ishostingenvironmentnameavailable": { "SingularDisplayName": "Microsoft.Web ishostingenvironmentnameavailable" }
        ,"microsoft.web/kubeenvironments": { "SingularDisplayName": "App Service Kubernetes Environment" }
        ,"microsoft.web/publishingusers": { "SingularDisplayName": "Microsoft.Web publishing user" }
        ,"microsoft.web/serverfarms": { "SingularDisplayName": "App Service plan" }
        ,"microsoft.web/sites": { "SingularDisplayName": "App Service web app" }
        ,"microsoft.web/sites/slots": { "SingularDisplayName": "App Service deployment slot" }
        ,"microsoft.web/sourcecontrols": { "SingularDisplayName": "Microsoft.Web sourcecontrol" }
        ,"microsoft.web/staticsites": { "SingularDisplayName": "Static Web App" }
        ,"microsoft.weightsandbiases/instances": { "SingularDisplayName": "Azure Native WeightsAndBiases Cloud Service" }
        ,"microsoft.whiteboxcadlprovider/whiteboxresources": { "SingularDisplayName": "Microsoft.WhiteBoxCadlProvider white box resource" }
        ,"microsoft.windows365/cloudpcdelegatedmsis": { "SingularDisplayName": "Microsoft.Windows365 cloud pc delegated msi" }
        ,"microsoft.windowsesu/multipleactivationkeys": { "SingularDisplayName": "Microsoft.WindowsESU multiple activation key" }
        ,"microsoft.windowsiot/deviceservices": { "SingularDisplayName": "Microsoft.WindowsIoT device service" }
        ,"microsoft.windowspushnotificationservices/registrations": { "SingularDisplayName": "Microsoft.WindowsPushNotificationServices registration" }
        ,"microsoft.workloadmonitor/monitors": { "SingularDisplayName": "Microsoft.WorkloadMonitor monitor" }
        ,"microsoft.workloadmonitor/monitors/history": { "SingularDisplayName": "Microsoft.WorkloadMonitor monitors history" }
        ,"microsoft.workloads/connectors": { "SingularDisplayName": "Microsoft.Workloads connector" }
        ,"microsoft.workloads/connectors/acssbackups": { "SingularDisplayName": "Microsoft.Workloads connectors acss backup" }
        ,"microsoft.workloads/connectors/amsinsights": { "SingularDisplayName": "Microsoft.Workloads connectors ams insight" }
        ,"microsoft.workloads/connectors/sapvirtualinstancemonitors": { "SingularDisplayName": "Microsoft.Workloads connectors sap virtual instance monitor" }
        ,"microsoft.workloads/epicvirtualinstances": { "SingularDisplayName": "Virtual Instance for Epic solution" }
        ,"microsoft.workloads/insights": { "SingularDisplayName": "Microsoft.Workloads insight" }
        ,"microsoft.workloads/monitors": { "SingularDisplayName": "Azure Monitor for SAP solutions" }
        ,"microsoft.workloads/oraclevirtualinstances": { "SingularDisplayName": "Microsoft.Workloads oracle virtual instance" }
        ,"microsoft.workloads/oraclevirtualinstances/databaseinstances": { "SingularDisplayName": "Microsoft.Workloads oracle virtual instances database instance" }
        ,"microsoft.workloads/phpworkloads": { "SingularDisplayName": "Microsoft.Workloads php workload" }
        ,"microsoft.workloads/phpworkloads/wordpressinstances": { "SingularDisplayName": "Microsoft.Workloads php workloads wordpress instance" }
        ,"microsoft.workloads/sapdiscoverysites": { "SingularDisplayName": "Microsoft.Workloads sap discovery site" }
        ,"microsoft.workloads/sapdiscoverysites/sapinstances": { "SingularDisplayName": "Microsoft.Workloads sap discovery sites sap instance" }
        ,"microsoft.workloads/sapdiscoverysites/sapinstances/serverinstances": { "SingularDisplayName": "Microsoft.Workloads sap discovery sites sap instances server instance" }
        ,"microsoft.workloads/sapvirtualinstances": { "SingularDisplayName": "Virtual Instance for SAP solutions" }
        ,"microsoft.workloads/sapvirtualinstances/applicationinstances": { "SingularDisplayName": "App server instance for SAP solutions" }
        ,"microsoft.workloads/sapvirtualinstances/centralinstances": { "SingularDisplayName": "Central service instance for SAP solutions" }
        ,"microsoft.workloads/sapvirtualinstances/databaseinstances": { "SingularDisplayName": "Database for SAP solutions" }
        ,"neon.postgres/organizations": { "SingularDisplayName": "Neon Serverless Postgres Resource" }
        ,"newrelic.observability/monitors": { "SingularDisplayName": "New Relic" }
        ,"nginx.nginxplus/nginxdeployments": { "SingularDisplayName": "NGINXaaS" }
        ,"oracle.database/autonomousdatabases": { "SingularDisplayName": "Autonomous Database" }
        ,"oracle.database/cloudexadatainfrastructures": { "SingularDisplayName": "Oracle Exadata Infrastructure" }
        ,"oracle.database/cloudvmclusters": { "SingularDisplayName": "Oracle Exadata VM Cluster" }
        ,"oracle.database/oraclesubscriptions": { "SingularDisplayName": "OracleSubscription" }
        ,"paloaltonetworks.cloudngfw/firewalls": { "SingularDisplayName": "Cloud NGFW by Palo Alto Networks" }
        ,"paloaltonetworks.cloudngfw/globalrulestacks": { "SingularDisplayName": "Global Rulestack" }
        ,"paloaltonetworks.cloudngfw/localrulestacks": { "SingularDisplayName": "Local Rulestack for Cloud NGFW by Palo Alto Networks" }
        ,"pinecone.vectordb/organizations": { "SingularDisplayName": "Azure Native Pinecone Cloud Service" }
        ,"purestorage.block/reservations": { "SingularDisplayName": "Azure Native Pure Storage Cloud Service" }
        ,"purestorage.block/storagepools": { "SingularDisplayName": "Storage pool" }
        ,"purestorage.block/storagepools/avsstoragecontainers": { "SingularDisplayName": "PureStorage.Block storage pools avs storage container" }
        ,"qumulo.qaas/storages": { "SingularDisplayName": "Qumulo.QaaS storage" }
        ,"qumulo.storage/filesystems": { "SingularDisplayName": "Azure Native Qumulo Scalable File Service" }
        ,"solarwinds.observability/organizations": { "SingularDisplayName": "SolarWinds Observability" }
        ,"splitio.experimentation/experimentationworkspaces": { "SingularDisplayName": "Split Experimentation Workspace" }
        ,"wandisco.fusion/migrators": { "SingularDisplayName": "LiveData Migrator" }
        ,"wandisco.fusion/migrators/datatransferagents": { "SingularDisplayName": "Data Transfer Agent" }
        ,"wandisco.fusion/migrators/exclusiontemplates": { "SingularDisplayName": "Exclusion" }
        ,"wandisco.fusion/migrators/livedatamigrations": { "SingularDisplayName": "Migration" }
        ,"wandisco.fusion/migrators/metadatamigrations": { "SingularDisplayName": "Metadata Migration" }
        ,"wandisco.fusion/migrators/metadatatargets": { "SingularDisplayName": "Metadata Target" }
        ,"wandisco.fusion/migrators/pathmappings": { "SingularDisplayName": "Path Mapping" }
        ,"wandisco.fusion/migrators/targets": { "SingularDisplayName": "Target" }
        ,"wandisco.fusion/migrators/verifications": { "SingularDisplayName": "Verification" }
    })[tolower(id)]
}
