[ClassVersion("1.0"), FriendlyName("xNetConnectionProfile")]
class MSFT_xNetConnectionProfile : OMI_BaseResource
{
[Key] string InterfaceAlias;
[Write,ValueMap{"Disconnected", "NoTraffic", "Subnet", "LocalNetwork", "Internet"},Values{"Disconnected", "NoTraffic", "Subnet", "LocalNetwork", "Internet"}] string IPv4Connectivity;
[Write,ValueMap{"Disconnected", "NoTraffic", "Subnet", "LocalNetwork", "Internet"},Values{"Disconnected", "NoTraffic", "Subnet", "LocalNetwork", "Internet"}] string IPv6Connectivity;
[Write,ValueMap{"Public", "Private"},Values{"Public", "Private"}] string NetworkCategory;
};
