name: Build Bicep
# This action can be run on-demand against a branch.
# TODO asdf It attempts to build the main.bicep update the baseline files, and commits and pushes changes if there are any.

on:
  workflow_dispatch:

jobs:
  main:
    name: Build Bicep
    runs-on: ubuntu-latest

    env:
      # don't print dotnet logo
      DOTNET_NOLOGO: true

      # disable telemetry (reduces dotnet tool output in logs)
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1.8.0
      
      - name: Install Bicep
        # See https://github.com/Azure/bicep/blob/main/docs/installing.md#windows-installer
        run: |
          # Create the install folder
          INSTALL_PATH="$RUNNER_TEMP/bicep"
          mkdir -pv $INSTALL_PATH
          BICEP_PATH=$INSTALL_PATH/bicep.bin
 
          # Fetch the latest Bicep CLI binary
          curl -Lo bicep.bin https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep.bin
          sudo mv ./bicep.bin $INSTALL_PATH
          echo Using bicep at $BICEP_PATH:
          $BICEP_PATH --version

      - name: Build main.bicep
        run: $BICE_PATH build main.bicep --outfile azdeploy.json
          
          # - name: Commit baselines
          #   run: |
          #     git config --global user.email "bicep@noreply.github.com"
          #     git config --global user.name "Bicep Automation"

          #     git add .

          #     if ! git diff-index --quiet HEAD --; then
          #       git commit -m "Update test baselines"
          #       git push
          #     fi