#!/bin/bash

exec 2>&1

echo "Seeding Mongo Collection"

MONGODB_HOME=$(hab pkg path core/mongo-tools)

source {{pkg.svc_config_path}}/mongoimport-opts.conf
echo "\$MONGOIMPORT_OPTS=$MONGOIMPORT_OPTS"

echo "sys.ip        = {{sys.ip}}"
echo "sys.hostname  = {{sys.hostname}}"
echo "pkg.origin    = {{pkg.origin}}"
echo "pkg.name      = {{pkg.name}}"
echo "pkg.version   = {{pkg.version}}"
echo "pkg.release   = {{pkg.release}}"
echo "pkg.ident     = {{pkg.ident}}"
echo "pkg.deps      = {{pkg.deps}}"
echo "pkg.exposes   = {{pkg.exposes}}"
echo "pkg.svc_path          = {{pkg.svc_path}}"
echo "pkg.svc_config_path   = {{pkg.svc_config_path}}"
echo "pkg.svc_data_path     = {{pkg.svc_data_path}}"
echo "pkg.svc_files_path    = {{pkg.svc_files_path}}"
echo "pkg.svc_static_path   = {{pkg.svc_static_path}}"
echo "pkg.svc_var_path      = {{pkg.svc_var_path}}"

cp -vrf $(hab pkg path {{pkg.origin}}/national-parks)/national-parks.war $(hab pkg path core/tomcat8)/tc/webapps/

echo ${MONGODB_HOME}/bin/mongoimport --drop -d demo -c nationalparks --type json --jsonArray --file $(hab pkg path {{pkg.origin}}/national-parks)/national-parks.json ${MONGOIMPORT_OPTS}
${MONGODB_HOME}/bin/mongoimport --drop -d demo -c nationalparks --type json --jsonArray --file $(hab pkg path {{pkg.origin}}/national-parks)/national-parks.json ${MONGOIMPORT_OPTS}
